### ISSUE TITLE
脚本执行权限问题

### ISSUE THREAD

**Issue by maplewang** [jinwyp/one_click_script#1]
没有sudo 执行./trojan_v2ray_install.sh 需要不但输入sudo 用户密码，但是很多时候还是不行， 比如这个pam_authenticate failed: trojanuser 用户有sudo 权限，但是脚本执行不下去。
ubuntu 18.04 amd x64 .

`==== AUTHENTICATING FOR org.freedesktop.systemd1.reload-daemon ===
Authentication is required to reload the systemd state.
Authenticating as: user,,, (user)
Password:
polkit-agent-helper-1: pam_authenticate failed: Authentication failure
==== AUTHENTICATION FAILED ===
Failed to reload daemon: Access denied
Sibt==== AUTHENTICATING FOR org.freedesktop.systemd1.reload-daemon ===
Authentication is required to reload the systemd state.
Authenticating as: user,,, (user)
Password:
polkit-agent-helper-1: pam_authenticate failed: Authentication failure
==== AUTHENTICATION FAILED ===
Failed to reload daemon: Access denied`

**Comment by jinwyp** [comment]
选的是菜单哪项执行的？

**Comment by maplewang** [comment]
我是准备装trojan go 的. 看来我理解的问题 这个脚本其实一定要root 装 我用sudo 装不行的，建议在说明里面加上一条，用root 或者有sudo 权限的用户su到root 也可以吧？

**Comment by jinwyp** [comment]
> 我是准备装trojan go 的. 看来我理解的问题 这个脚本其实一定要root 装 我用sudo 装不行的，建议在说明里面加上一条，用root 或者有sudo 权限的用户su到root 也可以吧？

对
