### ISSUE TITLE
web面板安装后的问题

### ISSUE THREAD

**Issue by FantasticSkyBaby** [jinwyp/one_click_script#10]
1、web面板安装后，访问域名还是welcome to nginx！页面
2、终端关掉后没有保存面板后台地址，第二次在哪看，貌似打开也是welcome to nginx！

**Comment by FantasticSkyBaby** [comment]
3、选择升级trojan面板，貌似没有升级成功，如图
![image](https://user-images.githubusercontent.com/14800057/92453555-fbac3200-f1f1-11ea-8a74-801d2641f0b0.png)

**Comment by jinwyp** [comment]
什么系统  目前除了centos 7  其余都有问题

**Comment by FantasticSkyBaby** [comment]
> 什么系统 目前除了centos 7 其余都有问题

debian 10，我原来用的debian 9没问题

**Comment by jinwyp** [comment]
> > 什么系统 目前除了centos 7 其余都有问题
> 
> debian 10，我原来用的debian 9没问题

https://github.com/Jrohy/trojan/issues/272  我在谷歌云试过了 都有问题

**Comment by FantasticSkyBaby** [comment]
终端关闭掉后没有保存面板后台地址，第二次在哪看
这个问题怎么看

**Comment by jinwyp** [comment]
> 终端关闭掉后没有保存面板后台地址，第二次在哪看
> 这个问题怎么看

只能看nginx 配置 /etc/nginx/nginx.conf  里面有路径

**Comment by jinwyp** [comment]
如果安装失败 可以手动申请证书 trojan-web tls  然后手动 安装mysql  运行trojan-web 选3.安装管理  再选3.安装mysql

**Comment by FantasticSkyBaby** [comment]
我用波仔的这个脚本debian9可以正常打开后台管理页面
https://www.v2rayssr.com/trojanpanel.html

**Comment by jinwyp** [comment]
> 我用波仔的这个脚本debian9可以正常打开后台管理页面
> https://www.v2rayssr.com/trojanpanel.html

我在谷歌云上 用官方脚本 source <(curl -sL https://git.io/trojan-install)  安装报错 

你是什么VPS

**Comment by FantasticSkyBaby** [comment]
> > 我用波仔的这个脚本debian9可以正常打开后台管理页面
> > https://www.v2rayssr.com/trojanpanel.html
> 
> 我在谷歌云上 用官方脚本 source <(curl -sL https://git.io/trojan-install) 安装报错
> 
> 你是哪家的VPS？

banwagong

**Comment by FantasticSkyBaby** [comment]
> > > 我用波仔的这个脚本debian9可以正常打开后台管理页面
> > > https://www.v2rayssr.com/trojanpanel.html
> > 
> > 
> > 我在谷歌云上 用官方脚本 source <(curl -sL https://git.io/trojan-install) 安装报错
> > 你是哪家的VPS？
> 
> banwagong

我debian9 运行这个命令都正常

**Comment by jinwyp** [comment]
> > > > 我用波仔的这个脚本debian9可以正常打开后台管理页面
> > > > https://www.v2rayssr.com/trojanpanel.html
> > > 
> > > 
> > > 我在谷歌云上 用官方脚本 source <(curl -sL https://git.io/trojan-install) 安装报错
> > > 你是哪家的VPS？
> > 
> > 
> > banwagong
> 
> 我debian9 运行这个命令都正常



我试过了 在banwagong 的全新的机器 Debian 9 x86_64   
用 source <(curl -sL https://git.io/trojan-install) 一样报错


正在下载管理程序v2.8.7版本...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   632  100   632    0     0   4195      0 --:--:-- --:--:-- --:--:--  4213
100 14.2M  100 14.2M    0     0   327k      0  0:00:44  0:00:44 --:--:--  275k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   384  100   384    0     0  12916      0 --:--:-- --:--:-- --:--:-- 13241
Created symlink /etc/systemd/system/multi-user.target.wants/trojan-web.service → /etc/systemd/system/trojan-web.service.
安装trojan管理程序成功!

运行命令trojan可进行trojan管理

本机未安装trojan, 正在自动安装...

Creating trojan install directory
Entering temp directory /tmp/tmp.iElZSSBJQX...
Downloading trojan 1.16.0...
######################################################################## 100.0%
Unpacking trojan 1.16.0...
Installing trojan 1.16.0 to /usr/bin/trojan/trojan...
Installing trojan server config to /usr/local/etc/trojan/config.json...
Installing trojan systemd service to /etc/systemd/system/trojan.service...
Reloading systemd daemon...
Deleting temp directory /tmp/tmp.iElZSSBJQX...
Done!
Created symlink /etc/systemd/system/multi-user.target.wants/trojan.service → /etc/systemd/system/trojan.service.

1.Let's Encrypt 证书

2.自定义证书路径

panic: Error while reading terminfo data: termbox: unsupported terminal

goroutine 1 [running]:
trojan/util.getChar(0xbe6062, 0x1d, 0x0, 0x0)
	/home/go/trojan/util/string.go:51 +0x216
trojan/util.LoopInput(0xbe6062, 0x1d, 0xac4060, 0xc000248a40, 0x1, 0x1)
	/home/go/trojan/util/string.go:79 +0x293
trojan/trojan.InstallTls()
	/home/go/trojan/trojan/install.go:71 +0xde
trojan/cmd.check()
	/home/go/trojan/cmd/root.go:34 +0xc2
trojan/cmd.mainMenu()
	/home/go/trojan/cmd/root.go:41 +0x34
trojan/cmd.glob..func6(0x1233fc0, 0x126a750, 0x0, 0x0)
	/home/go/trojan/cmd/root.go:16 +0x20
github.com/spf13/cobra.(*Command).execute(0x1233fc0, 0xc0000201d0, 0x0, 0x0, 0x1233fc0, 0xc0000201d0)
	/home/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x1233fc0, 0x443a4a, 0x11f29c0, 0xc000000180)
	/home/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/home/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
trojan/cmd.Execute()
	/home/go/trojan/cmd/root.go:23 +0x31
main.main()
	/home/go/trojan/main.go:6 +0x20
浏览器访问'https://域名'可在线trojan多用户管理

**Comment by FantasticSkyBaby** [comment]
好吧，我这一切都正常、没有报错

**Comment by jinwyp** [comment]
这个问题我试了一下 用 另外一台windows 的linux子系统的 ssh登录 运行脚本就没有问题,  而用我mac的终端登录VPS 运行脚本 就有问题 , 很奇怪的问题, 

你如果没问题 那么我的脚本也可以正常运行在debian和ubuntu上  选择29在选5 卸载后重新安装就可以了.

**Comment by FantasticSkyBaby** [comment]
> 这个问题我试了一下 用 另外一台 Windows 机器的 Subsystem for Linux（WSL子系统的Ubuntu) 的 ssh登录VPS, 运行脚本就没有问题, 而用我用 macbook pro 的终端(装了 oh my zsh ) 登录VPS 运行脚本 就有问题 , 很奇怪的问题,
> 
> 你如果没问题 那么我的脚本也可以正常运行在debian和ubuntu上 选择29在选5 卸载后重新安装就可以了.

好的，谢谢
