### ISSUE TITLE
系统没有安装 trojan, 退出卸载

### ISSUE THREAD

**Issue by hunao0221** [jinwyp/one_click_script#104]
1. 登录VPS后，选择 7 升级 trojan-go 到最新版本  -- **升级成功**
2. 选择 88 升级脚本， -- **升级成功**
3. 再次选择7 升级 trojan-go 到最新版本 -- **系统没有安装 trojan, 退出卸载**

**OS and Terminal:**  

- OS: [Centos]
- Version [7]
- Terminal :  [linux ssh] 
- VPS  [Google Cloud]

**To Reproduce** 复现方法  

1. 登录VPS后，选择 7 升级 trojan-go 到最新版本  -- **升级成功**
2. 选择 88 升级脚本， -- **升级成功**
3. 再次选择7 升级 trojan-go 到最新版本 -- **系统没有安装 trojan, 退出卸载**

**Comment by jinwyp** [comment]
已修复
