### ISSUE TITLE
Xray+Vmess+tls+ws 连接错误

### ISSUE THREAD

**Issue by iJayscn** [jinwyp/one_click_script#105]
**Describe the bug** A clear and concise description of what the bug is.
在提出问题前请先自行排除服务器端问题和升级到最新客户端，同时也请通过搜索确认是否有人提出过相同问题。

!!! 请务必提供安装的选择的第几项 !!!
!!! 请务必提供什么操作系统 和用的什么终端 !!!

1. 例如选择的第2项 安装trojan

**25，同时安装v2ray+trojan，支持CDN**

**Xay+vmess+tls+ws**

**OS and Terminal:**  系统环境 信息 请务必提供什么操作系统 和用的什么终端 ，还有VPS主机商

- OS: Windows
- Version 10
- Terminal :  xshell
- VPS  Virmatch Debian 10、Debian 11

**To Reproduce** 复现方法  

Log Info 日志信息： 请提供安装出错的信息

**客户端错误：**
app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://XXXX): 502 Bad Gateway > websocket: bad handshake] > common/retry: all retry attempts failed

**服务端错误：**
systemctl status xray.service
● xray.service - Xray
     Loaded: loaded (/lib/systemd/system/xray.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2022-01-05 11:57:22 CST; 7min ago
       Docs: https://www.v2fly.org/
    Process: 310 ExecStart=/root/v2ray/xray run -config /root/v2ray/config.json (code=exited, status=23)
   Main PID: 310 (code=exited, status=23)
        CPU: 122ms

Jan 05 11:57:22 B04 systemd[1]: Started Xray.
Jan 05 11:57:22 B04 xray[310]: Xray 1.5.2 (Xray, Penetrates Everything.) Custom (go1.17.5 linux/amd64)
Jan 05 11:57:22 B04 xray[310]: A unified platform for anti-censorship.
Jan 05 11:57:22 B04 xray[310]: 2022/01/05 11:57:22 [Info] infra/conf/serial: Reading config: /root/v2ray/config.json
Jan 05 11:57:22 B04 xray[310]: Failed to start: main: failed to load config files: [/root/v2ray/config.json] > infra/conf: invalid field rule > infra/conf: neither outboundTag nor balancerTag is specified in routing rule
Jan 05 11:57:22 B04 systemd[1]: xray.service: Main process exited, code=exited, status=23/n/a
Jan 05 11:57:22 B04 systemd[1]: xray.service: Failed with result 'exit-code'.

安装完成nginx 是否启动成功，域名的网站是否能正常打开，如果打不开说明nginx安装有问题，请给出nginx安装时输出日志

网站正常、traojan正常，端口 443

**Comment by jinwyp** [comment]
如果vmess 请在客户端设置  "alterId": 0 

自 2022 年 1 月 1 日起，服务器端将默认禁用对于 MD5 认证信息 的兼容。任何使用 MD5 认证信息的客户端将无法连接到禁用 VMess MD5 认证信息的服务器端。

https://www.v2fly.org/config/protocols/vmess.html

**Comment by iJayscn** [comment]
今天尝试最新脚本问题依旧，系统是新DD 的 debian 11

**Comment by jinwyp** [comment]
脚本经过大幅改动 增加了很多牛X功能 可以重新试试

**Comment by GTGraphics3** [comment]
仍然有问题，干净的debian10 下无法启动xray，使用xray ws tls 


● xray.service - Xray
   Loaded: loaded (/lib/systemd/system/xray.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2022-01-18 00:58:22 CST; 22s ago
     Docs: https://www.v2fly.org/
  Process: 11345 ExecStart=/root/v2ray/xray run -config /root/v2ray/config.json (code=exited, status=23)
 Main PID: 11345 (code=exited, status=23)

Jan 18 00:58:22 vmo3vp54.hostflyte.com systemd[1]: Started Xray.
Jan 18 00:58:22 vmo3vp54.hostflyte.com xray[11345]: Xray 1.5.2 (Xray, Penetrates Everything.) Custom (go1.17.5 linux/amd64)
Jan 18 00:58:22 vmo3vp54.hostflyte.com xray[11345]: A unified platform for anti-censorship.
Jan 18 00:58:22 vmo3vp54.hostflyte.com xray[11345]: 2022/01/18 00:58:22 [Info] infra/conf/serial: Reading config: /root/v2ray/config.json
Jan 18 00:58:22 vmo3vp54.hostflyte.com xray[11345]: Failed to start: main: failed to load config files: [/root/v2ray/config.json] > infra/conf/serial: failed to decode config: /root/v2ray/config.json > infra/conf
Jan 18 00:58:22 vmo3vp54.hostflyte.com systemd[1]: xray.service: Main process exited, code=exited, status=23/n/a
Jan 18 00:58:22 vmo3vp54.hostflyte.com systemd[1]: xray.service: Failed with result 'exit-code'.

**Comment by GTGraphics3** [comment]
找到完整的错误输出了

Failed to start: main: failed to load config files: [/root/v2ray/config.json] > infra/conf/serial: failed to decode config: /root/v2ray/config.json > infra/conf/serial: failed to read config file at line 180 char 1 > invalid character 'E' looking for beginning of object key string

![image](https://user-images.githubusercontent.com/44542198/149812027-41d121e2-c819-4d17-9ada-9db407253c27.png)

这第180行有什么问题呢？需要怎么改？

**Comment by jinwyp** [comment]
> 找到完整的错误输出了
> 
> Failed to start: main: failed to load config files: [/root/v2ray/config.json] > infra/conf/serial: failed to decode config: /root/v2ray/config.json > infra/conf/serial: failed to read config file at line 180 char 1 > invalid character 'E' looking for beginning of object key string
> 
> ![image](https://user-images.githubusercontent.com/44542198/149812027-41d121e2-c819-4d17-9ada-9db407253c27.png)
> 
> 这第180行有什么问题呢？需要怎么改？

你选的第几项安装的？ 中间还选择了什么？

**Comment by GTGraphics3** [comment]
> > 找到完整的错误输出了
> > Failed to start: main: failed to load config files: [/root/v2ray/config.json] > infra/conf/serial: failed to decode config: /root/v2ray/config.json > infra/conf/serial: failed to read config file at line 180 char 1 > invalid character 'E' looking for beginning of object key string
> > ![image](https://user-images.githubusercontent.com/44542198/149812027-41d121e2-c819-4d17-9ada-9db407253c27.png)
> > 这第180行有什么问题呢？需要怎么改？
> 
> 你选的第几项安装的？ 中间还选择了什么？

只要选择了vless，使用xray的任何选项都会出现这个问题….如果选择vmess安装v2ray则没有问题

**Comment by GTGraphics3** [comment]
比如说选择 _11. 安装 v2ray或xray 和 nginx ([Vmess/Vless]-[TCP/WS/gRPC/H2/QUIC]-TLS), 支持CDN, nginx 运行在443端口_ ， 选择xray，生成的xray配置文件会报错。之前选过的其他的选项生成的xray文件也会报错，不过可能不是这个180行的错误，我也遇到过跟楼主一样的报错Failed to start: main: failed to load config files: [/root/v2ray/config.json] > infra/conf: invalid field rule > infra/conf: neither outboundTag nor balancerTag is specified

**Comment by GTGraphics3** [comment]
我在另一台aws上重新试了试，debian 11 安装vless+xtls是没有问题的。不过其他两个debian 10 上的vps有问题

**Comment by jinwyp** [comment]
> 比如说选择 _11. 安装 v2ray或xray 和 nginx ([Vmess/Vless]-[TCP/WS/gRPC/H2/QUIC]-TLS), 支持CDN, nginx 运行在443端口_ ， 选择vless，xtlx，生成的xray配置文件会报错。之前选过的其他的选项生成的xray文件也会报错，不过可能不是这个180行的错误，我也遇到过跟楼主一样的报错Failed to start: main: failed to load config files: [/root/v2ray/config.json] > infra/conf: invalid field rule > infra/conf: neither outboundTag nor balancerTag is specified

已修复 请重新更新脚本安装,

**Comment by iJayscn** [comment]
2022/01/18 17:50:01 [Warning] [1564765627] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws://az.z7z8.buzz:443/0c70eef3): 404 Not Found > websocket: bad handshake] > common/retry: all retry attempts failed


安装  22  xray+vmess+ws ，未套CDN ，未选任何解锁 ， trojan 运行正常

**Comment by jinwyp** [comment]
> 

已修复  问题出在 选择22 还能自定义v2ray的端口导致nginx无法转发v2ray端口。

重新更新脚本  选88升级脚本  卸载安装即可。

安装完运行 systemctl status xray.service 看看xray 是否工作正常.

**Comment by jinwyp** [comment]
> 2022/01/18 17:50:01 [Warning] [1564765627] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws://az.z7z8.buzz:443/0c70eef3): 404 Not Found > websocket: bad handshake] > common/retry: all retry attempts failed
> 
> 安装 22 xray+vmess+ws ，未套CDN ，未选任何解锁 ， trojan 运行正常

已修复 问题出在 选择22 还能自定义v2ray的端口导致nginx无法转发v2ray端口。

重新更新脚本 选88升级脚本 卸载安装即可。

安装完运行 systemctl status xray.service 看看xray 是否工作正常.

**Comment by iJayscn** [comment]
> 

又试了两次，vless+ws+tls  和  vmess+ws+tls 直接装完是没办法连接

但是重启一下 就可以了

**Comment by jinwyp** [comment]
> 重启nginx 才能使用vmess问题已经修复

布置能不能修复 这是什么意思？

vmess 的订阅连接导入问题 稍后会修复，

**Comment by GTGraphics3** [comment]
实测是修复了，不过刚刚布置完后需要重启才能正常运作，问题不大

**Comment by iJayscn** [comment]
> > 重启nginx 才能使用vmess问题已经修复
> 
> 布置能不能修复 这是什么意思？
> 
> vmess 的订阅连接导入问题 稍后会修复，

不知能不能修复：

vmess 的订阅连接，没办法导入 v2rayN， trojan 和 vless 的正常

**Comment by jinwyp** [comment]
> > > 重启nginx 才能使用vmess问题已经修复
> > 
> > 
> > 布置能不能修复 这是什么意思？
> > vmess 的订阅连接导入问题 稍后会修复，
> 
> 不知能不能修复：
> 
> vmess 的订阅连接，没办法导入 v2rayN， trojan 和 vless 的正常

已修复 vmess 导入连接问题

**Comment by Eddieyyang** [comment]
> 如果vmess 请在客户端设置 "alterId": 0
> 
> 自 2022 年 1 月 1 日起，服务器端将默认禁用对于 MD5 认证信息 的兼容。任何使用 MD5 认证信息的客户端将无法连接到禁用 VMess MD5 认证信息的服务器端。
> 
> https://www.v2fly.org/config/protocols/vmess.html
> 
> VM 淘汰MD5 &强制AEAD 解决方案 https://www.blueskyxn.com/202201/5696.html

使用x-ui搭建Xray+Nginx+vmess+ws+tls+web的方法搭的节点，电脑V2ray能连接上，扫描导入手机V2rayNG连接不了，这是什么原因，大神知道吗？求告知！

**Comment by Eddieyyang** [comment]
换了也不行，奇怪了！

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Jin ***@***.***>
发送时间: Wednesday, October 12, 2022 12:02:59 AM
收件人: jinwyp/one_click_script ***@***.***>
抄送: Eddieyyang ***@***.***>; Comment ***@***.***>
主题: Re: [jinwyp/one_click_script] Xray+Vmess+tls+ws 连接错误 (Issue #105)


如果vmess 请在客户端设置 "alterId": 0
自 2022 年 1 月 1 日起，服务器端将默认禁用对于 MD5 认证信息 的兼容。任何使用 MD5 认证信息的客户端将无法连接到禁用 VMess MD5 认证信息的服务器端。
https://www.v2fly.org/config/protocols/vmess.html
VM 淘汰MD5 &强制AEAD 解决方案 https://www.blueskyxn.com/202201/5696.html

使用x-ui搭建Xray+Nginx+vmess+ws+tls+web的方法搭的节点，电脑V2ray能连接上，扫描导入手机V2rayNG连接不了，这是什么原因，大神知道吗？求告知！

特殊时期连不上很正常, 换IP 换VPS服务商

―
