### ISSUE TITLE
自动更新到了v2fly 5.01

### ISSUE THREAD

**Issue by gangmain** [jinwyp/one_click_script#106]
今天更新服务器端，通过26项更新了trojan-go和 v2fly 的CDN模式。 结果v2fly更新到了5.01版本服务不可用了，trojan-go正常。没看到降级选项，请问一下如何降级啊。
应该是5.01版本的问题。
502 Bad Gateway > websocket: bad handshake] > common/retry: all retry attempts failed

**Comment by Apurikotto** [comment]
我今天重装系统重新安装之后也出现了楼主同样的问题，v2ray根本没运行，检查nginx-error.log 报错 

> 2022/01/03 20:35:14 [error] 738#0: *82 connect() failed (111: Connection refused) while connecting to upstream, client: , server: , request: " HTTP/1.1", upstream: "", host: ""

，不知道是什么原因，选的是11，提前安装好了bbr plus。
![QQ截图20220103220515](https://user-images.githubusercontent.com/72537772/147933792-cc158f8c-c5bf-436d-833b-fbfb9e9927bd.jpg)

**Comment by googlespeed** [comment]
这错误折磨我一天了, 真个系统重装都不行
![image](https://user-images.githubusercontent.com/39025172/147955444-064a3ec4-8c4d-4afb-9810-d47d8c038109.png)

**Comment by iJayscn** [comment]
前天开始重装的，v2ray  就会提示 502 bad gateway ，但是trojan又正常

**Comment by jinwyp** [comment]
1 先检查 是不是 vmess AEAD 的问题
https://github.com/jinwyp/one_click_script/issues/105
如果vmess 请在客户端设置 "alterId": 0

自 2022 年 1 月 1 日起，服务器端将默认禁用对于 MD5 认证信息 的兼容。任何使用 MD5 认证信息的客户端将无法连接到禁用 VMess MD5 认证信息的服务器端。

https://www.v2fly.org/config/protocols/vmess.html

2  我已经把脚本 锁定v2ray 版本在4.44，   更新或重新安装都可以了

**Comment by Apurikotto** [comment]
还是不行，刚试了下
![IMG_20220104_103943](https://user-images.githubusercontent.com/72537772/148002517-91632e85-f863-4b72-b5a7-94e50a674445.jpg)

**Comment by gangmain** [comment]
> 1 先检查 是不是 vmess AEAD 的问题 #105 如果vmess 请在客户端设置 "alterId": 0
> 
> 自 2022 年 1 月 1 日起，服务器端将默认禁用对于 MD5 认证信息 的兼容。任何使用 MD5 认证信息的客户端将无法连接到禁用 VMess MD5 认证信息的服务器端。
> 
> https://www.v2fly.org/config/protocols/vmess.html
> 
> 2 我已经把脚本 锁定v2ray 版本在4.44， 更新或重新安装都可以了


刚更新了一下新的脚本，重新运行了一遍  V2ray版本自动更新部署了4.41.1。现在问题解决了，正常使用用。谢谢！

**Comment by googlespeed** [comment]
![image](https://user-images.githubusercontent.com/39025172/148005393-e50fa0fa-6122-4b06-9ebf-14ba21d06f1b.png)
![image](https://user-images.githubusercontent.com/39025172/148005398-f6a7c8fe-af09-482f-8673-dc668c2ed01e.png)
重装4.4还这样, 我这个是怎么了

**Comment by Apurikotto** [comment]
我刚才也这样，卸载v2ray重装才解决的。

**Comment by googlespeed** [comment]
> 1 先检查 是不是 vmess AEAD 的问题 #105 如果vmess 请在客户端设置 "alterId": 0
> 
> 自 2022 年 1 月 1 日起，服务器端将默认禁用对于 MD5 认证信息 的兼容。任何使用 MD5 认证信息的客户端将无法连接到禁用 VMess MD5 认证信息的服务器端。
> 
> https://www.v2fly.org/config/protocols/vmess.html
> 
> 2 我已经把脚本 锁定v2ray 版本在4.44， 更新或重新安装都可以了

![image](https://user-images.githubusercontent.com/39025172/148007647-4020afec-c44f-441b-9ec0-8d7cbc5a6e23.png)
卸载重装错误 23, 我这是漏了哪一步? v2ray服务器一直无法启动
![image](https://user-images.githubusercontent.com/39025172/148007698-057c3ead-3877-491b-aada-2791f44de0a3.png)

**Comment by googlespeed** [comment]
> 卸载重装错误 23, 我这是漏了哪一步? v2ray服务器一直无法启动



> 我刚才也这样，卸载v2ray重装才解决的。
你的安装流程是怎样的
卸载重装错误 23, 我这是漏了哪一步? v2ray服务器一直无法启动

**Comment by jinwyp** [comment]
> 

这个提示是 /root/v2ray/config 配置文件里面有错误 

你是选的第几项安装的 ? 安装过程中选的解锁 Netflix是 第几项

**Comment by iJayscn** [comment]
> > 
> 
> 这个提示是 /root/v2ray/config 配置文件里面有错误
> 
> 你是选的第几项安装的 ? 安装过程中选的解锁 Netflix是 第几项

xray+vmess+tls+ws 这个错误是?

systemctl status xray.service
● xray.service - Xray
   Loaded: loaded (/lib/systemd/system/xray.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2022-01-04 13:19:26 HKT; 6s ago
     Docs: https://www.v2fly.org/
  Process: 8264 ExecStart=/root/v2ray/xray run -config /root/v2ray/config.json (code=exited, status=23)
 Main PID: 8264 (code=exited, status=23)

Jan 04 13:19:26 dogg4-cat systemd[1]: Started Xray.
Jan 04 13:19:26 dogg4-cat xray[8264]: Xray 1.5.2 (Xray, Penetrates Everything.) Custom (go1.17.5 linux/amd64)
Jan 04 13:19:26 dogg4-cat xray[8264]: A unified platform for anti-censorship.
Jan 04 13:19:26 dogg4-cat xray[8264]: 2022/01/04 13:19:26 [Info] infra/conf/serial: Reading config: /root/v2ray/config.json
Jan 04 13:19:26 dogg4-cat xray[8264]: Failed to start: main: failed to load config files: [/root/v2ray/config.json] > infra/conf: invalid field rule > infra/conf: neither outboundTag nor balancerTag is specified in routing rule
Jan 04 13:19:26 dogg4-cat systemd[1]: xray.service: Main process exited, code=exited, status=23/n/a
Jan 04 13:19:26 dogg4-cat systemd[1]: xray.service: Failed with result 'exit-code'.

**Comment by jinwyp** [comment]
> > > 
> > 
> > 
> > 这个提示是 /root/v2ray/config 配置文件里面有错误
> > 你是选的第几项安装的 ? 安装过程中选的解锁 Netflix是 第几项
> > 25.同时安装v2ray+trojan，CDN。
> 
> xray+vmess+tls+ws 这个错误是?
> 
> systemctl status xray.service ● xray.service - Xray Loaded: loaded (/lib/systemd/system/xray.service; disabled; vendor preset: enabled) Active: failed (Result: exit-code) since Tue 2022-01-04 13:19:26 HKT; 6s ago Docs: https://www.v2fly.org/ Process: 8264 ExecStart=/root/v2ray/xray run -config /root/v2ray/config.json (code=exited, status=23) Main PID: 8264 (code=exited, status=23)
> 
> Jan 04 13:19:26 dogg4-cat systemd[1]: Started Xray. Jan 04 13:19:26 dogg4-cat xray[8264]: Xray 1.5.2 (Xray, Penetrates Everything.) Custom (go1.17.5 linux/amd64) Jan 04 13:19:26 dogg4-cat xray[8264]: A unified platform for anti-censorship. Jan 04 13:19:26 dogg4-cat xray[8264]: 2022/01/04 13:19:26 [Info] infra/conf/serial: Reading config: /root/v2ray/config.json Jan 04 13:19:26 dogg4-cat xray[8264]: Failed to start: main: failed to load config files: [/root/v2ray/config.json] > infra/conf: invalid field rule > infra/conf: neither outboundTag nor balancerTag is specified in routing rule Jan 04 13:19:26 dogg4-cat systemd[1]: xray.service: Main process exited, code=exited, status=23/n/a Jan 04 13:19:26 dogg4-cat systemd[1]: xray.service: Failed with result 'exit-code'.

选第几项安装的?

**Comment by googlespeed** [comment]
> > 
> 
> 这个提示是 /root/v2ray/config 配置文件里面有错误
> 
> 你是选的第几项安装的 ? 安装过程中选的解锁 Netflix是 第几项

解锁选项 一路回车下来的 都是默认值

**Comment by googlespeed** [comment]
> > > 
> > 
> > 
> > 这个提示是 /root/v2ray/config 配置文件里面有错误
> > 你是选的第几项安装的 ? 安装过程中选的解锁 Netflix是 第几项
> 
> 解锁选项 一路回车下来的 都是默认值



> > > 
> > 
> > 
> > 这个提示是 /root/v2ray/config 配置文件里面有错误
> > 你是选的第几项安装的 ? 安装过程中选的解锁 Netflix是 第几项
> 
> 解锁选项 一路回车下来的 都是默认值

选了11 自定义path和uuis

**Comment by googlespeed** [comment]
![image](https://user-images.githubusercontent.com/39025172/148013540-9d01e974-fc39-4d2b-ac8d-fd021f6aed3a.png)

**Comment by googlespeed** [comment]
> /root/v2ray/config 配置文件

给你的Email发了配置文件

**Comment by iJayscn** [comment]
> > > > 
> > > 
> > > 
> > > 这个提示是 /root/v2ray/config 配置文件里面有错误
> > > 你是选的第几项安装的 ? 安装过程中选的解锁 Netflix是 第几项
> > > 25.同时安装v2ray+trojan，CDN。
> > 
> > 
> > xray+vmess+tls+ws 这个错误是?
> > systemctl status xray.service ● xray.service - Xray Loaded: loaded (/lib/systemd/system/xray.service; disabled; vendor preset: enabled) Active: failed (Result: exit-code) since Tue 2022-01-04 13:19:26 HKT; 6s ago Docs: https://www.v2fly.org/ Process: 8264 ExecStart=/root/v2ray/xray run -config /root/v2ray/config.json (code=exited, status=23) Main PID: 8264 (code=exited, status=23)
> > Jan 04 13:19:26 dogg4-cat systemd[1]: Started Xray. Jan 04 13:19:26 dogg4-cat xray[8264]: Xray 1.5.2 (Xray, Penetrates Everything.) Custom (go1.17.5 linux/amd64) Jan 04 13:19:26 dogg4-cat xray[8264]: A unified platform for anti-censorship. Jan 04 13:19:26 dogg4-cat xray[8264]: 2022/01/04 13:19:26 [Info] infra/conf/serial: Reading config: /root/v2ray/config.json Jan 04 13:19:26 dogg4-cat xray[8264]: Failed to start: main: failed to load config files: [/root/v2ray/config.json] > infra/conf: invalid field rule > infra/conf: neither outboundTag nor balancerTag is specified in routing rule Jan 04 13:19:26 dogg4-cat systemd[1]: xray.service: Main process exited, code=exited, status=23/n/a Jan 04 13:19:26 dogg4-cat systemd[1]: xray.service: Failed with result 'exit-code'.
> 
> 选第几项安装的?

25项

**Comment by jinwyp** [comment]
> > /root/v2ray/config 配置文件
> 
> 给你的Email发了配置文件

已修复这个问题 更新脚本 卸载后 重新安装
