### ISSUE TITLE
没有找到安装Trojan-go+V2ray+Nginx+WS+TSL+CDN的方法

### ISSUE THREAD

**Issue by dqyhonghu** [jinwyp/one_click_script#11]
没有找到安装Trojan-go+V2ray+Nginx+WS+TSL+CDN的方法，是我太笨了吗？

**Comment by jinwyp** [comment]
trojan-go 可以支持 Websocket + CDN 
v2ray 可以支持 Websocket + CDN  

你想要的是哪种？  是trojan-go 和 v2ray 同时安装后 
1 trojan-go 不支持 CDN + v2ray 支持 CDN 
2 trojan-go 支持CDN + v2ray 不支持 CDN
3 trojan-go 支持CDN  同时 v2rya也支持CDN  

实际上 如果要支持 CDN,  建议单独只安装 trojan-go（选8） 或 v2ray （选12）  

目前脚本只提供了 同时安装后 trojan-go 和 v2ray   都不支持CDN  （选18） （实际这个v2ray是支持CDN,你可以试下）


在v2ray 时代， tls是由 nginx web服务器提供的， v2ray在nginx 后面，  就是 nginx -》 v2ray。
在trojan出现后  trojan接管了443  跑在了 nginx前面   就是 trojan - nginx 这样就很安全了  
然后trojan和 v2ray 整合 就是 trojan -》nginx -》v2ray。

当v2ray 模仿trojan 出了 vless 后  也可以跑在 nginx 前面接管443了  就是 v2ray -》nginx  

那么 vless的v2ray 就无法和 trojan 共存了，  

而且还可以 vless 的 v2ray -》 nginx -》 vmess 的v2ray 

总结 你明白了？  你想要什么？  

建议自用只装一个trojan 比较好，如果主机IP被封了可以 套CDN，否则CDN感觉更慢

**Comment by dqyhonghu** [comment]
我希望实现第3种功能，如果实在不行，就放弃了。谢谢回复！

**Comment by dqyhonghu** [comment]
选12安装，Nginx无法启动，错误信息：nginx: [warn] invalid value "TLSv1.3" in /etc/nginx/nginx.conf:29

**Comment by dqyhonghu** [comment]
系统Debian 9 64 bit

**Comment by jinwyp** [comment]
已经加好了第三种 选19  你可以测试一下 

nginx的问题 是默认源的nginx 不支持tls1.3  因为我是直接用源安装的，否则要编译安装nginx 支持tls1.3 时间太长， 不搞了   

你只能换系统用Ubuntu 20 或 新一点的源。或编辑nginx 把tls1.3 指令删除  
nginx 在1.13以上就支持tls 1.3  

我暂时把tls1.3去掉了， 你直接更新就能用了 支持tls1.2

**Comment by malikshi** [comment]
install the latest Nginx through sourcelist its much better set to mainline released version.

**Comment by jinwyp** [comment]
已增加xray
