### ISSUE TITLE
v2ray.service无法启动

### ISSUE THREAD

**Issue by xifeng0** [jinwyp/one_click_script#114]
![image](https://user-images.githubusercontent.com/76558682/150698995-d3c09c7c-4601-42a2-af9e-3351df259df9.png)
 系统信息: Ubuntu, ubuntu, 20.04.2, 20.04, focal, amd CPU amd64, bash, apt-get
VPS是甲骨文的。今天重装V2RAY，使用的11安装。出现此错误。网页可以正常打开，v2ray无法正常启动。

**Comment by jinwyp** [comment]
试了一下 选择11 其他都默认直接回车 安装是正常的， 建议先升级脚本 然后卸载之前安装的v2ray或用重新系统试试  

或者使用 systemctl status v2ray 看看报错是什么原因， 图上的意思就是好像还有其他v2ray在启动

在用 systemctl restart v2ray 重启v2ray

配置文件在 /root/v2ray/config.json

**Comment by xifeng0** [comment]
确认是脚本问题，未更新最新版脚本。谢谢！

> 试了一下 选择11 其他都默认直接回车 安装是正常的， 建议先升级脚本 然后卸载之前安装的v2ray或用重新系统试试
> 
> 或者使用 systemctl status v2ray 看看报错是什么原因， 图上的意思就是好像还有其他v2ray在启动
> 
> 在用 systemctl restart v2ray 重启v2ray
> 
> 配置文件在 /root/v2ray/config.json
