### ISSUE TITLE
Debian11的日志信息，请看一下。

### ISSUE THREAD

**Issue by freelight** [jinwyp/one_click_script#115]
Debian10和Debian11 都出现同样的错误信息

vps系统环境  OS: [Debian 11 x64 (bullseye)]

选择安装第12项 ，安装v2ray-vmess， 传输协议: websocket,其他安装选项都是默认，
，没有安装nginx，vps系统时间已设定北京时间

VPS主机商：vultr

Terminal : MobaXterm

客户端：windows-v2rayN-v4.29
 
Log Info 日志信息： 

[Warning] failed to handler mux client connection > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (ws://149.28.xxx.xx:39808/bc12dd80):  > dial tcp 149.28.xxx.xx:39808: i/o timeout] > common/retry: all retry attempts failed

**Comment by jinwyp** [comment]
没更新脚本把? 

systemctl status v2ray 看看什么错误
