### ISSUE TITLE
升级脚本后无法访问网站

### ISSUE THREAD

**Issue by eternallyjie** [jinwyp/one_click_script#116]
**Describe the bug** A clear and concise description of what the bug is.
在升级脚本后，现在无法使用v2ray或者trojan访问网站。但是域名伪装网站可以打开。

!!! 请务必提供安装的选择的第几项 !!!
!!! 请务必提供什么操作系统 和用的什么终端 !!!

选择22项重现安装的

**OS and Terminal:**  系统环境 信息 请务必提供什么操作系统 和用的什么终端 ，还有VPS主机商

- OS: Debian 10，Debian 11，Ubuntu 20.04
- Version 
- Terminal :  Mac的teminal
- VPS  vultr

**To Reproduce** 复现方法  
升级脚本后，选择22项重新安装之后无法访问网站。但是域名伪装网站可以打开。

**Comment by jinwyp** [comment]
要先卸载原来的才可以安装啊. 先卸载之前的v2ray和trojan

**Comment by eternallyjie** [comment]
> 要先卸载原来的才可以安装啊. 先卸载之前的v2ray和trojan

我卸载过的，我都把vps系统还原重装了。还是一样的问题。

**Comment by jinwyp** [comment]
> > 要先卸载原来的才可以安装啊. 先卸载之前的v2ray和trojan
> 
> 我卸载过的，我都把vps系统还原重装了。还是一样的问题。

什么系统 debian10 吗?

**Comment by eternallyjie** [comment]
> > > 要先卸载原来的才可以安装啊. 先卸载之前的v2ray和trojan
> > 
> > 
> > 我卸载过的，我都把vps系统还原重装了。还是一样的问题。
> 
> 什么系统 debian10 吗?

是的，Centos9，Debian10、11，Ubuntu20.04都试了，都一样的问题。而且Ubuntu更换内核5.10重启后，ssh连不上，也有时候是在启用bbr，优化网络重启后，ssh连不上。

**Comment by eternallyjie** [comment]
> > 
> 
> 这个问题修复了

我刚才在 Ubuntu 20.04 上安装，选择66安装bbrplus内核后重启vps，ssh就无法连接vps了。

然后在 Debian 11 上安装了。Xray 和 Trojan-go 都是运行正常的，代理网站也能打开，443端口也是正常能 ping 通的。但是使用客户端还是无法访问google等网站。

安装步骤：
1、选择34，设置时间
2、选择31，安装软件
3、选择1，再选择66安装bbrplus内核
4、选择1，再选择3启用bbrplus加速
5、选择1，再选择11
6、选择1，再选择12
7、选择22安装
结束

<img width="776" alt="image" src="https://user-images.githubusercontent.com/30895476/153551549-0b42e8c6-3760-4765-993b-45115c259ac4.png">

**Comment by jinwyp** [comment]
> > > 
> > 
> > 
> > 这个问题修复了
> 
> 我刚才在 Ubuntu 20.04 上安装，选择66安装bbrplus内核后重启vps，ssh就无法连接vps了。
> 
> 然后在 Debian 11 上安装了。Xray 和 Trojan-go 都是运行正常的，代理网站也能打开，443端口也是正常能 ping 通的。但是使用客户端还是无法访问google等网站。
> 
> 安装步骤： 1、选择34，设置时间 2、选择31，安装软件 3、选择1，再选择66安装bbrplus内核 4、选择1，再选择3启用bbrplus加速 5、选择1，再选择11 6、选择1，再选择12 7、选择22安装 结束
> 
> <img alt="image" width="776" src="https://user-images.githubusercontent.com/30895476/153551549-0b42e8c6-3760-4765-993b-45115c259ac4.png">

1 图上已经正确运行 连不上是客户端设置问题吧 软件要升级到最新版.   trojan-go 和 v2ray的websocket 端口都是443 
2 选择1，再选择11 和 选择12 只能装一个 不建议同时装.
