### ISSUE TITLE
一键脚本出错这是怎么整呢 谢谢了

### ISSUE THREAD

**Issue by yao52069** [jinwyp/one_click_script#118]
root@a2:/root # curl -O https://raw.githubusercontent.com/jinwyp/one_click_script/master/trojan_v2ray_install.sh && chmod +x ./trojan_v2ray_install.sh && ./trojan_v2ray_install.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  249k  100  249k    0     0  1850k      0 --:--:-- --:--:-- --:--:-- 1865k
./trojan_v2ray_install.sh: line 1411: syntax error near unexpected token `fi'
./trojan_v2ray_install.sh: line 1411: `    fi'

**Comment by jinwyp** [comment]
改好了
