### ISSUE TITLE
无法执行安装脚本

### ISSUE THREAD

**Issue by weiidii** [jinwyp/one_click_script#119]
[root@ip-123.123.123.123 centos]# bash trojan_v2ray_install.sh 
trojan_v2ray_install.sh: line 1411: syntax error near unexpected token `fi'
trojan_v2ray_install.sh: line 1411: `    fi'

昨天还好的，更新脚本后，无法进入脚本
如上

**Comment by xifeng0** [comment]
是的，脚本出现了问题。无法安装

**Comment by yao52069** [comment]
是的安装不了

**Comment by lonlylion** [comment]
等待大佬更新

**Comment by jinwyp** [comment]
改好了

**Comment by weiidii** [comment]
> 

多谢！
