### ISSUE TITLE
关于网络配置优化中的 net.ipv4.ip_forward 设置

### ISSUE THREAD

**Issue by layou233** [jinwyp/one_click_script#121]
https://github.com/jinwyp/one_click_script/blob/832a697f6c79b4900d788790b2040eb5a35b047a/install_kernel.sh#L781
这个设置具有副作用，详见 https://github.com/XTLS/Xray-core/discussions/59  

> 实际测试验证,无论ipv4还是ipv6的转发只要开启一项,速度都会被拉垮,且splice可能下降更低
测试环境中,splice降低到约比direct略低一点,(2600降低到850,此时direct900)
测试环境中,direct也降低性能(1300降低至900)

此文指出此设置会影响Xray工作效率，我自己经过尝试也是如此，但是在脚本的优化网络配置的部分中是将此选项打开。  
对于仅开梯子的用户来说，ip_forward是多余的，只会拉跨速度，是否应该给一个询问，让用户自己选择是否开启这个？

**Comment by jinwyp** [comment]
1 这是脚本给服务器用的不是给 客户端路由器用的. linux 服务器转发是使用kernel 功能, 新版内核性能x86性能影响不大
2 该功能是用来给防火墙, 或多网卡 或NAT路由 配合时需要开启, 我已经修改去掉了这个转发优化, 保持原设置.  但如果装wireguard 虚拟网卡就需要开启.

**Comment by layou233** [comment]
感谢，我将关闭这个议题
