### ISSUE TITLE
希望添加对youtube提供解锁

### ISSUE THREAD

**Issue by linger040831** [jinwyp/one_click_script#123]
有些ip被谷歌识别成中国导致YouTubepremium用不了，现在的脚本有奈菲之类的优先ipv6解锁，希望对youtube也能加上优先ipv6，
谢谢！

**Comment by jinwyp** [comment]
> 

脚本已经了有了啊

用脚本安装 v2ray里面就可以选择 解锁任意流媒体

请选择要解锁的流媒体网站:

1. 不解锁"
2. 解锁 Netflix 限制
3.. 解锁 Youtube 和 Youtube Premium
4. 解锁 Pornhub, 解决视频变成玉米无法观看问题
5. 同时解锁 Netflix 和 Pornhub 限制
6. 同时解锁 Netflix, Youtube 和 Pornhub 限制
7. 同时解锁 Netflix, Hulu, HBO, Disney 和 Pornhub 限制
8. 同时解锁 Netflix, Hulu, HBO, Disney, Youtube 和 Pornhub 限制
9. 解锁 全部流媒体 包括 Netflix, Youtube, Hulu, HBO, Disney, BBC, Fox, niconico, dmm, Pornhub

**Comment by jinwyp** [comment]
> 谢谢回答，我还没用过vmess🤣一直用的trojan，请问可以在trojan的安装过程中选择要不要解锁流媒体吗？

trojan目前没有提供 类似v2ray的路由功能 所以无法针对特定网站分流走ipv6

**Comment by jinwyp** [comment]
> 好的👌谢谢回答，我去试试用vmess

vmess和vless都可以， 

如果让trojan支持分流 可以手动使用 iptable + dnsmasq  来设置规则 分流  具体比较麻烦
