### ISSUE TITLE
CF 开启CND就连不上

### ISSUE THREAD

**Issue by llity** [jinwyp/one_click_script#126]
Centos 7下面安装3或者23的Trojan + ws支持CDN，在CF 里面开启CDN代理，SSL选择完全，一会儿就连不上服务器。

求解，不套CDN就正常。

**Comment by jinwyp** [comment]
选择3 安装trojan-go + ws  开启CF 的CDN 后 先看看网站是否能打开, 最近CF很慢 使用ws连不上也是可能的.

可以ping 域名看看IP是多少 延迟高不高, 延迟高 用ws打不开, 可以试试优选IP 

或者 选择11 安装v2ray 看看到底 是CF的CDN连不上还是VPS的问题.  CF的IP有时候被封的很厉害
