### ISSUE TITLE
Error Message : invalid domain in running acme

### ISSUE THREAD

**Issue by bedweather** [jinwyp/one_click_script#127]
**Describe the bug** A clear and concise description of what the bug is.
在提出问题前请先自行排除服务器端问题和升级到最新客户端，同时也请通过搜索确认是否有人提出过相同问题。

!!! 请务必提供安装的选择的第几项 !!!
!!! 请务必提供什么操作系统 和用的什么终端 !!!

### 1.  选择 以下的安装模式
`2.Install trojan/trojan-go with nginx, not support CDN acceleration, trojan/trojan-go running at 443 port serve TLS`

**OS and Terminal:**  系统环境 信息 请务必提供什么操作系统 和用的什么终端 ，还有VPS主机商
## 系统信息
- OS: [Linux version Ubuntu SMP]
- Version [18.04]
- Terminal :  Teraterm
- VPS  [Azure]

**To Reproduce** 复现方法  
### 1. 选择 第一次申请证书
```
 是否申???? 默?直接回??申???, 如第二次安装或已有?? 可以?否
 如果已?有SSL??文件 ?放到下面路径
 meta-xyz.ml 域名??内容文件路径 /root/website/cert/fullchain.cer
 meta-xyz.ml 域名??私?文件路径 /root/website/cert/private.key
是否申???? 默?直接回??自?申???,??入[Y/n]:
```

输入：Y

### 2.两次尝试不同的证书提供商
 1 Letsencrypt.org， 2 BuyPass.com

```
 ?????提供商, 默?通? Letsencrypt.org 来申???
 如果??申?失?, 例如一天内通? Letsencrypt.org 申?次数?多, 可? BuyPass.com 或 ZeroSSL.com 来申?.
 1 Letsencrypt.org
 2 BuyPass.com
 3 ZeroSSL.com
```
分别输入 第一次：1， 第二次：2

### 3.选择http证书生成方式
```
 ??? acme.sh 脚本申?SSL??方式: 1 http方式, 2 dns方式
 默?直接回?? http 申?方式, ?否?? dns 方式
```

输入：1 http

### 4. 选择DNS提供商
```
??? DNS provider DNS 提供商: 1 CloudFlare, 2 AliYun,  3 DNSPod(Tencent), 4 GoDaddy
注意 CloudFlare ??某些免?域名例如 .tk .cf 等  不再支持使用API 申?DNS??

```
使用API token验证，下面是token测试结果
```
curl -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \
>      -H "Authorization: Bearer 38DIFbKChD-NAmmxRNRyV8GztZ36eBkeyvY22x7g" \
>      -H "Content-Type:application/json"
{"result":{"id":"XXXX","status":"active","expires_on":"2032-03-05T23:59:59Z"},"success":true,"errors":[],"messages":[{"code":10000,"message":"This API Token is valid and active","type":null}]}

```
## 错误信息 Summary

···
[Sat Mar  5 03:28:02 UTC 2022] ret='0'
[Sat Mar  5 03:28:02 UTC 2022] h='meta-xyz.ml'
[Sat Mar  5 03:28:02 UTC 2022] zones?name=xxx-xxx.ml
[Sat Mar  5 03:28:02 UTC 2022] GET
[Sat Mar  5 03:28:02 UTC 2022] url='https://api.cloudflare.com/client/v4/zones?name=xxx-xxx.ml'
[Sat Mar  5 03:28:02 UTC 2022] timeout=
[Sat Mar  5 03:28:02 UTC 2022] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g '
[Sat Mar  5 03:28:02 UTC 2022] ret='0'
[Sat Mar  5 03:28:02 UTC 2022] h='ml'
[Sat Mar  5 03:28:02 UTC 2022] zones?name=ml
[Sat Mar  5 03:28:02 UTC 2022] GET
[Sat Mar  5 03:28:02 UTC 2022] url='https://api.cloudflare.com/client/v4/zones?name=ml'
[Sat Mar  5 03:28:02 UTC 2022] timeout=
[Sat Mar  5 03:28:02 UTC 2022] _CURL='curl --silent --dump-header /root/.acme.sh/http.header  -L  -g '
[Sat Mar  5 03:28:02 UTC 2022] ret='0'
[Sat Mar  5 03:28:02 UTC 2022] h
**[Sat Mar  5 03:28:02 UTC 2022] invalid domain**
[Sat Mar  5 03:28:02 UTC 2022] Error add txt for domain:_acme-challenge.xxx-xxx.ml
[Sat Mar  5 03:28:02 UTC 2022] _on_issue_err
[Sat Mar  5 03:28:02 UTC 2022] Please add '--debug' or '--log' to check more details.
[Sat Mar  5 03:28:02 UTC 2022] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
···

Log Info 日志信息： 请提供安装出错的信息
例如xxx
[error_letsencrypt_1.txt](https://github.com/jinwyp/one_click_script/files/8189934/error_letsencrypt_1.txt)
[error_buypass_2.txt](https://github.com/jinwyp/one_click_script/files/8189935/error_buypass_2.txt)

安装完成nginx 是否启动成功，域名的网站是否能正常打开，如果打不开说明nginx安装有问题，请给出nginx安装时输出日志

Port 80 : show Apache2 Ubuntu Default Page
Port 443:  can not conenct

**Comment by jinwyp** [comment]
域名要输入www.meta-xyz.ml 这种二级域名 并且域名已经指向该VPS

**Comment by bedweather** [comment]
> 域名要输入www.meta-xyz.ml 这种二级域名 并且域名已经指向该VPS
Thanks， It's  worked.
