### ISSUE TITLE
如何修改v2ray路径

### ISSUE THREAD

**Issue by hrddfs** [jinwyp/one_click_script#128]
如何修改v2ray路径

**Comment by jinwyp** [comment]
1 默认在/root/v2ray下载 , 把文件复制到你自定义的路径
2 修改systemmd 配置文件 可以运行 systemctl status v2ray 看一下这个配置路径在哪

centos 在 /usr/lib/systemd/system/v2ray.service  编辑这个文件 把里面的/root/v2ray的路径 都改为你的自定义路径

在运行 以下三个命令
```
systemctl daemon-reload
systemctl restart v2ray.service
systemctl enable v2ray.service
```

**Comment by hrddfs** [comment]
知道了，谢谢回复！
