### ISSUE TITLE
求问如何关闭伪装站的TLSv1.3，想套CloudFront CDN，他们不支持1.3

### ISSUE THREAD

**Issue by LIHAOCHI** [jinwyp/one_click_script#129]
RT

**Comment by jinwyp** [comment]
CloudFront  支持TLS 1.3 啊 https://aws.amazon.com/cn/about-aws/whats-new/2020/09/cloudfront-tlsv1-3-support/

在nginx 配置中 /etc/nginx/nginx.conf  去掉tls1.3

ssl_protocols         TLSv1.2 TLSv1.3;  
改为
ssl_protocols         TLSv1.2

;

**Comment by LIHAOCHI** [comment]
谢谢！！
