### ISSUE TITLE
可以在码云上布署你们上传你的代码吗

### ISSUE THREAD

**Issue by vipwuping** [jinwyp/one_click_script#13]
一健脚本自动安装，如果是国内VPS 安装的话，根本没办法。我想在测试的国内VPS上装。速度卡的不行啊

**Comment by jinwyp** [comment]
不符合国家法律，而且VPS本身无法访问外网的话，部署了也没有用啊

**Comment by vipwuping** [comment]
我试着把代码全部打包上传到服务器上面  ，运行脚本后 还是从远程下载安装包，明明已经有安装包了还是远程下载
因为一健安装代码就是远程执行的，你可以把全部代码打包完，再写一个本地执行的脚本吧，这样直接把完整安装包上传到服务器上面直接执行安装，这样很方便。不用远程下载了

**Comment by jinwyp** [comment]
> 我试着把代码全部打包上传到服务器上面 ，运行脚本后 还是从远程下载安装包，明明已经有安装包了还是远程下载
> 因为一健安装代码就是远程执行的，你可以把全部代码打包完，再写一个本地执行的脚本吧，这样直接把完整安装包上传到服务器上面直接执行安装，这样很方便。不用远程下载了

自己把脚本里面的几个zip文件的下载地址替换一下，然后上传到服务器就可以啊

**Comment by vipwuping** [comment]
我试着把代码的下载地址改了然后再运行  结果不行直接报错了
![9999](https://user-images.githubusercontent.com/40034996/93047857-06eadc00-f690-11ea-92cc-a1a0eb17259f.png)

**Comment by jinwyp** [comment]
> 我试着把代码的下载地址改了然后再运行 结果不行直接报错了
> ![9999](https://user-images.githubusercontent.com/40034996/93047857-06eadc00-f690-11ea-92cc-a1a0eb17259f.png)
> 下载的地址改成码云的地址不行，怎么把下载地址改成服务器上的路径地址，下载地址改成服务器本地路径的格式是，能写个样式吗
> 可以写一个本地服务器安装的脚本，然后直接把安装包上传到服务器上面就可以安装了

脚本里面有几种下载，
一种就是代码库的download目录里面的文件，这些文件你只要上传到vps /root/temp 里面就可以了， 
还有一些是下载程序可执行代码 这些都是从作者的github直接下载最新版本，还有是docker hub上的， 我说的只是改第一种，其他的下载还是从国外的机器下载的， vps访问这些国外网站慢那就没办法了. 

还有你的提示错误信息应该是改错语法了，建议用vscode或webstorm 编辑器改，否则容易出语法问题

**Comment by vipwuping** [comment]
https://github.com/acmesh-official/acme.sh/archive/master.tar.gz  这个文件在脚本里面找不到，需要在哪里更改
另外证书申请可否自定义一下自有证书，如果域名申请多次证书后就不能再申请了，直接就停止下一步的安装了,做一下更改动手工指定证书或者证书申请失败了，由用户手工上传证书到服务器，然后再继续   证书申请改成 ECC证书 这种证书体积小运算更快

一种就是代码库的download目录里面的文件，这些文件你只要上传到vps /root/temp 里面就可以了 这样不行还是会自动复盖下载的

**Comment by jinwyp** [comment]
> ![8888](https://user-images.githubusercontent.com/40034996/93113700-1b5cc200-f6ec-11ea-8050-cf344c4f7456.png)
> https://github.com/acmesh-official/acme.sh/archive/master.tar.gz 这个文件在脚本里面找不到，需要在哪里更改
> 另外证书申请可否自定义一下自有证书，如果域名申请多次证书后就不能再申请了，直接就停止下一步的安装了,做一下更改动手工指定证书或者证书申请失败了，由用户手工上传证书到服务器，然后再继续 证书申请改成 ECC证书 这种证书体积小运算更快
> 
> 一种就是代码库的download目录里面的文件，这些文件你只要上传到vps /root/temp 里面就可以了 这样不行还是会自动复盖下载的

1 域名换个二级域名就可以继续申请，
2 下载zip的问题 你要把下载的代码加个#号 注释掉 或者 改下 下载地址换成你的下载地址 就可以了。
 

https://github.com/acmesh-official/acme.sh/archive/master.tar.gz 这个文件不是我的里面的，因为我调用了acme.sh 的脚本申请证书, 是它里面的文件， 所以我也不清楚怎么下载的， 具体要看acme.sh的脚本了
