### ISSUE TITLE
Trojan-Go + Websocket 套CloudFront CDN出现502错误

### ISSUE THREAD

**Issue by LIHAOCHI** [jinwyp/one_click_script#130]
**1. 选择的第3项 安装Trojan-Go和Nginx
2. 正常安装
3. 配置CloudFront CDN，配置时参考了我自己之前使用Vless + WS + TLS套CDN的设置：源域填写绑到VPS的域名、转发所有标头、仅限https的查看器策略等等
4. 访问CloudFront分配的域名，出现502错误**

OS and Terminal:  系统环境 信息 请务必提供什么操作系统 和用的什么终端 ，还有VPS主机商

**- OS: Debian
- Version: 10
- Terminal: Termius Mac版
- VPS: AWS EC2**

**To Reproduce** 复现方法  

Log Info 日志信息： 请提供安装出错的信息

**Nginx错误日志：
2022/03/12 20:19:46 [error] 4761#4761: *5 open() "/root/website/html/js/bootstrap.bundle.min.js" failed (2: No such file or directory), client: 127.0.0.1, server: xxx.com, request: "GET /js/bootstrap.bundle.min.js HTTP/1.1", host: "xxx.com", referrer: "https://xxx.com/"
每次试图访问CloudFront分配域名都会出现一次类似的错误，只不过因为伪装网站是变动的，所以具体的路径会有差异，但总体来说都是同一类错误。

Trojan-Go Access日志：
[ERROR] 2022/03/12 20:36:37 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | sni mismatched: , expected: xxx.com**

安装完成nginx 是否启动成功，域名的网站是否能正常打开，如果打不开说明nginx安装有问题，请给出nginx安装时输出日志
安装完成nginx可以启动，伪装站也可以打开并自动变动。

**我在用同样的环境，也是用您的脚本搭Vless + WS + TLS套同样的CloudFront配置时，就没有此问题。也用您这个脚本在其他机器上搭同样的Trojan-Go套同样的CDN，也有此问题。
烦请开发者浏览一下我的问题，期待回复。**

**Comment by jinwyp** [comment]
可能是trojan-go 的CDN 不支持 因为没用过CloudFront CDN 可以到trojan-go的项目反馈问题
https://github.com/p4gefau1t/trojan-go/issues

因为443端口是trojan-go 提供的 和nginx无关, 关键是trojan-go的报错

**Comment by LIHAOCHI** [comment]
我想用着把trojan-go本地端口改为x，用transport-plugin禁用trojan-go自己的ssl，然后在nginx那里通过x端口反代trojan-go，用nginx自己的ssl，这样可行吗？
