### ISSUE TITLE
选项13，3种协议搭配都无法上网。

### ISSUE THREAD

**Issue by kaiyi88** [jinwyp/one_click_script#133]
选项13，3种协议搭配都无法上网。

**Comment by kaiyi88** [comment]
v2ray.service - V2Ray
     Loaded: loaded (/lib/systemd/system/v2ray.service; enabled; vendor preset: enable>
     Active: failed (Result: exit-code) since Tue 2022-03-15 22:33:08 EDT; 47s ago
       Docs: https://www.v2fly.org/
    Process: 68987 ExecStart=/root/v2ray/v2ray -config /root/v2ray/config.json (code=e>
   Main PID: 68987 (code=exited, status=2)
        CPU: 7ms

Mar 15 22:33:08 instance-20220304-1525 systemd[1]: v2ray.service: Scheduled restart jo>
Mar 15 22:33:08 instance-20220304-1525 systemd[1]: Stopped V2Ray.
Mar 15 22:33:08 instance-20220304-1525 systemd[1]: v2ray.service: Start request repeat>
Mar 15 22:33:08 instance-20220304-1525 systemd[1]: v2ray.service: Failed with result '>
Mar 15 22:33:08 instance-20220304-1525 systemd[1]: Failed to start V2Ray.

**Comment by jinwyp** [comment]
systemctl status v2ray  

上面信息表示没有启动成功 是不是安装过程有问题, 请按照教程从新的系统安装  域名请使用xxx.xxx.com这种二级域名

**Comment by kaiyi88** [comment]
试过多遍了，域名也是二级域名。
