### ISSUE TITLE
trojan安装失败

### ISSUE THREAD

**Issue by aaa1230217** [jinwyp/one_click_script#134]
2选项安装trojan原版，安装完成后 http可以访问，https无法访问网站
也上不了网
在下载trojan后解压的时候 好像报错找不到文件 但是还是给出了密码和订阅链接
debian systemd[1]: trojan.service: Failed with result 'exit-code'.
debian11

**Comment by jinwyp** [comment]
证书没申请成功把？  systemctl status trojan 看看什么错误
