### ISSUE TITLE
请问Trojan-go安装后，Chrome访问有些网页提示NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by jinglikeblue** [jinwyp/one_click_script#135]
我正确安装了Trojan-go，google youtube什么的都能访问，但是有些网页会提示“你的連線不是私人連線”，错误代码：NET::ERR_CERT_AUTHORITY_INVALID 这样的提示。请问有没有解决方案呢?
示例网址：[https://www.okx.com/](https://www.okx.com/)

**Comment by jinglikeblue** [comment]
很尴尬，之前用OpenClash不行，这会儿用v2rayN客户端试了下又可以。请指点一下这是为啥

**Comment by jinwyp** [comment]
网站本身问题  请咨询 okx.com
