### ISSUE TITLE
如何解acme.sh: No such file or directory

### ISSUE THREAD

**Issue by qJerry** [jinwyp/one_click_script#136]
/dev/fd/63: line 1308: /root/.acme.sh/acme.sh: No such file or directory

这个脚本就一直报这个错，怎么解？

**Comment by jinwyp** [comment]
目前还不清楚有时候会报错是什么原因 , 一般reboot 重启一下 重新运行脚本就好了

**Comment by hunao0221** [comment]
centos 7 的话需要手动安装openssl
```bash
yum install openssl
```
