### ISSUE TITLE
安装内核找不到对应版本

### ISSUE THREAD

**Issue by mlch911** [jinwyp/one_click_script#137]
**Describe the bug** A clear and concise description of what the bug is.
在提出问题前请先自行排除服务器端问题和升级到最新客户端，同时也请通过搜索确认是否有人提出过相同问题。
![](https://s2.loli.net/2022/04/05/9lwrTq4VXkhDzom.png)

!!! 请务必提供安装的选择的第几项 !!!
!!! 请务必提供什么操作系统 和用的什么终端 !!!

1. 例如选择的第2项 安装trojan

**OS and Terminal:**  系统环境 信息 请务必提供什么操作系统 和用的什么终端 ，还有VPS主机商

- OS: Ubuntu
- Version 20.04
- Terminal :  Mac iTerm
- VPS  Linode

**To Reproduce** 复现方法  

Log Info 日志信息： 请提供安装出错的信息
例如xxx

安装完成nginx 是否启动成功，域名的网站是否能正常打开，如果打不开说明nginx安装有问题，请给出nginx安装时输出日志

**Comment by jinwyp** [comment]
运行脚本后 选的1 进入安装内核子菜单 然后 选的第几项安装的内核啊？ 是要安装xanmod内核吗？

**Comment by mlch911** [comment]
51，52，都一样找不到

**Comment by jinwyp** [comment]
更新了脚本 再试试 

 如果还是无法安装说明你vps的网络有问题，看看dns 是不是连不上 https://xanmod.org/ 和 deb.xanmod.org 网站

**Comment by mlch911** [comment]
嗯嗯ok了
