### ISSUE TITLE
甲骨文的实例ip用dns.he.net解析，申请证书总是失败

### ISSUE THREAD

**Issue by tingyue-wu** [jinwyp/one_click_script#138]
如题

**Comment by tingyue-wu** [comment]
我一开始是全新安装使用您的脚本选11，申请证书失败导致xray也安装不上。后来我用别的脚本先装好了xray以及http访问页面，然后用你的脚本选26获取证书就成功了。可见脚本一开始失败是因为nginx没有部署导致http页面访问 不了所有通过http方式申请证书才会失败。是不是改一改脚本执行的顺序让11这个选项成功率更高。

**Comment by jinwyp** [comment]
1 什么系统? 
2 选的第几项 
3 错误信息 

不要用其他脚本 有冲突肯定安装不了啊, 

证书失败你看看什么原因啊 可以选单独申请证书那项测试. 80 端口不能被占用才可以申请证书

我的脚本可以完全干净的卸载重新安装, 其他脚本卸载的都有问题,无法干净卸载. 建议用全新系统只安装证书试试 
或者选17 只安装xray 不按照nginx 试试

**Comment by tingyue-wu** [comment]
> 1 什么系统? 2 选的第几项 3 错误信息
> ubuntu和Debian都试了，全新系统关闭防火墙，就用了你的脚本。错误提示：安装证书失败请重启vps再试一下……类似这样的话
> 不要用其他脚本 有冲突肯定安装不了啊,
> 没有用别的脚本。新系统。后来用了别的脚本反而和您的脚本配合成功获取证书了
> 证书失败你看看什么原因啊 可以选单独申请证书那项测试. 80 端口不能被占用才可以申请证书
> 单独申请也是失败。
> 我的脚本可以完全干净的卸载重新安装, 其他脚本卸载的都有问题,无法干净卸载. 建议用全新系统只安装证书试试 或者选17 只安装xray 不按照nginx 试试

**Comment by jinwyp** [comment]
全新系统 选17项 按照xray 或者选26像只申请证书 

你不贴出来出错信息 我怎么知道什么问题

甲骨文有时候dns有问题 极有可能是网络问题

**Comment by jinwyp** [comment]
> 额额 我也遇到了但我解决了 arm 实列 乌班图系统 安装acme.sh 会安装到/home/ubuntu/.acme.sh/ 这个路径 但是脚本访问的是/root/.acme.sh/ 这个路径 所以出现问题 找不到文件 申请证书失败 我手动把文件移动之后问题解决了

你这是非root用户运行的脚本吧？

**Comment by jiahao2333** [comment]
你好，是这样 我是先使用key+ubuntu用户名 登入ssh 之后使用su切换到root账户来执行脚本 但是出现了上述问题

**Comment by jinwyp** [comment]
> 你好，是这样 我是先使用key+ubuntu用户名 登入ssh 之后使用su切换到root账户来执行脚本 但是出现了上述问题

> 你好，是这样 我是先使用key+ubuntu用户名 登入ssh 之后使用su切换到root账户来执行脚本 但是出现了上述问题

acme.sh 官方不推荐用非root用户使用
