### ISSUE TITLE
Trojan-go搭建完成后，windows平台可正常使用，但IOS使用Shadowrocket配置无效

### ISSUE THREAD

**Issue by SimpleKHHHH** [jinwyp/one_click_script#139]
**Describe the bug** A clear and concise description of what the bug is.
在提出问题前请先自行排除服务器端问题和升级到最新客户端，同时也请通过搜索确认是否有人提出过相同问题。

!!! 请务必提供安装的选择的第几项 !!!
!!! 请务必提供什么操作系统 和用的什么终端 !!!

1. 选择的第3项
安装 trojan-go 和 nginx, 支持CDN 开启websocket, trojan-go 运行在443端口

- OS: [Centos8.2]
- Version [e.g. 7]
- Terminal :  linux MobaXterm
- VPS  [aliyun HK VPS ]  

**To Reproduce** 复现方法  

Log Info 日志信息： 请提供安装出错的信息
安装 trojan-go 和 nginx后梯子成功搭建，Windows平台通过clash_for_windows配置yaml文件后正常访问谷歌以及油管。
但是在IOS(15.4)上通过Shadowrocket配置（选择Trojan，输入地址 端口 密码等信息），连通性验证正常，但是无法实际访问谷歌以及油管等。

**Comment by jiahao2333** [comment]
我也遇到了相同问题 麻烦问一下您是怎么解决的呢

**Comment by SimpleKHHHH** [comment]
> 
问题解决了吗？你要打开ws设置

**Comment by jiahao2333** [comment]
> 

呃呃问题解决了 是和nginx的冲突问题 所以偶尔可以偶尔不行

**Comment by jinwyp** [comment]
shadowrocket 不支持 trojan-go, 仅仅支持原版trojan 所以 trojan-go不要开启websocket功能, 就是说服务器安装的是trojan-go 但shadowrocket只能用trojan的协议链接服务器,无法使用trojan-go的websocket等功能. 或者安装的时候选择trojan不要选择trojan-go
