### ISSUE TITLE
按了29 安装面板再按1 ，直接退出了

### ISSUE THREAD

**Issue by ritech** [jinwyp/one_click_script#14]
按了29 安装面板再按1 ，直接退出了，按步骤卸载了之前装的也不行

**Comment by jinwyp** [comment]
有什么提示？

**Comment by browningfai** [comment]
我也是，什么提示都没有

**Comment by browningfai** [comment]
> 有什么提示？
我也是这样的，什么提示都没有

**Comment by browningfai** [comment]
> 有什么提示？

选择同步北京时间那个也是有时候进去没反应直接退出了

**Comment by jinwyp** [comment]
什么linux系统？ 用的什么ssh软件运行的？

**Comment by browningfai** [comment]
> 什么linux系统？用的什么ssh软件运行的？


Debian 10 x86_64       ssh    putty 
--

**Comment by jinwyp** [comment]
> > 什么linux系统？用的什么ssh软件运行的？
> 
> ## Debian 10 x86_64 ssh putty

可以换个windows ssh 客户端试试

**Comment by jinwyp** [comment]
这个是trojan 面板的一个bug ， 和 用的ssh 客户端登录VPS 有关， 目前只有centos 没有问题 

如果安装不了请换一个ssh客户端登录VPS

用 另外一台 Windows 机器的 Subsystem for Linux（WSL子系统的Ubuntu) 的 ssh登录VPS, 运行脚本就没有问题, 而用我的 macbook pro 的终端(装了 oh my zsh ) 登录VPS 运行脚本 就有问题 , 很奇怪的问题,

我的macbook pro 运行env 结果

TERM_PROGRAM=Apple_Terminal
SHELL=/bin/zsh
TERM=ansi （导致问题的关键环境变量）



具体请看  

https://github.com/jinwyp/one_click_script/issues/10

https://github.com/Jrohy/trojan/issues/272

**Comment by browningfai** [comment]
> 这个是trojan面板的一个bug，和用的ssh客户端登录VPS有关，目前只有centos没有问题
> 
> 如果安装不了请换一个ssh客户端登录VPS
> 
> 我用另外一台Windows机器的Linux子系统（WSL Linux的Ubuntu）的ssh登录VPS，运行脚本就没有问题，而用我的macbook pro的终端（装了哦，我的zsh）登录VPS运行脚本就有了问题，很奇怪的问题
> 
> 我的macbook pro运行env结果
> 
> TERM_PROGRAM = Apple_Terminal
> SHELL = / bin / zsh
> TERM = ansi（导致问题的关键环境变量）
> 
> 我把环境变量改成TERM = xterm就没有问题了
> 
> 具体请看
> 
> [＃10](https://github.com/jinwyp/one_click_script/issues/10)
> 
> [Jrohy /木马＃272](https://github.com/Jrohy/trojan/issues/272)

V2 UI面板也是同样问题的

**Comment by jinwyp** [comment]
已修复该问题
