### ISSUE TITLE
请问，节点连接443端口和伪装的https主页会冲突吗？

### ISSUE THREAD

**Issue by tingyue-wu** [jinwyp/one_click_script#140]
请问，节点连接443端口和伪装的https主页会冲突吗？会不会443端口连着v2客户端时https主页打不开，因为我有时候发现https主页会打不开，而这时http页面可以打开。
另外已经部署了443端口，怎么改成其它端口，是重新安装吗？

还有一个443端口不是只能建立一个节点吗，为什么会有10个uuid和20个trajon密码。要进vps修改配置文件的端口建立第二个节点连接的话，同时也可以修改uuid，所以预先生成几十个配置，有点多余，因为仍然要进去修改的。也或者是我理解错误不会用。

**Comment by jinwyp** [comment]
1 要看选的第几项 哪个服务 提供443端口的服务. 例如 https 网页打不开 , 而http可以打开 说明安装的是nginx 提供80的服务, 443是由xray或trojan提供的服务.  http网页可以打开 因为nginx运行在80端口, https 网页打不开 说明xray或trojan运行失败 
可以运行systemctl status xray 看xray是否运行,  
443又xray提供服务 然后xray转发到80的nginx 提供网页服务

2 修改端口直接修改xray的配置就可以 在/root/v2ray/config.json  
3 多用户连接的都是同一个端口, 通过不用的用户UUID区分v2ray多用户啊, 具体看xray的说明  
https://www.v2fly.org/config/inbounds.html#inboundobject
https://guide.v2fly.org/basics/vmess.html#%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%85%8D%E7%BD%AE
