### ISSUE TITLE
安装v2ray/xray/trojan-go失败，没有安装本体

### ISSUE THREAD

**Issue by LIHAOCHI** [jinwyp/one_click_script#141]
1. 选择的第11项、15项、21项。

**OS and Terminal:**  系统环境 信息 请务必提供什么操作系统 和用的什么终端 ，还有VPS主机商

- OS: Debian
- Version 11
- Terminal :  Termius
- VPS  Vultr

**To Reproduce** 复现方法  

选择任意一项安装v2ray/xray/trojan-go后，通过分享链接试图连接vps，客户端报错，此时在/root/v2ray查看，geoip、geosite、readme.md、v2ray/xray/trojan-go本体均不存在，只有几个分享链接的文本和配置配置文件。并且在安装过程中并没有发现有安装v2ray/xray/trojan-go的过程。

**Comment by jinwyp** [comment]
是不是已经安装过其他脚本,或已经安装过nginx 导致没有继续安装

**Comment by LIHAOCHI** [comment]
没事了，发现是Vultr机子开机的时候默认没有安装unzip导致没法解开压缩包
