### ISSUE TITLE
vless+WS+tls

### ISSUE THREAD

**Issue by Atajan2000** [jinwyp/one_click_script#144]
Hi there i installed this script on my vps but can not find option how to add and delete user, how to do it without installing UI web admin panel PLZ HELP!

**Comment by Atajan2000** [comment]
also after install x-ui admin panel to clean VPS and create any client link it is not working but if i install without UI panel it is working i do not know why it is being like this

**Comment by jinwyp** [comment]
Any x-ui panel issue, check out link of x-ui project https://github.com/vaxilu/x-ui 
you need do some setting for x-ui, such as ssl cert file path

**Comment by Atajan2000** [comment]
> Any x-ui panel issue, check out link of x-ui project https://github.com/vaxilu/x-ui you need do some setting for x-ui, such as ssl cert file path

Tried it not working is there any solution for this?
