### ISSUE TITLE
想问下大佬关于 nginx SNI 分流 选项的问题

### ISSUE THREAD

**Issue by AHCorn** [jinwyp/one_click_script#147]
系统为CentOS 7
使用的面板是Appnode，已经完成Web环境的搭建
使用脚本选项中的第23项 

> 同时安装 nginx, v2ray或xray 和 trojan或trojan-go, 通过 nginx SNI 分流, 支持CDN, 支持与现有网站共存, nginx 运行在443端口

提示已经安装nginx，然后自动退出
卸载后重新安装原先站点就无法访问了，请问该怎么选才能让Appnode中的已有站点和代理服务共存呢？

**Comment by jinwyp** [comment]
不会手动改nginx 配置 还是算了, 因为脚本安装的nginx和你appnode 面板nginx配置不一样, 你要用面板的话肯定要自己手动改配置.

如果会改的话 用我的脚本安装后 把/etc/nginx/nginx.conf 复制出来  然后用脚本卸载
,然后装好appnode 自己参考我这个nginx 改就可以

**Comment by AHCorn** [comment]
感谢您的解答，已经弄好啦
