### ISSUE TITLE
安装v2ray 和xray 不能连接，但trojan是通的

### ISSUE THREAD

**Issue by aoteman5255661** [jinwyp/one_click_script#148]
- OS： 甲骨文云dd debian
- version：debain9
- vps： 甲骨文云
- 服务端日志
![1](https://user-images.githubusercontent.com/25601353/168076920-f83b2ac7-c465-4ec3-8ee9-3f113d478dc8.JPG)

**Comment by jinwyp** [comment]
选的第几项安装的? 是arm cpu吗?

**Comment by jinwyp** [comment]
> amd 1h1g 没有dd前也是这样ubuntu的 选的13 换其他xray v2ray脚本可以通

13 项没有trojan 啊 你trojan怎么通的？

13 项 你没装nginx吧  fallback 必须要80有web服务器

可以运行 systemctl status v2ray  或 systemctl status xray 查看一下状态 是否允许正常

**Comment by jinwyp** [comment]
选择13 安装后 +(VMess-TCP-TLS) 协议有问题无法连接  
其他协议已经修复 可以正常使用， 同时导入链接问题也修复了。

+(VMess-TCP-TLS) 为什么不行无法使用了， 好像是 某个版本v2ray core有问题 具体还要调查

**Comment by jinwyp** [comment]
https://github.com/v2fly/v2ray-examples/issues/79

https://github.com/XTLS/Xray-examples/issues/66

已经提交到v2ray和xray 那去了 看看到底什么问题

**Comment by jinwyp** [comment]
问题已解决  服务器端配置了 伪装类型 为 http , 而客户端的生成的配置漏了
