### ISSUE TITLE
Multiple Installation

### ISSUE THREAD

**Issue by rudiana587** [jinwyp/one_click_script#149]
#help
I want to install Vless+WS/gRPC+TLS + Vmess+WS/gRPC+TLS + Trojan-go+WS+TLS with nginx in 1 VPS. How to do that step by step ?

**Comment by jinwyp** [comment]
check https://github.com/jinwyp/one_click_script/blob/master/README_CN.md

Run script and  choose 13 .

**Comment by rudiana587** [comment]
how about each mode running on different subdomain but still on 1 vps, like this:

vless+ws/grpc+tls with nginx on vless.domain.com
vmess+ws/grpc+tls with nginx on vmess.domain.com
trojan-go+ws+tls with nginx on trojan-go.domain.com

can it works ?

**Comment by jinwyp** [comment]
> how about each mode running on different subdomain but still on 1 vps, like this:
> 
> vless+ws/grpc+tls with nginx on vless.domain.com vmess+ws/grpc+tls with nginx on vmess.domain.com trojan-go+ws+tls with nginx on trojan-go.domain.com
> 
> can it works ?

Yes. Choose 23 Use nginx sni to do this .  You need  edit /etc/nginx/nginx.conf to support more protocal vless

**Comment by jinwyp** [comment]
I add a new feature that can input  different systemd xray service name. Now You can install multiple xray on one vps. Choose 13-17 to install xray and only install nginx once.
