### ISSUE TITLE
acme.sh 貌似有点问题，这个脚本稳定性真不咋地

### ISSUE THREAD

**Issue by ritech** [jinwyp/one_click_script#15]
开始重新申请证书 acme.sh standalone mode !

[Wed 16 Sep 2020 09:41:05 AM EDT] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 35
[Wed 16 Sep 2020 09:41:05 AM EDT] Can not init api.

**Comment by jinwyp** [comment]
没遇到过，第一次用nginx 模式申请的时候有问题吗？ 可以卸载 重新安装
