### ISSUE TITLE
安装证书时候报错

### ISSUE THREAD

**Issue by CXY037** [jinwyp/one_click_script#150]
安装证书时候提示错误
[Wed May 18 22:17:11 CST 2022] The domain '*.*.com' is not a cert name. You must use the cert name to specify the cert to install.
[Wed May 18 22:17:11 CST 2022] Can not find path:'/root/.acme.sh/*.*.com_ecc'
尝试了很多次都无法解决

**Comment by jinwyp** [comment]
选的第几项安装的？

**Comment by jinwyp** [comment]
已修复了

**Comment by CXY037** [comment]
选项2 跟选项3都提示这个
在 2022年5月18日 +0800 22:52，JinWYP ***@***.***>，写道：

**Comment by CXY037** [comment]
谢谢～
在 2022年5月20日 +0800 18:26，JinWYP ***@***.***>，写道：
