### ISSUE TITLE
全部搭建成功了，就是连不上

### ISSUE THREAD

**Issue by wwwliutao125** [jinwyp/one_click_script#152]
Oracle-Linux-8.5-2022.04.26-0，选是11，vmelss+tls+ws,,,,, nginx是运行的，伪装的网站能打开，证书也正常，v2ray状态也是正常，服务器时间也对着呢，，，，，，，，，，，，，，就是连不上，大神快来解决下

**Comment by jinwyp** [comment]
看看服务器端口是否有防火墙屏蔽了 或者选17 vless 换端口安装  

使用 https://ping.pe/ 网站查看ip或端口是否被封掉
