### ISSUE TITLE
求更新Trojan-web 可视化管理面板

### ISSUE THREAD

**Issue by 1eez** [jinwyp/one_click_script#153]
30. 子菜单 安装 trojan 和 v2ray 可视化管理面板,....
4. 查看日志, 管理用户, 查看配置等功能
2.用户管理
1.新增用户

增加后的用户，在web端看不到新增的用户列表（刷新了也看不见）

**OS and Terminal:**  系统环境 信息 请务必提供什么操作系统 和用的什么终端 ，还有VPS主机商

- OS: Centos 7.6
- Version 7.6
- Terminal :  inux zsh 
- VPS  Tencent Cloud

**To Reproduce** 复现方法  

选择升级后，提示：
==================================================
     升级成功 Trojan-web 可视化管理面板: 2.14.1 !
 ==================================================

但我看https://github.com/Jrohy/trojan 的截图
已经可是在Web端，增删查改用户了。

求大神更新脚本。

**Comment by jinwyp** [comment]
本脚本就是用的官方脚本安装的， 具体问题可以到 https://github.com/Jrohy/trojan/issues 反馈

你说的没有.新增用户 是什么意思 ，直接在web管理面板增加用户不就行了吗？ 

是说用脚本增加的用户 在web界面没有显示？  这个都是用的 https://github.com/Jrohy/trojan/issues  官方脚本， 去他的issue问吧

**Comment by 1eez** [comment]
> 本脚本就是用的官方脚本安装的， 具体问题可以到 https://github.com/Jrohy/trojan/issues 反馈
> 
> 你说的没有.新增用户 是什么意思 ，直接在web管理面板增加用户不就行了吗？
> 
> 是说用脚本增加的用户 在web界面没有显示？ 这个都是用的 https://github.com/Jrohy/trojan/issues 官方脚本， 去他的issue问吧

好的，谢谢回复。
