### ISSUE TITLE
[bug]同时安装 nginx, v2ray或xray 和 trojan或trojan-go选项的bug

### ISSUE THREAD

**Issue by never8388** [jinwyp/one_click_script#154]
选择的第2项 同时安装 nginx, v2ray或xray 和 trojan或trojan-go (VLess/Vmess-WS-TLS)+Trojan, 支持CDN, trojan或trojan-go运行在443端口

- OS: debian 
- Version 10
- Terminal : mac自带终端
- VPS  hax

复现方法 :先安装一次22选项，再使用脚本把安装的xray、nginx删掉，再次选择安装。此时提示"检测到本机已经申请过域名证书 是否新增申请域名证书
 选是为新增申请域名证书, 选否为续签或删除已申请域名证书"
选否之后只能续签或删除，不能直接用。

**Comment by jinwyp** [comment]
选22 后 你要全部卸载 nginx xray trojan 才能再次安装啊， 同时域名还要选Y 就是新增域名， 这里可能文字误导了， 都应该选新增域名 即使域名是一样的

**Comment by jinwyp** [comment]
域名提示误导问题已经修复。请更新脚本重新允许
