### ISSUE TITLE
nginx安装出错

### ISSUE THREAD

**Issue by xingyu2016** [jinwyp/one_click_script#158]
openvz主机  系统centos7+ / debian9+ 都试了 均报错无法运行

11 选项

Installed:
  nginx-mod-stream.x86_64 1:1.20.1-9.el7                                                                                                                                          

Dependency Installed:
  centos-indexhtml.noarch 0:7-9.el7.centos        centos-logos.noarch 0:70.0.6-3.el7.centos        gperftools-libs.x86_64 0:2.6.1-1.el7        nginx.x86_64 1:1.20.1-9.el7       
  nginx-filesystem.noarch 1:1.20.1-9.el7          openssl11-libs.x86_64 1:1.1.1k-3.el7            

Complete!
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: la.mirrors.clouvider.net
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: mirrors.xtom.com
 * updates: mirrors.oit.uci.edu
Resolving Dependencies
--> Running transaction check
---> Package nginx.x86_64 1:1.20.1-9.el7 will be updated
--> Processing Dependency: nginx(abi) = 1.20.1 for package: 1:nginx-mod-stream-1.20.1-9.el7.x86_64
---> Package nginx.x86_64 1:1.22.0-1.el7.ngx will be an update
--> Processing Dependency: libpcre2-8.so.0()(64bit) for package: 1:nginx-1.22.0-1.el7.ngx.x86_64
--> Running transaction check
---> Package nginx.x86_64 1:1.20.1-9.el7 will be updated
--> Processing Dependency: nginx(abi) = 1.20.1 for package: 1:nginx-mod-stream-1.20.1-9.el7.x86_64
---> Package pcre2.x86_64 0:10.23-2.el7 will be installed
--> Finished Dependency Resolution
Error: Package: 1:nginx-mod-stream-1.20.1-9.el7.x86_64 (@epel)
           Requires: nginx(abi) = 1.20.1
           Removing: 1:nginx-1.20.1-9.el7.x86_64 (@epel)
               nginx(abi) = 1.20.1
           Updated By: 1:nginx-1.22.0-1.el7.ngx.x86_64 (nginx)
               Not found
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by xingyu2016** [comment]
root@v2:~# systemctl status nginx.service
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/nginx.service.d
           └─override.conf
   Active: failed (Result: exit-code) since Fri 2022-06-24 02:18:38 CEST; 1min 40s ago
 Main PID: 14111 (code=exited, status=0/SUCCESS)

Jun 24 02:18:38 v2 systemd[1]: Starting A high performance web server and a reverse proxy server...
Jun 24 02:18:38 v2 nginx[14213]: nginx: [warn] invalid value "TLSv1.3" in /etc/nginx/nginx.conf:39
Jun 24 02:18:38 v2 nginx[14213]: nginx: configuration file /etc/nginx/nginx.conf test failed
Jun 24 02:18:38 v2 systemd[1]: nginx.service: Control process exited, code=exited status=1
Jun 24 02:18:38 v2 systemd[1]: Failed to start A high performance web server and a reverse proxy server.
Jun 24 02:18:38 v2 systemd[1]: nginx.service: Unit entered failed state.
Jun 24 02:18:38 v2 systemd[1]: nginx.service: Failed with result 'exit-code'.

**Comment by xingyu2016** [comment]
换源没有用 最后找到这个脚本是可以的 他是本地编译的  希望作者也用他的这种方式安装  我还是你的这个脚本

**Comment by xingyu2016** [comment]
https://github.com/wulabing/V2Ray_ws-tls_bash_onekey

**Comment by jinwyp** [comment]
> 换源没有用 最后找到这个脚本是可以的 他是本地编译的 希望作者也用他的这种方式安装 我还是你的这个脚本 https://github.com/wulabing/V2Ray_ws-tls_bash_onekey

不用编译安装 只要改为nginx 1.18 并去掉/etc/nginx/nginx.conf 的 tls1.3 指令就可以了

**Comment by jinwyp** [comment]
脚本去掉了使用nginx官方源安装nginx，改为使用原有epel源 安装nginx ，因为epel源已经支持了nginx 1.20 . 

可以卸载nginx 重新更新脚本安装
