### ISSUE TITLE
18号功能亲测，搭建后Trojan-go使用完美，但是v2ray vless无法上网

### ISSUE THREAD

**Issue by naiyouhuifanli** [jinwyp/one_click_script#16]
用的系统是Centos7.6

**Comment by jinwyp** [comment]
安装选的哪项啊？

**Comment by naiyouhuifanli** [comment]
> 安装选的哪项啊？

大神你好，如标题，我选的是18号选项

**Comment by jinwyp** [comment]
> > 安装选的哪项啊？
> 
> 大神你好，如标题，我选的是18号选项。
> 
> 不过后面我试着分别单独去安装Trojan和v2ray，然后Trojan完美，但v2ray依旧无法上网

VMESS 和 Vless 都这样吗？
