### ISSUE TITLE
脚本实际上没有安装trojan-go，而是普通trojan

### ISSUE THREAD

**Issue by tdjnodj** [jinwyp/one_click_script#160]
操作系统：debian
版本 11
终端：Mac的终端
vps:woiden
安装的trojan-go根本不是trojan-go，而是普通的trojan。（我选22，输出的配置信息也是trojan-go甚至还有ws，但实际上不能用ws访问，将节点信息去除ws后就能使用）

**Comment by tdjnodj** [comment]
> 操作系统：debian 版本 11 终端：Mac的终端 vps:woiden 安装的trojan-go根本不是trojan-go，而是普通的trojan。（我选22，输出的配置信息也是trojan-go甚至还有ws，但实际上不能用ws访问，而将节点信息去除ws后就能使用）

**Comment by jinwyp** [comment]
你用的trojan的客户端端是什么？  trojan-go的客户端需要专门的客户端才可以用ws

**Comment by tdjnodj** [comment]
> 

用的是clash，https://github.com/Dreamacro/clash/wiki/configuration#proxy-groups clash也是支持trojan-ws的

**Comment by jinwyp** [comment]
clash 不支持trojan-go 的特殊协议,

 已测试用qvray 可以正常支持trojan-go的ws 协议. 再次注意 trojan-go和trojan很多地方不是一个协议 需要支持trojan-go的客户端配合使用
