### ISSUE TITLE
Option 23 sni nginx

### ISSUE THREAD

**Issue by t-e-s-tweb** [jinwyp/one_click_script#165]
**Describe the bug** A clear and concise description of what the bug is.
在提出问题前请先自行排除服务器端问题和升级到最新客户端，同时也请通过搜索确认是否有人提出过相同问题。

!!! 请务必提供安装的选择的第几项 !!!
!!! 请务必提供什么操作系统 和用的什么终端 !!!

1. 23 option nginx sni
**OS and Terminal:**  

- OS: Debian 
- Version [e.g. 11]
- Terminal :  Putty
- VPS  [e.g.  Racknerd]

**To Reproduce** 
Install option 23 and after that nginx doesn't start and the vless vmess ws grpc options have random port instead of port 443

Log Info Starting A high performance web server and a reverse proxy server...            2]: nginx: [emerg] unknown directive "stream" in /etc/nginx/nginx.conf:13          2]: nginx: configuration file /etc/nginx/nginx.conf test failed
]: nginx.service: Control process exited, code=exited, status=1/FAILURE
]: nginx.service: Failed with result 'exit-code'.
]: Failed to start A high performance web server and a reverse proxy server.

**Comment by jinwyp** [comment]
已修复 请更新脚本后 卸载原来的 重新安装

或在 /etc/nginx/nginx/conf  文件最上面 加入一行
include /etc/nginx/modules-enabled/*.conf;

然后重启 nginx  
systemctl restart nginx
