### ISSUE TITLE
(VLess-TCP-[TLS/XTLS])+(VLess-WS-TLS)+Trojan客户端连接报错

### ISSUE THREAD

**Issue by yuki0320** [jinwyp/one_click_script#166]
**Describe the bug** A clear and concise description of what the bug is.
在提出问题前请先自行排除服务器端问题和升级到最新客户端，同时也请通过搜索确认是否有人提出过相同问题。

!!! 请务必提供安装的选择的第几项 !!!
!!! 请务必提供什么操作系统 和用的什么终端 !!!

1. 例如选择的第21项 同时安装 v2ray或xray 和 trojan或trojan-go (VLess-TCP-[TLS/XTLS])+(VLess-WS-TLS)+Trojan, 支持CDN, 可选安装nginx, VLess运行在443端口

**OS and Terminal:**  系统环境 信息 请务必提供什么操作系统 和用的什么终端 ，还有VPS主机商

- OS: ubuntu
- Version 22.04
- Terminal :  xshell
- VPS  : oracle

**To Reproduce** 复现方法  

安装完成nginx 启动成功，域名的网站能正常打开,v2ray启动正常，防火墙也已经关闭，时区也改为国区
![image](https://user-images.githubusercontent.com/40019388/179555596-7a14dc0f-9234-4e26-95b0-af0246e95e32.png)
![image](https://user-images.githubusercontent.com/40019388/179555978-b4fdb535-cc65-4db3-970b-b5573ef589d1.png)
![image](https://user-images.githubusercontent.com/40019388/179556758-d3f841db-5b61-42cf-b438-6fff24b42334.png)

但是v2ray和trojan客户端连接都报错：
2022/07/19 00:14:00 [Warning] [2251353666] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://www.***.org/32941807): 502 Bad Gateway > websocket: bad handshake] > common/retry: all retry attempts failed

**Comment by yuki0320** [comment]
> 

![image](https://user-images.githubusercontent.com/40019388/179647272-c68b5ab5-184d-41f1-bcd6-ea5628e6b9e0.png)
![image](https://user-images.githubusercontent.com/40019388/179647302-54700990-3222-4c84-9120-1ac429bed906.png)

**Comment by yuki0320** [comment]
> 服务器端没问题的话 1 请更新v2rayN 5.29版本 2 用 http://ping.pe/ 查看VPS 端口是否被封 3 更换非443 端口 重新试试

按照网上的教程手动安装了v2ray和nginx配置Vmess-WS-TLS可以连接了

**Comment by yuki0320** [comment]
> > 
> 
> Kindly share the link to tutorials.

https://ericclose.github.io/V2Ray-TLS-WebSocket-Nginx-with-Cloudflare.html

**Comment by jinwyp** [comment]
选择21 安装后 trojan无法链接问题已经修复， 问题出在是最后的配置信息的trojan密码写错了。 更新脚本 卸载后 重新选21安装即可
