### ISSUE TITLE
Vless grpc broken option 23

### ISSUE THREAD

**Issue by t-e-s-tweb** [jinwyp/one_click_script#167]
Describe the bug A clear and concise description of what the bug is.

Installing option 23. Vless grpc doesn't work but if installed with any other option like 11 or 12 vless grpc works. 
!!! 请务必提供安装的选择的第几项 !!!
!!! 请务必提供什么操作系统 和用的什么终端 !!!

23 option nginx sni. Grpc vless will not connect. 
OS and Terminal:
OS: Debian
Version [e.g. 11]
Terminal : Putty/xshell
VPS [e.g. Racknerd]
To Reproduce
Install option 23 and after that vless grpc will not connect whether through port 443 or using the original ports from the configurations. 

Log Info

**Comment by jinwyp** [comment]
vless grpc 只能选择11 或14 安装 不支持23 nginx sni 这种
