### ISSUE TITLE
无法在只有ipv6的主机上安装

### ISSUE THREAD

**Issue by md5xwl** [jinwyp/one_click_script#168]
vultr有只有ipv6的主机只要2.5刀。
所以试了下，github没有ipv6地址，所有的包都无法下载，手动下载包然后传到主机上，没有报错，tanjon-go在监听443端口，但是客户端无法正常连接。

ubuntu20.04

**Comment by jinwyp** [comment]
这个问题无法解决。

其实有个很容易的方法，安装WARP 添加IPV4 的IP 就可以了 https://github.com/fscarmen/warp
