### ISSUE TITLE
采用安装脚本中23，nginx-sni 分流，v2ray可以正常运行，但是trojan-go无法启动。

### ISSUE THREAD

**Issue by hqwl159** [jinwyp/one_click_script#169]
**Describe the bug** A clear and concise description of what the bug is.
在提出问题前请先自行排除服务器端问题和升级到最新客户端，同时也请通过搜索确认是否有人提出过相同问题。
如题，采用trojan_v2ray_install.sh中“23 同时安装 nginx, v2ray或xray 和 trojan或trojan-go, 通过 nginx SNI 分流, 支持CDN, 支持与现有网站共存, nginx 运行在443端口” 安装后，trojan-go无法启动。

采用ubuntu 22.04，终端是原生shell， VPS主机商为racknerd

trojan-go log
`Jul 24 20:13:32 racknerd-dc4df7 trojan-go[171794]: [INFO]  2022/07/24 20:13:32 trojan-go v0.10.6 initial>
Jul 24 20:13:32 racknerd-dc4df7 systemd[1]: trojan-go.service: Main process exited, code=exited, status=>
Jul 24 20:13:32 racknerd-dc4df7 systemd[1]: trojan-go.service: Failed with result 'exit-code'.
Jul 24 20:13:43 racknerd-dc4df7 systemd[1]: trojan-go.service: Scheduled restart job, restart counter is>
Jul 24 20:13:43 racknerd-dc4df7 systemd[1]: Stopped trojan-go.
Jul 24 20:13:43 racknerd-dc4df7 systemd[1]: Started trojan-go.
Jul 24 20:13:43 racknerd-dc4df7 trojan-go[172003]: [INFO]  2022/07/24 20:13:43 trojan-go v0.10.6 initial>
Jul 24 20:13:43 racknerd-dc4df7 systemd[1]: trojan-go.service: Main process exited, code=exited, status=>
Jul 24 20:13:43 racknerd-dc4df7 systemd[1]: trojan-go.service: Failed with result 'exit-code'.
Jul 24 20:13:53 racknerd-dc4df7 systemd[1]: trojan-go.service: Scheduled restart job, restart counter is>
Jul 24 20:13:53 racknerd-dc4df7 systemd[1]: Stopped trojan-go.
Jul 24 20:13:53 racknerd-dc4df7 systemd[1]: Started trojan-go.
Jul 24 20:13:53 racknerd-dc4df7 trojan-go[172212]: [INFO]  2022/07/24 20:13:53 trojan-go v0.10.6 initial>
Jul 24 20:13:53 racknerd-dc4df7 systemd[1]: trojan-go.service: Main process exited, code=exited, status=>
Jul 24 20:13:53 racknerd-dc4df7 systemd[1]: trojan-go.service: Failed with result 'exit-code'.`

**Comment by jinwyp** [comment]
可以运行 systemctl status trojan-go.service 看一下trojan-go 是否正常运行

你选了23后 然后下面选的哪个模式？

 1. Nginx + Trojan + V2ray + 伪装网站
 2. Nginx + Trojan + 伪装网站
 3. Nginx + V2ray + 伪装网站
 4. Nginx + Trojan + V2ray + 已有网站共存
 5. Nginx + Trojan + 已有网站共存
 6. Nginx + V2ray + 已有网站共存

**Comment by hqwl159** [comment]
您的邮件已收到，我会尽快进行回复。--from hQing
