### ISSUE TITLE
哪个是不安装nginx的，我服务器上已经安装过了。

### ISSUE THREAD

**Issue by lukemin** [jinwyp/one_click_script#17]
哪个是不安装nginx的，我服务器上已经安装过了，并且有网站在运行。

**Comment by jinwyp** [comment]
目前都是安装nginx的， 因为trojan会接管443端口， 所以 如果已有nginx 网站 必须自己配置 否则无法共存

如果有需求我可以弄个单独的脚本不安装nginx

**Comment by lukemin** [comment]
需要，谢谢

**Comment by jinwyp** [comment]
> 需要，谢谢

已增加该功能  选择29后可以根据菜单选择 只安装trojan 或 v2ray 不安装nginx

**Comment by lukemin** [comment]
谢谢，有空试一下，现在用v2ray，vmess+ws+tls虽然速度慢，但是还比较稳定。
