### ISSUE TITLE
看见FRP是PVE 上安装，可以直接在服务器上面安装吗？

### ISSUE THREAD

**Issue by llity** [jinwyp/one_click_script#170]
直接在centos上安装FRP和Trojan等服务器端。

谢谢，本地使用路由器穿透。

**Comment by jinwyp** [comment]
可以的

**Comment by llity** [comment]
> 可以的
下面的FRPS脚本能和trojan服务共存吗？
https://github.com/jinwyp/one_click_script/blob/master/dsm/readme.md

**Comment by jinwyp** [comment]
不影响 只要端口号不冲突就可以， 注意frps 也有web服务， 所以要注意是否端口号80 或443有冲突
