### ISSUE TITLE
建议增加自定义伪装网页的选项

### ISSUE THREAD

**Issue by feizhuqwq** [jinwyp/one_click_script#172]
建议在使用脚本安装服务的过程中，增加自定义伪装网页的选项
例如可以选择反向代理其他网页，或选择预设静态页  这样更加便捷
而不是在安装完成后手动修改Nginx的配置文件或目录文件
感谢

**Comment by jinwyp** [comment]
不是已经有默认了预设静态页的伪装网页了吗？ 你还要什么功能.  如果需要换网页内容直接 替换 /nginxweb/html 里面的内容就可以了

**Comment by feizhuqwq** [comment]
我知道，除了使用静态网页，反向代理互联网上的其他网页可以有更多选择
我是希望在脚本增加一个设置自定义反代网页的选项，防止过多的人使用同一个伪装网页

**Comment by 55113110039** [comment]
+1，我有个需求是伪装另一个网站（比如https://google.com)，但是修改了/etc/nginx/nginx.conf，在里面添加反代之后访问网页还是会像之前一样随机跳转。具体表现如下：
修改配置文件
    server {
        listen       80;
        server_name  mydomain;

	client_max_body_size 5000M;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For '$proxy_add_x_forwarded_for';
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header Sec-WebSocket-Extensions $http_sec_websocket_extensions;
	proxy_set_header Sec-WebSocket-Key $http_sec_websocket_key;
	proxy_set_header Sec-WebSocket-Version $http_sec_websocket_version;
	proxy_cache off;
	proxy_redirect off;
	proxy_buffering off;

	location / {
		proxy_pass https://google.com/;
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_ssl_verify off;
		proxy_http_version 1.1;
		proxy_set_header Host mydomain;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_read_timeout 86400;
	}

然后访问mydomain，并不能反代google.com，而是会随机访问 https://mydomain/xxx/index.html, 然后出现如下报错：
<img width="305" alt="image" src="https://user-images.githubusercontent.com/109523248/189476359-2a0c3f31-7203-469a-843f-0866688b5581.png">

另外问一个问题，请问与ssl相关的配置是写在哪里的呢，我看nginx.conf里面并没有，不知道应该去哪个地方找。

**Comment by jinwyp** [comment]
脚本已经添加反代选项
