### ISSUE TITLE
xray status error

### ISSUE THREAD

**Issue by Atajan2000** [jinwyp/one_click_script#173]
hi guys! i installed web-ui of v2rayng but the v2ray status is showing error sometimes saying stop when i enter to web min it was running but after adding some vless it said error also my genereted vles code is not connecting if you can help can you help me plz
![error](https://user-images.githubusercontent.com/75452259/183869075-f86630f9-99b5-4fdc-96ac-5ed630095f9a.PNG)
!

**Comment by jinwyp** [comment]
Go to https://github.com/vaxilu/x-ui to talk x-ui issue.
Go to  https://github.com/XTLS/Xray-core to check xray config 

You can delete all config and user and upgrade newer xray  or v2ray. 

Vless need more setting. Search keyword "x-ui" on youtube to find solution

**Comment by mikhey18** [comment]
Hi! Now I have the same problem. Does anyone know how to solve it? Installed 3 previous times on different hosting and no problems anywhere. Not only did I have to open the port manually, but now I'm getting an error xray 
![111](https://github.com/jinwyp/one_click_script/assets/56192768/d71cb2d8-ba8b-4537-aa41-929a450b35eb)
![222](https://github.com/jinwyp/one_click_script/assets/56192768/749e3853-d6ab-49a9-80b1-f93a9df36b1c)

**Comment by jinwyp** [comment]
The log show that port 443 already in use 

Stop Nginx or other web service and try again.

**Comment by simmorsal** [comment]
Make sure there are no inbounds with the protocol `trojan`. Removing them fixed it for me
