### ISSUE TITLE
现在更新5.1.0正式用户版啦 请问一下脚本现在支持这个正式版吗

### ISSUE THREAD

**Issue by shinanzhuomo** [jinwyp/one_click_script#176]
现在更新5.1.0正式用户版啦 请问一下脚本现在支持这个正式版吗

**Comment by jinwyp** [comment]
[v5.1.0 User Preview](https://github.com/v2fly/v2ray-core/releases/tag/v5.1.0)

还不是正式版啊

**Comment by jinwyp** [comment]
已增加可以选择安装 5.1还是4.45.2 版本
