### ISSUE TITLE
Nginx报错，不能够启动

### ISSUE THREAD

**Issue by yaak63** [jinwyp/one_click_script#178]
VPS为搬瓦工Centos7原版
选23项，SNI，原版trojan,xray Vless+xtls+nginx+伪装网站
终端为openwrt及android
问题是，nginx启动不了，连带vless不能够启动

安装完成nginx 是否启动成功，域名的网站是否能正常打开，如果打不开说明nginx安装有问题，请给出nginx安装时输出日志
systemctl status nginx.service
● nginx.service - The nginx HTTP and reverse proxy server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/nginx.service.d
           └─override.conf
   Active: failed (Result: exit-code) since Tue 2022-09-27 11:29:16 CST; 8h ago
  Process: 3890 ExecStartPre=/usr/sbin/nginx -t (code=exited, status=1/FAILURE)
  Process: 3888 ExecStartPre=/usr/bin/rm -f /run/nginx.pid (code=exited, status=0/SUCCESS)
error log:
Sep 27 11:29:16 $ systemd[1]: Starting The nginx HTTP and reverse proxy server...
Sep 27 11:29:16 $ nginx[3890]: nginx: [emerg] conflicting parameter "www.XXXX.XXX" in /etc/nginx/nginx.conf:17
Sep 27 11:29:16 $ nginx[3890]: nginx: configuration file /etc/nginx/nginx.conf test failed
Sep 27 11:29:16 $ systemd[1]: nginx.service: control process exited, code=exited status=1
Sep 27 11:29:16 $ systemd[1]: Failed to start The nginx HTTP and reverse proxy server.
Sep 27 11:29:16 $ systemd[1]: Unit nginx.service entered failed state.
Sep 27 11:29:16 $ systemd[1]: nginx.service failed.
__________________________________________________________
自己检查nginx.conf，第17行发现trojan与vless用同一个域名，请问是不是这里发生了冲突？需要卸载重装吗？

**Comment by jinwyp** [comment]
nginx.conf 全部的配置内容给一下

**Comment by yaak63** [comment]
运行nginx -t结果如下：
root # nginx -t
nginx: [emerg] conflicting parameter "www.hwzm.cf" in /etc/nginx/nginx.conf:17
nginx: configuration file /etc/nginx/nginx.conf test failed
[nginx_conf.txt](https://github.com/jinwyp/one_click_script/files/9669822/nginx_conf.txt)
由于nginx.cof不能够粘贴，改为文本。

**Comment by jinwyp** [comment]
www.hwzm.cf trojan;
        www.hwzm.cf v2ray;

17 行 trojan 和 v2ray 使用了相同的域名  是不行的, 必须使用不同的域名SNI才可以.  
可以选24 卸载重新安装.  

也可以自己编辑这个配置文件, 但还需要手动把新域名的申请的证书 放到/nginxhtml/cert下面 .

**Comment by yaak63** [comment]
谢谢指教，再请教几个问题:用同一个根目录的二级子目录行吗？如用ab和xy作为二级域名该用哪个作为地址ip标识？另外如果不用www.hwzm.cf作为其中的一个，可以将其布置为缺省网页吗？地址ip域名安装成功以后可以将云点灰吗？请不吝指教，谢谢。

**Comment by jinwyp** [comment]
> 谢谢指教，再请教几个问题:用同一个根目录的二级子目录行吗？如用ab和xy作为二级域名该用哪个作为地址ip标识？另外如果不用www.hwzm.cf作为其中的一个，可以将其布置为缺省网页吗？地址ip域名安装成功以后可以将云点灰吗？请不吝指教，谢谢。

看不懂你的问题.
1 目前支持 www.xxx.com 这种， 如果xx.www.xxx.com 这种三级域名 应该是不可以的， 无法申请证书。 好像 cloudflare不支持申请三级域名证书
2 缺省网页也需要提供一个新的域名 
3 cloudflare 是否开启小云朵的CDN， 取决于使用的协议， 只有websocket 支持开启小云朵， tcp协议不支持开启.  就是所有协议都支持点灰，不开启小云朵。

**Comment by yaak63** [comment]
抱歉，我的意思是用hwzm.cf作根域名，ab,xy,www作二级域名，以根域名作A记录，其余三个作cname记录指向根域名。以ab.xxx.xx;xy.xxx.xx,www.xxx.xx分别申请证书，以www.xxx.xx作为网页。看这样行不行。

**Comment by jinwyp** [comment]
> 抱歉，我的意思是用hwzm.cf作根域名，ab,xy,www作二级域名，以根域名作A记录，其余三个作cname记录指向根域名。以ab.xxx.xx;xy.xxx.xx,www.xxx.xx分别申请证书，以www.xxx.xx作为网页。看这样行不行。

ab,xy,www 做三个A记录就可以了。 cname不需要啊

**Comment by jinwyp** [comment]
> 感谢指教，获益匪浅。如果采用选项17用xray自带的trojan能够兼容trojan-go吗？是不是不需要sni了？也就是只需要一个域名就可以了？

1 xray 的trojan 不支持trojan-go 的websocket的功能。   
2 对 只需要一个域名
