### ISSUE TITLE
搭建成功，但是连不上，第11

### ISSUE THREAD

**Issue by jl1014171068** [jinwyp/one_click_script#179]
### 1、安装命令为11，然后一路全是默认回车。准备工作也全部按教程执行，但是pc和手机都无法正常翻墙； 

【11. 安装 v2ray或xray 和 nginx ([Vmess/Vless]-[TCP/WS/gRPC/H2/QUIC]-TLS), 支持CDN, nginx 运行在443端口】

### 2、执行cat /root/v2ray-access.log

2022/10/05 18:03:54 203.91.85.6:0 accepted tcp:ssl.gstatic.com:443 [IPv4_out] email: password11@gmail.com
2022/10/05 18:03:54 203.91.85.6:0 accepted tcp:play.google.com:443 [IPv4_out] email: password11@gmail.com
2022/10/05 18:03:54 203.91.85.6:0 accepted tcp:chat-dl.google.com:443 [IPv4_out] email: password11@gmail.com
2022/10/05 18:03:54 203.91.85.6:0 accepted tcp:chat-dl.google.com:443 [IPv4_out] email: password11@gmail.com
2022/10/05 18:03:55 203.91.85.6:0 accepted tcp:signaler-pa.clients6.google.com:443 [IPv4_out] email: password11@gmail.com
2022/10/05 18:03:55 203.91.85.6:0 accepted tcp:chat-dl.google.com:443 [IPv4_out] email: password11@gmail.com
2022/10/05 18:03:56 203.91.85.6:0 accepted tcp:signaler-pa.clients6.google.com:443 [IPv4_out] email: password11@gmail.com
2022/10/05 18:04:01 203.91.85.6:0 accepted tcp:ssl.gstatic.com:443 [IPv4_out] email: password11@gmail.com

### 3、pc使用mac端的v2rayu，为安装结束后推荐的mac v2ray下载地址下载。客户端报错日志为：

V2Ray 4.34.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.6 darwin/amd64)
A unified platform for anti-censorship.
2022/10/05 18:08:28 [Info] v2ray.com/core/main/jsonem: Reading config: config.json
2022/10/05 18:08:28 [Info] v2ray.com/core/app/dns: DNS: created localhost client
2022/10/05 18:08:28 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1080
2022/10/05 18:08:28 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 127.0.0.1:1087
2022/10/05 18:08:28 [Warning] v2ray.com/core: V2Ray 4.34.0 started
2022/10/05 18:08:32 [Info] [46989117] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [www.google.com:443] with URL [//www.google.com:443]
2022/10/05 18:08:32 [Info] [46989117] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:443
2022/10/05 18:08:32 [Info] [46989117] v2ray.com/core/transport/internet/websocket: creating connection to tcp:www.zhangbeibei.xyz:443
2022/10/05 18:08:32 127.0.0.1:65396 accepted //www.google.com:443 [proxy]
2022/10/05 18:08:32 [Info] [4117128938] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [www.google.com:443] with URL [//www.google.com:443]
2022/10/05 18:08:32 [Info] [4117128938] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:443
2022/10/05 18:08:32 [Info] [4117128938] v2ray.com/core/transport/internet/websocket: creating connection to tcp:www.zhangbeibei.xyz:443
2022/10/05 18:08:32 127.0.0.1:65398 accepted //www.google.com:443 [proxy]
2022/10/05 18:08:32 [Info] [2836917602] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [www.google.com:443] with URL [//www.google.com:443]
2022/10/05 18:08:32 [Info] [2836917602] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:443
2022/10/05 18:08:32 [Info] [2836917602] v2ray.com/core/transport/internet/websocket: creating connection to tcp:www.zhangbeibei.xyz:443
2022/10/05 18:08:32 127.0.0.1:65400 accepted //www.google.com:443 [proxy]
2022/10/05 18:08:32 [Info] [2983646910] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [www.google.com:443] with URL [//www.google.com:443]
2022/10/05 18:08:32 [Info] [2983646910] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:443
2022/10/05 18:08:32 127.0.0.1:65401 accepted //www.google.com:443 [proxy]
2022/10/05 18:08:32 [Info] [2983646910] v2ray.com/core/transport/internet/websocket: creating connection to tcp:www.zhangbeibei.xyz:443
2022/10/05 18:08:32 [Info] [931566172] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [www.google.com:443] with URL [//www.google.com:443]
2022/10/05 18:08:32 [Info] [931566172] v2ray.com/core/app/dispatcher: default route for tcp:www.google.com:443
2022/10/05 18:08:32 [Info] [931566172] v2ray.com/core/transport/internet/websocket: creating connection to tcp:www.zhangbeibei.xyz:443
2022/10/05 18:08:32 127.0.0.1:65402 accepted //www.google.com:443 [proxy]
2022/10/05 18:08:32 [Info] [2636721842] v2ray.com/core/proxy/http: request to Method [CONNECT] Host [p46-caldav.icloud.com.cn:443] with URL [//p46-caldav.icloud.com.cn:443]
2022/10/05 18:08:32 [Info] [2636721842] v2ray.com/core/app/dispatcher: default route for tcp:p46-caldav.icloud.com.cn:443
2022/10/05 18:08:32 127.0.0.1:65403 accepted //p46-caldav.icloud.com.cn:443 [proxy]
2022/10/05 18:08:32 [Info] [2636721842] v2ray.com/core/transport/internet/websocket: creating connection to tcp:www.zhangbeibei.xyz:443

**Comment by jinwyp** [comment]
1 检查域名的证书是否成功申请
2 检查nginx 是否运行 systemctl status nginx   ,  检查nginx 配置是否正常 nginx -t
3 检查v2ray 是否运行 systemctl status v2ray/xray

使用windows 客户端 最新版的 v2rayN ， mac客户端有问题 太老了

**Comment by jl1014171068** [comment]
### 1、域名证书排查
[Thu Oct  6 00:05:53 CST 2022] Reload success

 域名 www.zhangbeibei.xyz 的证书已经成功续签!

 ==================================================
 已检测到域名  的证书文件 获取成功!
  域名证书内容文件路径 /nginxweb/cert/fullchain.cer
  域名证书私钥文件路径 /nginxweb/cert/private.key
 ==================================================

### 2、nginx排查，

 Active: active (running) since Thu 2022-10-06 00:05:53 CST; 23s ago
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

### 3、v2ray状态排查

v2ray.service - V2Ray
Loaded: loaded (/lib/systemd/system/v2ray.service; enabled; vendor preset: enabled)
 Active: active (running) since Wed 2022-10-05 18:01:56 CST; 6h ago

window下的v2rayN,测试服务器延迟Ping是200ms，按说是正常的也无法Google，直接导入生成的vmess base64方式的，手机小火箭试过也不行。。

**Comment by jinwyp** [comment]
卸载后  选15 换其他端口安装试试， 不要用443端口

**Comment by honqiang** [comment]
不要用443端口了，现在全网封杀

**Comment by jl1014171068** [comment]
已解决，改了端口就好了

**Comment by Sayid1** [comment]
请问怎么更改nginx端口呢？直接修改nginx.conf的443端口就可以了？还是需要修改其它配置 @jl1014171068

**Comment by jinwyp** [comment]
> 请问怎么更改nginx端口呢？直接修改nginx.conf的443端口就可以了？还是需要修改其它配置 @jl1014171068

nginx 一般使用80 或 443  改其他端口没有意义。 可以选其他项 把 nginx 放到xray的后面 就可以修改xray的端口了。

如果看不懂说什么，  就是如果选11项 nginx 必须用443 端口 也可以改 /etc/nginx/conf.d/default.conf 里面的端口号， 但不建议改.

如果想使用其他端口建议不要选择11项安装

**Comment by Sayid1** [comment]
> > 请问怎么更改nginx端口呢？直接修改nginx.conf的443端口就可以了？还是需要修改其它配置 @jl1014171068
> 
> nginx 一般使用80 或 443 改其他端口没有意义。 可以选其他项 把 nginx 放到xray的后面 就可以修改xray的端口了。
> 
> 如果看不懂说什么， 就是如果选11项 nginx 必须用443 端口 也可以改 /etc/nginx/conf.d/default.conf 里面的端口号， 但不建议改.
> 
> 如果想使用其他端口建议不要选择11项安装

我用21号选项，xray安装在了2022端口，安装完后还是不行
运行 systemctl status trojan-go 命令发现trojan运行有问题，我没有选装nginx

● trojan-go.service - trojan-go
   Loaded: loaded (/usr/lib/systemd/system/trojan-go.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2022-11-11 09:00:47 EST; 9s ago
  Process: 79725 ExecStart=/root/trojan-go/trojan-go -config /root/trojan-go/server.json (code=exited, status=1/FAILURE)
 Main PID: 79725 (code=exited, status=1/FAILURE)

**Comment by jinwyp** [comment]
> 

建议搞不明白的 不要选21-23 ，只安装 xray 或只安装trojan-go
