### ISSUE TITLE
请教大佬，想要部署网站以及Trojan-web 可视化管理面板都在443端口(就是xxx.xx/56ab5#这种感觉)，应该如何操作呢？

### ISSUE THREAD

**Issue by Swor-dart** [jinwyp/one_click_script#180]
请教大佬，想要部署网站以及Trojan-web 可视化管理面板都在443端口(就是xxx.xx/56ab5#这种感觉)，应该如何操作呢？
希望不使用那些伪装静态网站，而是直接宝塔搭建php环境部署博客(xxx.xx)和Trojan-web 可视化管理面板(xxx.xx/56ab5#这种感觉)，应该如何操作呢？个人比较小白(全是自己喜欢折腾学习的)不是很懂代码和网站反代相关原理，望大佬有空简单指导一下，非常感谢！

**Comment by jinwyp** [comment]
1 使用nginx 反代trojan-web 就可以，要指定trojan-web的运行的端口号 .  使用我的脚本安装 trojan-web ， 然后查看nginx的配置 在  /etc/nginx/conf.d/trojanweb_site.conf.   同时trojan-web的运行的端口号是指定的，在systemd的 trojan-web.service 中查看启动trojan-web的命令 增加 -p 参数指定端口号运行

2 搞明白了1的nginx配置后, 手动增加自己的网站博客 nginx 配置 即可 通过不同域名区分博客还是trojan-web

3 如果要和宝塔共存， 就先安装宝塔， 然后用官方脚本安装trojan-web 。 然后根据1的nginx配置  在宝塔中新建一个网站反代trojan-web 

如果看不懂nginx 配置还是先去学习nginx 配置 否则无法和宝塔共存。

最后trojan-web的vless 也无法使用443端口 否则和宝塔冲突

**Comment by jinwyp** [comment]
1 只能删除nginx 和trojan-web ,  先装宝塔 . 可以先删除 nginx 后,  安装宝塔试试,不一定能行. 删除nginx 方法看下面脚本 
https://github.com/jinwyp/one_click_script/blob/master/trojan_v2ray_install.sh#L2186

2 安装trojanweb 不要安装nginx , 官方trojanweb 不会安装nginx

3 /56ab5 就是 location /56ab5  但下面的静态页面也要相应改,否则trojan web 页面不对.  可以用同一个域名, 但你blog和trojan-web 样式就有冲突, 你自己也可以研究nginx 配置解决. 都是nginx 配置的问题. 用两个域名比较简单 配置不冲突

**Comment by Swor-dart** [comment]
> 1 只能删除nginx 和trojan-web , 先装宝塔 . 可以先删除 nginx 后, 安装宝塔试试,不一定能行. 删除nginx 方法看下面脚本 https://github.com/jinwyp/one_click_script/blob/master/trojan_v2ray_install.sh#L2186
> 
> 2 安装trojanweb 不要安装nginx , 官方trojanweb 不会安装nginx
> 
> 3 /56ab5 就是 location /56ab5 但下面的静态页面也要相应改,否则trojan web 页面不对. 可以用同一个域名, 但你blog和trojan-web 样式就有冲突, 你自己也可以研究nginx 配置解决. 都是nginx 配置的问题. 用两个域名比较简单 配置不冲突

大佬我已经重新安装宝塔面板和网站环境了，用了两个域名，申请了证书，官方trojan-web脚本安装时选择了宝塔申请的证书，全部正常了，但是访问两个域名都会跳转到博客页面，宝塔只能部署一个证书吧？我应该怎么写反代代码呢？官方安装好像没有反向代理选项，是要新建一段server直接把上边那些代码填入nginx的配置中吗？这官方的脚本我不知道怎么写反代。

麻烦大佬了，非常感谢！

**Comment by jinwyp** [comment]
> 
是在宝塔中 建2个网站 一个blog 一个trojanweb , 互不冲突.  两个网站在宝塔中 配置都是独立的.  不会访问2个域名都跳到blog.
宝塔可以部署多个证书 根据域名不同 建不同的网站配置 

如果只建一个网站肯定是2个域名首页 都是进入blog了 要通过url区分 就是上面的nginx 配置放到宝塔的网站的nginx配置里面 编辑

trojanweb 会运行到一个端口上 查看一下trojanweb运行的端口 反代到这个端口号就行, 就是上面的nginx  26687 改个端口号 默认是81

https://github.com/Jrohy/trojan/wiki/nginx%E9%85%8D%E7%BD%AE

https://github.com/Jrohy/trojan/wiki/%E4%BF%AE%E6%94%B9web%E7%AB%AF%E5%8F%A3

**Comment by Swor-dart** [comment]
> 
我按照https://github.com/Jrohy/trojan/wiki/nginx%E9%85%8D%E7%BD%AE将端口和网址都改好了，trojan的端口也改好了，但是访问的时候却显示：
当前无法使用此页面
重定向次数过多

**Comment by Swor-dart** [comment]
> > > 
> > 
> > 
> > 是在宝塔中 建2个网站 一个blog 一个trojanweb , 互不冲突. 两个网站在宝塔中 配置都是独立的. 不会访问2个域名都跳到blog. 宝塔可以部署多个证书 根据域名不同 建不同的网站配置
> > 如果只建一个网站肯定是2个域名首页 都是进入blog了 要通过url区分 就是上面的nginx 配置放到宝塔的网站的nginx配置里面 编辑
> > trojanweb 会运行到一个端口上 查看一下trojanweb运行的端口 反代到这个端口号就行, 就是上面的nginx 26687 改个端口号 默认是81
> > https://github.com/Jrohy/trojan/wiki/nginx%E9%85%8D%E7%BD%AE
> > https://github.com/Jrohy/trojan/wiki/%E4%BF%AE%E6%94%B9web%E7%AB%AF%E5%8F%A3
> 
> 我按照https://github.com/Jrohy/trojan/wiki/nginx%E9%85%8D%E7%BD%AE 所述 将端口和网址都改好了，trojan的端口也改好了，但是访问的时候却显示： 当前无法使用此页面 重定向次数过多

这样写的，直接加在了nginx配置文件都是location的地方：
`
location / 
    {
            proxy_pass   http://127.0.0.1:13568/;
    }
    location ~* ^/(static|common|auth|trojan)/ 
    {
            proxy_pass  http://127.0.0.1:13568;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
    }
        # http强制跳转到https
        if ( $remote_addr != 127.0.0.1 ){
            rewrite ^/(.*)$ https://xxx.xx/$1 redirect;
        }
`

**Comment by jinwyp** [comment]
不清楚 

建议 在宝塔里面  把trojan-web单独做一个 域名 
配置 把 http强制跳转到https 下面删了试试

宝塔还有很多自己nginx配置 可以删除试试

**Comment by Swor-dart** [comment]
> 不清楚
> 
> 建议 在宝塔里面 把trojan-web单独做一个 域名 配置 把 http强制跳转到https 下面删了试试
> 
> 宝塔还有很多自己nginx配置 可以删除试试

我试了很久最终没有报错的界面是：（强制https代码删了）
```
恭喜, 站点创建成功！
这是默认index.html，本页面由系统自动生成
本页面在FTP根目录下的index.html
您可以修改、删除或覆盖本页面
FTP相关信息，请到“面板系统后台 > FTP” 查看
```
宝塔的默认index.html，端口反代貌似没效果？

**Comment by jinwyp** [comment]
> > 不清楚
> > 建议 在宝塔里面 把trojan-web单独做一个 域名 配置 把 http强制跳转到https 下面删了试试
> > 宝塔还有很多自己nginx配置 可以删除试试
> 
> 我试了很久最终没有报错的界面是：（强制https代码删了）
> 
> ```
> 恭喜, 站点创建成功！
> 这是默认index.html，本页面由系统自动生成
> 本页面在FTP根目录下的index.html
> 您可以修改、删除或覆盖本页面
> FTP相关信息，请到“面板系统后台 > FTP” 查看
> ```
> 
> 宝塔的默认index.html，端口反代貌似没效果？

自己多研究一下 nginx 配置文档 把每一行什么意思 都搞清楚. 
在宝塔里面新建一个静态网站 做实验 学习如何反代网站
