### ISSUE TITLE
正常使用trojan-go 1天后日志报错：tls handshake failed

### ISSUE THREAD

**Issue by mydhui** [jinwyp/one_click_script#182]
1. 选择的第3项 安装trojan-go 和 nginx

- OS: AlmLinux 
- Version 8
- Terminal :  Mac的terminal ssh 到VPS 
- VPS: RackNerd

Log Info 日志信息： 

![image](https://user-images.githubusercontent.com/35788289/194741503-1cdae161-f0c7-4b47-b761-693fe6f814cc.png)

配置好了以后1天后出现的这个问题，小火箭延迟2200+ms, 或者显示超时
已经设置了北京时间，trojan-go运行在886端口，非443
nginx启动成功, trojan-go status 也是running
大佬看一下是什么问题，是886端口被封了吗？

**Comment by mydhui** [comment]
![image](https://user-images.githubusercontent.com/35788289/194742914-1e2fcc97-e16a-49e0-9ab1-729d9f277f49.png)
请问这个情况国外都能ping通国内ping不通，说明886端口在国内被封了吗？

**Comment by jinwyp** [comment]
对啊 被封了.

昨日我已经把 trojan-go 换成了 另外一个, 原来的trojan-go很长时间没更新了.
https://github.com/fregie/trojan-go


你可以重新卸载后 选2重新安装试试

**Comment by mydhui** [comment]
> 对啊 被封了.
> 
> 昨日我已经把 trojan-go 换成了 另外一个, 原来的trojan-go很长时间没更新了. https://github.com/fregie/trojan-go
> 
> 你可以重新卸载后 选2重新安装试试

谢谢，卸载后选了2，并且重新安装证书以后，可以了。
想问一下，用了1天就被封了这个事情是因为原来的trojan-go版本较老吗？还是的VPS的ip或port的原因？之后怎么能用长久一点

**Comment by jinwyp** [comment]
> 

换VPS服务商,现在都是AI识别流量,  没法长久用了,  换大的VPS服务商 例如微软azure 或亚马逊aws, 这种IP段 不会被封.
