### ISSUE TITLE
Trojan-go使用一段时间会断流

### ISSUE THREAD

**Issue by mianmianmi** [jinwyp/one_click_script#184]
用几天之后，就连不上了，无法上网，本以为是443端口被封，然后分别在国内、国外服务器上telnet 443端口，发现都不通，但443端口仍有不少连接（据观察连接情况不怎么变化，一直是那些IP，对应的连接数也不变化），trojan-go重启之后恢复正常。后来关闭MUX，还是使用一段时间后就无法连接了。以前用Trojan开几个月都没有问题，最近服务器重装，才发现你们脚本里面本来有的Trojan安装都更新为了Trojan-go。但是安装了Trojan-go之后一直非常的不稳定。希望可以解决。或者恢复以前脚本里面选择Trojan的安装。个人感觉确实Trojan比Trojan-go稳定。

**Comment by jinwyp** [comment]
都是什么时期了 多看看新闻 换VPS运营商. 和trojan trojan-go没有关系 多用ping.pe 测试.

**Comment by jinwyp** [comment]
更新了脚本 增加原版trojan 和 其他改版trojan-go
