### ISSUE TITLE
新脚本没有升级Trojan-go到最新版本的选项

### ISSUE THREAD

**Issue by soundghost** [jinwyp/one_click_script#185]
我看到4小时前脚本有更新，trojan-go的版本从0.10.5改到了最新版本0.10.6，但是在更新完脚本后发现菜单里没有升级trojan-go到最新版本的选项了。

谢谢你提供的脚本。

**Comment by jinwyp** [comment]
trojan-go 早就不更新了

**Comment by soundghost** [comment]
4小时前的从0.10.5改动到0.10.6不是你做的啊？
出现了灵异事件了……

还是要表示感谢。那我重新装一遍吧。

**Comment by jinwyp** [comment]
> 4小时前的从0.10.5改动到0.10.6不是你做的啊？ 出现了灵异事件了……
> 
> 还是要表示感谢。那我重新装一遍吧。

是我改的， 但那个不影响， 因为程序或获取最新版本， 就是说你以前装的一直是0.10.6版本 根本不会安装老板本。 trojan-go已经很长时间没有更新了
