### ISSUE TITLE
选择第22项 安装 trojan-go 和 v2ray，安装完成后域名https打不开，trojan和v2ray都不能正常使用

### ISSUE THREAD

**Issue by uioty** [jinwyp/one_click_script#186]
./trojan_v2ray_install.sh
选择第22项 安装trojan 和 v2ray，安装完成后域名https打不开，trojan和v2ray也都不能正常使用。

- OS: [Centos]
- Version [8]
- Terminal :  FinalShell
- VPS  [Oracle Cloud]

**To Reproduce** 复现方法  

Log Info 日志信息：
[root@centos8-20221025-1304 ~]# journalctl -n 50 -u nginx.service
-- Logs begin at Tue 2022-10-25 06:22:13 GMT, end at Tue 2022-10-25 07:11:47 GMT. --
10月 25 06:42:47 centos8-20221025-1304 systemd[1]: nginx.service: Unit cannot be reloaded because it is inactive.
10月 25 06:43:17 centos8-20221025-1304 systemd[1]: Starting The nginx HTTP and reverse proxy server...
10月 25 06:43:17 centos8-20221025-1304 nginx[63536]: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
10月 25 06:43:17 centos8-20221025-1304 nginx[63536]: nginx: configuration file /etc/nginx/nginx.conf test is successful
10月 25 06:43:17 centos8-20221025-1304 systemd[1]: Started The nginx HTTP and reverse proxy server.

[root@centos8-20221025-1304 ~]# journalctl -n 50 -u v2ray.service
-- Logs begin at Tue 2022-10-25 06:22:13 GMT, end at Tue 2022-10-25 07:13:19 GMT. --
10月 25 06:44:01 centos8-20221025-1304 systemd[1]: Started V2Ray.
10月 25 06:44:01 centos8-20221025-1304 v2ray[65384]: V2Ray 4.45.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.18.3 linux/amd64)
10月 25 06:44:01 centos8-20221025-1304 v2ray[65384]: A unified platform for anti-censorship.
10月 25 06:44:01 centos8-20221025-1304 v2ray[65384]: 2022/10/25 06:44:01 [Info] main/jsonem: Reading config: /root/v2ray/config.json

安装完成nginx 显示安装成功，过程中没看出有什么错误提示，但域名的网站用https不能正常打开，http可以正常打开，nginx安装时输出日志如下：
 ================================================== 
       Web服务器 nginx 安装成功!!
    伪装站点为 *************（隐去站点域名）
    伪装站点的静态html内容放置在目录 /nginxweb/html, 可自行更换网站内容!
    nginx 配置路径 /etc/nginx/nginx.conf 
    nginx 访问日志 /nginxweb/nginx-access.log 
    nginx 错误日志 /nginxweb/nginx-error.log 
    nginx 查看日志命令: journalctl -n 50 -u nginx.service
    nginx 启动命令: systemctl start nginx.service  停止命令: systemctl stop nginx.service  重启命令: systemctl restart nginx.service
    nginx 查看运行状态命令: systemctl status nginx.service 
 ==================================================

**Comment by jinwyp** [comment]
选择 22 是trojan-go 在前面提供443 服务 看一下 trojan-go 运行是否正常
运行 systemctl status trojan-go  和 
 journalctl -n 50 -u trojan-go

**Comment by uioty** [comment]
[root@centos8-20221025-1304 ~]# mv /root/trojan-go-fork /root/trojan-go
mv: 无法获取'/root/trojan-go-fork' 的文件状态(stat): No such file or directory
[root@centos8-20221025-1304 ~]# systemctl restart trojan-go
[root@centos8-20221025-1304 ~]# journalctl -n 50 -u trojan-go
-- Logs begin at Tue 2022-10-25 15:22:53 GMT, end at Wed 2022-10-26 03:27:46 GMT. --
10月 26 03:26:31 centos8-20221025-1304 systemd[1]: Stopped trojan-go.
10月 26 03:26:31 centos8-20221025-1304 systemd[1]: Started trojan-go.
10月 26 03:26:31 centos8-20221025-1304 systemd[1]: trojan-go.service: Main process exited, code=exited, status=203/EXEC
10月 26 03:26:31 centos8-20221025-1304 systemd[1]: trojan-go.service: Failed with result 'exit-code'.
10月 26 03:26:41 centos8-20221025-1304 systemd[1]: trojan-go.service: Service RestartSec=10s expired, scheduling restart.
10月 26 03:26:41 centos8-20221025-1304 systemd[1]: trojan-go.service: Scheduled restart job, restart counter is at 7276.
10月 26 03:26:41 centos8-20221025-1304 systemd[1]: Stopped trojan-go.
10月 26 03:26:41 centos8-20221025-1304 systemd[1]: Started trojan-go.
10月 26 03:26:41 centos8-20221025-1304 systemd[1]: trojan-go.service: Main process exited, code=exited, status=203/EXEC
10月 26 03:26:41 centos8-20221025-1304 systemd[1]: trojan-go.service: Failed with result 'exit-code'.
10月 26 03:26:51 centos8-20221025-1304 systemd[1]: trojan-go.service: Service RestartSec=10s expired, scheduling restart.
10月 26 03:26:51 centos8-20221025-1304 systemd[1]: trojan-go.service: Scheduled restart job, restart counter is at 7277.
10月 26 03:26:51 centos8-20221025-1304 systemd[1]: Stopped trojan-go.
10月 26 03:26:51 centos8-20221025-1304 systemd[1]: Started trojan-go.
10月 26 03:26:51 centos8-20221025-1304 systemd[1]: trojan-go.service: Main process exited, code=exited, status=203/EXEC
10月 26 03:26:51 centos8-20221025-1304 systemd[1]: trojan-go.service: Failed with result 'exit-code'.
10月 26 03:27:02 centos8-20221025-1304 systemd[1]: trojan-go.service: Service RestartSec=10s expired, scheduling restart.
10月 26 03:27:02 centos8-20221025-1304 systemd[1]: trojan-go.service: Scheduled restart job, restart counter is at 7278.
10月 26 03:27:02 centos8-20221025-1304 systemd[1]: Stopped trojan-go.
10月 26 03:27:02 centos8-20221025-1304 systemd[1]: Started trojan-go.
10月 26 03:27:02 centos8-20221025-1304 systemd[1]: trojan-go.service: Main process exited, code=exited, status=203/EXEC
10月 26 03:27:02 centos8-20221025-1304 systemd[1]: trojan-go.service: Failed with result 'exit-code'.
10月 26 03:27:12 centos8-20221025-1304 systemd[1]: trojan-go.service: Service RestartSec=10s expired, scheduling restart.
10月 26 03:27:12 centos8-20221025-1304 systemd[1]: trojan-go.service: Scheduled restart job, restart counter is at 7279.
lines 1-25

**Comment by jinwyp** [comment]
trojan-go 没运行 卸载重新安装试试， 是不是有端口占用
systemctl status trojan-go 看看什么问题

**Comment by uioty** [comment]
[root@centos8-20221025-1304 ~]# systemctl status trojan-go
● trojan-go.service - trojan-go
   Loaded: loaded (/usr/lib/systemd/system/trojan-go.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2022-10-26 06:11:29 GMT; 7s ago
  Process: 722233 ExecStart=/root/trojan-go/trojan-go -config /root/trojan-go/server.json (code=exited, status=203/EXEC)
 Main PID: 722233 (code=exited, status=203/EXEC)

试过卸载重装，依旧，装完域名https打不开。安装的时候没有提示端口被占用，尝试过更换443端口安装，依旧不行。
今年8月份时同样选的22安装没这些问题，装完可以立即正常使用，不知这两个月发生了什么。。。

**Comment by jinwyp** [comment]
只有用了443端口才可以访问https, 用了其他端口网站就不是443了, 443端口是否被封 用http://ping.pe/ 测试一下 是否被封了
