### ISSUE TITLE
求助，app的选择

### ISSUE THREAD

**Issue by Jacky-Bruse** [jinwyp/one_click_script#187]
你好，请问搭建了修改版加入浏览器指纹的trojan-go，那么我的客户端是直接用v2rayNG可以吗？或者需要专用客户端？一直没理解，请赐教

**Comment by jinwyp** [comment]
可以
但加入指纹实际是客户端, 就是服务器端设置后客户端也要用指纹,否则还是没有发出指纹

**Comment by Jacky-Bruse** [comment]
那现在这个有对应客户端吗，求教？

**Comment by jinwyp** [comment]
> 那现在这个有对应客户端吗，求教？

暂时用PC的v2rayN就行 , 

是需要没有发出指纹的客户端或发出模拟浏览器指纹的客户端, 但实际也不会安全多少
