### ISSUE TITLE
对于提示   关闭防火墙 firewalld

### ISSUE THREAD

**Issue by mn3711698** [jinwyp/one_click_script#188]
安装11使用正常。但看到关闭防火墙 firewalld，不知道有没有办法不关闭防火墙，因为服务器里边还有其他的业务，比如数据库，web项目，防火墙关了怕怕

**Comment by mn3711698** [comment]
rocky 9系统

**Comment by jinwyp** [comment]
安装完自己手动开启 并开启相应端口
