### ISSUE TITLE
trojango第二天后无法使用

### ISSUE THREAD

**Issue by super766** [jinwyp/one_click_script#189]
centos7安装trojan go。选的是第2项
第一天没问题，第二天突然连不上了。于是第二天重装v2ray和trojan也连不上
伪装的网页也访问不了
VPS是vmiss
域名解析没问题，IP没有被墙
测试服务器状态v2rayN 控制台打印：
当前服务的真连接延迟: -1 ms（ip和域名我改过了不是真实的）
2022/10/30 17:08:04 [Warning] [1290651336] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://super.one/d471261b):  > dial tcp 20.47.103.90:443: i/o timeout transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://super.one/d471261b):  > dial tcp 20.47.103.90:443: operation was canceled transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://super.one/d471261b):  > dial tcp: operation was canceled] > common/retry: all retry attempts failed

**Comment by jinwyp** [comment]
在服务器上运行 systemctl status trojan-go 查看运行状态

运行 systemctl status nginx 查看网页运行状态

不行就卸载重装。 

用 https://ping.pe/  测试是否被封

**Comment by super766** [comment]
k

**Comment by super766** [comment]
看了下好像是我开的端口被封了，但是IP没被封，只有国内访问不了，请问这种问题怎么解决。不可能每天开个重装开个新端口吧？
还有就是v2ray和trojan哪个更不容易被封

**Comment by jinwyp** [comment]
用CDN ， 或者换VPS运营商，现在GFW已经是AI识别 不存在不封的情况了
