### ISSUE TITLE
Trojan卸载后再次安装出现trojan.service权限错误

### ISSUE THREAD

**Issue by CarlaRadames** [jinwyp/one_click_script#191]
Trojan成功安装后卸载，第二次安装会出现权限错误导致无法启动
`root@lucid-cube-1.localdomain:/root # systemctl status trojan-go.servicesystemctl status trojan-go.service
Unit trojan-go.servicesystemctl.service could not be found.
Unit status.service could not be found.
● trojan-go.service - trojan-go
     Loaded: loaded (/lib/systemd/system/trojan-go.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Fri 2022-11-04 03:38:00 CST; 9s >
    Process: 3282 ExecStart=/root/trojan-go/trojan-go -config /root/trojan-go/server.json (code=e>
   Main PID: 3282 (code=exited, status=1/FAILURE)
        CPU: 17ms`

可参考另外一个脚本的issue：https://github.com/p4gefau1t/trojan-go/issues/451

1. 例如选择的第2项 安装trojan
2. 选择4，卸载但保留Nginx
3. 选择3，重新安装trojan

**OS and Terminal:**  系统环境 信息 请务必提供什么操作系统 和用的什么终端 ，还有VPS主机商

- OS: Debian
- Version 10
- Terminal :  Electerm
- VPS  Bandwagon

**Comment by jinwyp** [comment]
卸载后 重新运行脚本， 更新脚本 ， 重新安装一下

你选的是哪种trojan安装的？
 1 原版 Trojan 不支持 websocket (not support websocket)
 2 原版 Trojan-go 支持 websocket (support websocket)
 3 修改版 Trojan-go 支持 websocket by fregie (support websocket)
 4 修改版 Trojan-go 支持模拟浏览器指纹 支持 websocket by Potterli20 (support websocket)

**Comment by jy569569** [comment]
最新脚本安装3和4都是这个问题，怎么解决？

**Comment by jinwyp** [comment]
已修复 建议每次全部卸载在安装
