### ISSUE TITLE
正常安装13号选项后，不能正常连接。只有v2ray-error.log日志有内容

### ISSUE THREAD

**Issue by Sayid1** [jinwyp/one_click_script#192]
1. 安装的第13项 安装前已使用第44项设置为北京时间

**OS and Terminal:** 

- OS: AlmaLinux OS 8 64 Bit
- Terminal :  Mac的teminal
- VPS : RackNerd

**To Reproduce** 复现方法  
按照第13项一直下一步下一步，没有安装nginx。
安装正常，但是安装后不能正常连接

# 安装步骤截图
13. 安装 v2ray或xray (VLess-TCP-[TLS/XTLS])+(VMess-TCP-TLS)+(VMess-WS-TLS) 支持CDN, 可选安装nginx, VLess运行在443端口
<img width="359" alt="image" src="https://user-images.githubusercontent.com/29008437/201377297-d89c0d4d-51cd-4149-997a-98ca8a3abb88.png">

<img width="587" alt="image" src="https://user-images.githubusercontent.com/29008437/201377920-949164d4-2b01-413c-bd2b-3b25b811c5ee.png">

<img width="786" alt="image" src="https://user-images.githubusercontent.com/29008437/201378051-f67e2f3b-2f27-4835-804f-f887044af0ad.png">

<img width="591" alt="image" src="https://user-images.githubusercontent.com/29008437/201378382-0a44b26f-d608-4028-badc-f72b5c48984e.png">

# systemctl status v2ray.service 运行截图
<img width="985" alt="image" src="https://user-images.githubusercontent.com/29008437/201378596-e0e75ff9-92db-4dd9-b5de-37587dacddf0.png">

# /root/v2ray-error.log 错误日志
<img width="999" alt="image" src="https://user-images.githubusercontent.com/29008437/201379273-051d37a4-d70c-4843-ab74-edb137b30f41.png">

**Comment by jinwyp** [comment]
使用 https://ping.pe/ 查看端口是否被封，
1 更换端口
2 更换VPS 主机商
3 重启光猫

现在防火墙是AI识别， 连不上就是检测端口或还是直接IP被封了
