### ISSUE TITLE
生成的V2ray客户端配置参数内容不全(缺少地址);同时导入链接也不包含地址信息

### ISSUE THREAD

**Issue by TinaryTree** [jinwyp/one_click_script#193]
手动在客户端添加服务器地址也无法连接

**Comment by jinwyp** [comment]
你复制错了导入连接, VMESS和Vless是不一样的格式, 如果是Vmess需要复制base64格式的那行

你贴一下安装后的信息, 看看是不是复制错行了

**Comment by jinwyp** [comment]
你选的第几项安装的啊, 地址就是你的域名啊

**Comment by TinaryTree** [comment]
我知道地址是我的域名，但是我现在无论选哪项最后生成的v2Ray配置都没有地址，而且我不确定是不是还少其他信息导致我客户端连不上服务器，不知道是不是脚本生成配置有bug导致的

**Comment by jinwyp** [comment]
> 我知道地址是我的域名，但是我现在无论选哪项最后生成的v2Ray配置都没有地址，而且我不确定是不是还少其他信息导致我客户端连不上服务器，不知道是不是脚本生成配置有bug导致的

你选的第几项安装的啊？感觉安装过程中出问题了才会无法显示地址

**Comment by TinaryTree** [comment]
不好意思不太记得了，我换了个别的脚本搞好了，如果你那边回归测试没问题的话，那可能是我的问题，懒得复现了。
