### ISSUE TITLE
UDP提示UdpBlocked

### ISSUE THREAD

**Issue by lingaoyi** [jinwyp/one_click_script#194]
2. 安装 trojan/trojan-go 和 nginx, 支持CDN 开启websocket, trojan-go 运行在443端口

**OS and Terminal:**  系统环境 信息 请务必提供什么操作系统 和用的什么终端 ，还有VPS主机商

- OS: Debian 11
- Terminal :  Termius
- 供应商：Linode

**To Reproduce** 复现方法  

为什么我开启UDP时候，用NatTypeTester测试，UDP提示是：UdpBlocked，关闭了代理之后就是FullCone，这个能解决吗？我换了几台机器，安装你们脚本就是UdpBlocked

**Comment by jinwyp** [comment]
trojan / trojan-go 对UDP 支持不好，因为trojan是TCP， 支不支持 UDP over TCP 要看一下官方文档
 建议换xray.
