### ISSUE TITLE
脚本需要加一行yum -y install unzip

### ISSUE THREAD

**Issue by shengxu99** [jinwyp/one_click_script#195]
否则没unzip的机器安装trojan-go容易安个寂寞

**Comment by shengxu99** [comment]
仔细看了一下脚本，似乎有相关功能？但当前版本在centos7下选2装trojan-go最终会因为无法解压服务端程序导致安装个寂寞。普通用户可以再运行脚本前yum -y install unzip。

**Comment by jinwyp** [comment]
已修改 增加了unzip的检测
