### ISSUE TITLE
求添加trojan的升级升级选项了 现在没有trojan和trojan-go的升级选项了 以前有来着

### ISSUE THREAD

**Issue by shinanzhuomo** [jinwyp/one_click_script#198]
求添加trojan的升级升级选项了 现在没有trojan和trojan-go的升级选项了 以前有来着

**Comment by jinwyp** [comment]
因为trojan和trojan-go已经2年没有更新了

**Comment by catch6** [comment]
> 因为trojan和trojan-go已经2年没有更新了

@jinwyp 现在推荐安装哪个呢？，服务器只有256M内存，trojan-go占内存低，目前用的这个，想体验shadowsocks-rust，但是有下面的错误

```sh
chmod: cannot access '/root/shadowsocksrust/ssserver': No such file or directory
```

**Comment by jinwyp** [comment]
ss 无论是哪个协议 秒封

推荐11开始的xray

**Comment by catch6** [comment]
> ss 无论是哪个协议 秒封
> 
> 推荐11开始的xray

好的
