### ISSUE TITLE
解锁流媒体的落地机设置好后，没有生效，请问在哪里可以手动自己再调整

### ISSUE THREAD

**Issue by issaceyan** [jinwyp/one_click_script#199]
<img width="689" alt="image" src="https://user-images.githubusercontent.com/61646916/206418530-f2f8ab7f-0cbc-48af-8af8-cde3a490776f.png">

**Comment by jinwyp** [comment]
自己编辑 /root/v2ray/config.json 配置文件

最近老姨子解锁挂了 就是使用脚本提供的神秘解锁挂了

**Comment by issaceyan** [comment]
> 自己编辑 /root/v2ray/config.json 配置文件
> 
> 最近老姨子解锁挂了 就是使用脚本提供的神秘解锁挂了

抱歉，root下面没有找到V2RAY的文件夹
<img width="451" alt="image" src="https://user-images.githubusercontent.com/61646916/206629029-19aafa27-bb5a-4c24-90f1-93dbe21c507c.png">

**Comment by jinwyp** [comment]
你没安装成功， 重新选24卸载后 在选11安装吧

**Comment by issaceyan** [comment]
已经中转成功，但是速度没有达到预期效果，两个小鸡的互相PING值都稳定在34MS左右，请问还有其他协议可以提速吗？

**Comment by jinwyp** [comment]
> 已经中转成功，但是速度没有达到预期效果，两个小鸡的互相PING值都稳定在34MS左右，请问还有其他协议可以提速吗？

速度和ping 值没有关系， 可以用iperf3来测速  

xtls 速度最快 其次是trojan-go 开启mux
