### ISSUE TITLE
脚本创建的配置文件格式似乎不再受支持

### ISSUE THREAD

**Issue by betaback** [jinwyp/one_click_script#2]
开发者您好，这应该是一个小问题，之前版本的trojan go似乎是支持conf格式的配置文件，今天突然用脚本装完不能用了，查看Trojan go错误日志，发现如下内容
[FATAL] 2020/06/12 15:46:06 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:30 unsupported filename suffix /root/trojan-go/src/server.conf . use .yaml or .json instead.
我是小白，不太懂，但应该是近期才不支持conf格式的，之前我也用的好好得

**Comment by jinwyp** [comment]
暂时只能用0.6的版本 0.7的版本bug太多了

**Comment by jinwyp** [comment]
已经更新到最新版本0.7.6的配置 你可以试试还有没有问题

**Comment by betaback** [comment]
没有问题了，可以正常使用，感谢
