### ISSUE TITLE
选择12安装导致原来的https网址无法访问

### ISSUE THREAD

**Issue by redstoneleo** [jinwyp/one_click_script#200]
`12. 只安装 v2ray或xray ([Vmess/Vless]-[TCP/WS/gRPC/H2/QUIC]), 无TLS加密, 方便与现有网站或宝塔面板集成`

选择12安装导致原来的https网址无法访问，选择3安装费443端口倒是可以

**Comment by jinwyp** [comment]
无法得知你原来的网站是什么情况，12只安装了xray/v2ray 可以卸载即可。请自行排查原因，运行systemctl status nginx 看看nginx是否正常 等
