### ISSUE TITLE
本项目提示原版trojan-go不支持utls

### ISSUE THREAD

**Issue by redstoneleo** [jinwyp/one_click_script#201]
本项目提示原版trojan-go不支持utls，但是现在已经正常了，请修正一下描述
https://github.com/p4gefau1t/trojan-go

**Comment by jinwyp** [comment]
trojan-go 最后更新是 Sep 14, 2021， 也没更新支持utls啊

**Comment by redstoneleo** [comment]
在这里面搜索utls你就知道了
https://github.com/p4gefau1t/trojan-go/blob/881182a143d1af4073de2dbd69331cff4ecd4243/docs/content/basic/full-config.md

**Comment by jinwyp** [comment]
https://github.com/gfw-report/trojan-go/releases
看一下这个项目 原版的trojan-go指纹太老了
