### ISSUE TITLE
v1.6.6/Xray-linux-64.zip 下载文件不存在, 已经改为 1.6.6-2

### ISSUE THREAD

**Issue by 0xuhe** [jinwyp/one_click_script#202]
===== 下载并解压zip文件:  Xray-linux-64.zip
--2022-12-13 21:22:43--  https://github.com/XTLS/Xray-core/releases/download/v1.6.6/Xray-linux-64.zip
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-12-13 21:22:43 ERROR 404: Not Found.

**Comment by jinwyp** [comment]
官方没有按照规则发布版本号 等新的1.6.7发布就可以了
