### ISSUE TITLE
无法成功启动xray，code=exited, status=203/EXEC

### ISSUE THREAD

**Issue by THLarge** [jinwyp/one_click_script#203]
安装任意选项的xray，无法成功启动xray
查看xray进程状态显示：
xray.service - Xray
   Loaded: loaded (/lib/systemd/system/xray.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2022-12-16 16:36:39 CST; 7s ago
     Docs: https://xtls.github.io/
  Process: 5371 ExecStart=/root/v2ray/xray run -config /root/v2ray/config.json (code=exited, status=203/EXEC)
 Main PID: 5371 (code=exited, status=203/EXEC)

Dec 16 16:36:39 FrozenPlaintive-VM systemd[1]: xray.service: Main process exited, code=exited, status=203/EXEC
Dec 16 16:36:39 FrozenPlaintive-VM systemd[1]: xray.service: Failed with result 'exit-code'.
Dec 16 16:36:39 FrozenPlaintive-VM systemd[1]: xray.service: Service RestartSec=100ms expired, scheduling restart.
Dec 16 16:36:39 FrozenPlaintive-VM systemd[1]: xray.service: Scheduled restart job, restart counter is at 5.
Dec 16 16:36:39 FrozenPlaintive-VM systemd[1]: Stopped Xray.
Dec 16 16:36:39 FrozenPlaintive-VM systemd[1]: xray.service: Start request repeated too quickly.
Dec 16 16:36:39 FrozenPlaintive-VM systemd[1]: xray.service: Failed with result 'exit-code'.
Dec 16 16:36:39 FrozenPlaintive-VM systemd[1]: Failed to start Xray.

**Comment by msshn** [comment]
I have the same issue. Looks like the download link for v2ray in the script is broken.
