### ISSUE TITLE
Ubuntu 20.04 内核安装以及优化网络配置

### ISSUE THREAD

**Issue by bcseputetto** [jinwyp/one_click_script#205]
![ubuntu_kernel_install_grub](https://user-images.githubusercontent.com/29139573/209503088-45bd5c46-5fee-4ab0-951f-08fbb7ff9cd9.png)
我这台日本的IPv4+IPv6双栈的VPS，用的服务商提供的Ubuntu 20.04，带内核5.4.0-125和5.4.0-135，使用46，安装5.10 LTS是失败的，没有安装上，而且重启之后也无法正常启动，VNC里面启动报错我忘记留截图了，使用66安装bbrplus 5.10内核虽然可以安装上，但不像上图那样操作，VNC里看就会卡在grub引导，输入update-grub 提示我找不到该命令，然后推荐安装grub2-common，然后我就照它说的安装了，然后执行了update-grub，update-grub2之后，再手动reboot，就可以了。
![ubuntu_kernel_install_grub2](https://user-images.githubusercontent.com/29139573/209503511-e7381d3b-83e2-4fc3-a7fe-4c7c10850dcf.png)

然后是优化系统网络配置
![network](https://user-images.githubusercontent.com/29139573/209503623-c0d2a7ca-b452-4a72-8b0c-27feb497201a.png)
如果使用了优化系统网络配置就会导致VPS很难访问外部网络
我curl google.com 都会一下成功，一下失败
![network2](https://user-images.githubusercontent.com/29139573/209503740-0e47fcd7-13fd-4ff3-a52f-82c32c997008.png)
使用脚本 bash <(curl -Lso- https://git.io/kernel.sh)
更是直接没有反应退出了，多试几次可能会成功，但这个网络真的很不正常，会出现各种问题，要么是无法解析域名，要么是80/443端口连接超时
![network3](https://user-images.githubusercontent.com/29139573/209504138-28e5dfa6-52e3-4b7e-bfaf-dcf1a9728d03.png)
只要删除 系统网络优化配置 并重启，这些现象都没了。

**Comment by jinwyp** [comment]
哪家的VPS? KVM架构吗? 不支持openvz

**Comment by bcseputetto** [comment]
> 哪家的VPS? KVM架构吗? 不支持openvz

KVM，非openvz，比较难买的日本的 sakura internet
![KVM](https://user-images.githubusercontent.com/29139573/209913367-de4e4ae2-a75b-409c-9cc7-24b278ff6289.png)
