### ISSUE TITLE
大神，能不能出个快捷脚本，例如输入oneclick就自动运行安装脚本

### ISSUE THREAD

**Issue by Jasonzhang2023** [jinwyp/one_click_script#206]
因为每次都要进入大佬主页，复制curl -O https://raw.githubusercontent.com/jinwyp/one_click_script/master/trojan_v2ray_install.sh && chmod +x ./trojan_v2ray_install.sh && ./trojan_v2ray_install.sh这一串代码。
大佬能不能出个快捷命令，例如输入oneclick就自动运行以上代码？谢谢

**Comment by jinwyp** [comment]
第一次运行后 再次运行 在 /root 目录 直接输入
··· ./trojan_v2ray_install.sh
···

**Comment by Jasonzhang2023** [comment]
谢谢大神！
