### ISSUE TITLE
where us ui panel?

### ISSUE THREAD

**Issue by AkramiPro** [jinwyp/one_click_script#208]
i use this command:
`bash <(curl -Lso- https://git.io/oneclick)`

then enter 22:
` 22. Install both v2ray/xray and trojan-go with nginx, (VLess/Vmess-WS-TLS)+Trojan, support CDN, trojan-go running at 443 port serve TLS`

after install is compete i cant find any admin ui . 
how i can manage v2ay and trojan in admin panel ui ?

**Comment by jinwyp** [comment]
no UI panel for 22
