### ISSUE TITLE
404 not found : Install BBR Plus kernel 5.15 LTS, compile by UJX6N

### ISSUE THREAD

**Issue by AkramiPro** [jinwyp/one_click_script#209]
1. bash <(curl -Lso- https://git.io/kernel.sh)
2. 67

**OS and Terminal:** 

- OS: centos
- Version 7
- Terminal :  ssh
- VPS  hetzner

`/root/download_linux_kernel/5.15.86-bbrplus/CentOS-7_Optional_kernel-bbrplus-headers-5.15.86-1.bbrplus.el7.x86_64.rpm
文件下载中... 下载地址: https://github.com/UJX6N/bbrplus-5.15/releases/download/5.15.86-bbrplus/CentOS-7_Optional_kernel-bbrplus-headers-5.15.86-1.bbrplus.el7.x86_64.rpm
--2023-01-14 16:02:54--  https://github.com/UJX6N/bbrplus-5.15/releases/download/5.15.86-bbrplus/CentOS-7_Optional_kernel-bbrplus-headers-5.15.86-1.bbrplus.el7.x86_64.rpm
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-01-14 16:02:55 ERROR 404: Not Found.`

![image](https://user-images.githubusercontent.com/54323929/212482070-905101ab-6827-413a-af8d-16e15f0eb534.png)

**Comment by jinwyp** [comment]
已修复 感谢反馈
