### ISSUE TITLE
现在的v2 core直接支持trojan。大佬研究下？

### ISSUE THREAD

**Issue by DLGum** [jinwyp/one_click_script#21]
看那个范例配置可以一个core各种套娃。
我尝试折腾了下没搞通。

**Comment by jinwyp** [comment]
哪个连接 ？

是这个吗？
https://github.com/v2fly/v2ray-examples/blob/master/Trojan-TCP-TLS%20(minimal)/config_server.json

**Comment by jinwyp** [comment]
已增加各种v2ray vless作为前端的配置 选择29后即可 根据菜单安装
