### ISSUE TITLE
大神，最近撸到了甲骨文arm机器，有时间有心情的话，能帮忙出个arm机器的一键脚本吗？

### ISSUE THREAD

**Issue by Jasonzhang2023** [jinwyp/one_click_script#210]
使用现有一键安装脚本，大部分会报错，删机再重建（那天运气好，删机再重建无限制，甲骨文韩国首尔ARM4核24G内存机器一台重复开了8次。目前是选用30再选1安装trojan-go，这个版本也是我个人认为最为稳定的协议，即使在20big也是非常稳定）。

大神有空的时候，及心情好的时候，能否帮忙陆续更新适配arm版本的脚本？

**Comment by jinwyp** [comment]
脚本是支持 arm的, 但你选的那个trojan web UI 不支持 arm  

具体可以看他的那个项目 
https://github.com/Jrohy/trojan

**Comment by Jasonzhang2023** [comment]
谢谢大神！
