### ISSUE TITLE
使用脚本安装v2ray后启动服务报错

### ISSUE THREAD

**Issue by doahuw** [jinwyp/one_click_script#217]
**Describe the bug** A clear and concise description of what the bug is.
在提出问题前请先自行排除服务器端问题和升级到最新客户端，同时也请通过搜索确认是否有人提出过相同问题。

!!! 请务必提供安装的选择的第几项 !!!
!!! 请务必提供什么操作系统 和用的什么终端 !!!

1. 选的第十一项 安装 v2ray或xray 和 nginx ([Vmess/Vless]-[TCP/WS/gRPC/H2/QUIC]-TLS), 支持CDN, nginx 运行在443端口

**OS and Terminal:**  系统环境 信息 请务必提供什么操作系统 和用的什么终端 ，还有VPS主机商

- OS: Ubuntu
- Version 20.04.1 x86_64
- Terminal :  XShell
- VPS  MS Azure

脚本执行完之后v2ray服务没有启动，报错信息如下，nginx正常
root@pp88:/home/azureuser# journalctl -n 50 -u v2ray.service
-- Logs begin at Sat 2023-02-11 16:01:33 CST, end at Sat 2023-02-11 18:30:40 CST. --
Feb 11 18:21:24 pp88 systemd[1]: v2ray.service: Main process exited, code=exited, status=203/EXEC
Feb 11 18:21:24 pp88 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Feb 11 18:21:24 pp88 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 4.
Feb 11 18:21:24 pp88 systemd[1]: Stopped V2Ray.
Feb 11 18:21:24 pp88 systemd[1]: Started V2Ray.
Feb 11 18:21:24 pp88 systemd[17107]: v2ray.service: Failed to execute command: No such file or directory
Feb 11 18:21:24 pp88 systemd[17107]: v2ray.service: Failed at step EXEC spawning /root/v2ray/v2ray: No such file or directory
Feb 11 18:21:24 pp88 systemd[1]: v2ray.service: Main process exited, code=exited, status=203/EXEC
Feb 11 18:21:24 pp88 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Feb 11 18:21:25 pp88 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
Feb 11 18:21:25 pp88 systemd[1]: Stopped V2Ray.
Feb 11 18:21:25 pp88 systemd[1]: v2ray.service: Start request repeated too quickly.
Feb 11 18:21:25 pp88 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Feb 11 18:21:25 pp88 systemd[1]: Failed to start V2Ray.
Feb 11 18:21:38 pp88 systemd[1]: Started V2Ray.
Feb 11 18:21:38 pp88 systemd[17110]: v2ray.service: Failed to execute command: No such file or directory
Feb 11 18:21:38 pp88 systemd[17110]: v2ray.service: Failed at step EXEC spawning /root/v2ray/v2ray: No such file or directory
Feb 11 18:21:38 pp88 systemd[1]: v2ray.service: Main process exited, code=exited, status=203/EXEC
Feb 11 18:21:38 pp88 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Feb 11 18:21:38 pp88 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 1.
Feb 11 18:21:38 pp88 systemd[1]: Stopped V2Ray.
Feb 11 18:21:38 pp88 systemd[1]: Started V2Ray.
Feb 11 18:21:38 pp88 systemd[17111]: v2ray.service: Failed to execute command: No such file or directory
Feb 11 18:21:38 pp88 systemd[17111]: v2ray.service: Failed at step EXEC spawning /root/v2ray/v2ray: No such file or directory
Feb 11 18:21:38 pp88 systemd[1]: v2ray.service: Main process exited, code=exited, status=203/EXEC
Feb 11 18:21:38 pp88 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Feb 11 18:21:38 pp88 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 2.
Feb 11 18:21:38 pp88 systemd[1]: Stopped V2Ray.
Feb 11 18:21:38 pp88 systemd[1]: Started V2Ray.
Feb 11 18:21:38 pp88 systemd[17112]: v2ray.service: Failed to execute command: No such file or directory
Feb 11 18:21:38 pp88 systemd[17112]: v2ray.service: Failed at step EXEC spawning /root/v2ray/v2ray: No such file or directory
Feb 11 18:21:38 pp88 systemd[1]: v2ray.service: Main process exited, code=exited, status=203/EXEC
Feb 11 18:21:38 pp88 systemd[1]: v2ray.service: Failed with result 'exit-code'.
Feb 11 18:21:38 pp88 systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 3.
Feb 11 18:21:38 pp88 systemd[1]: Stopped V2Ray.
Feb 11 18:21:38 pp88 systemd[1]: Started V2Ray.
Feb 11 18:21:38 pp88 systemd[17113]: v2ray.service: Failed to execute command: No such file or directory
Feb 11 18:21:38 pp88 systemd[17113]: v2ray.service: Failed at step EXEC spawning /root/v2ray/v2ray: No such file or directory
Feb 11 18:21:38 pp88 systemd[1]: v2ray.service: Main process exited, code=exited, status=203/EXEC

**Comment by brezaie** [comment]
I am receiving the same error for trojan-go.

Here is the error:
Failed at step EXEC spawning /root/trojan-go/trojan-go: No such file or directory

**Comment by jinwyp** [comment]
Fix trojan-go bug.

选11 后 无论安装v2ray的4.45.2还是5.3版本都有没有问题 建议卸载后重新安装
