### ISSUE TITLE
新购VPS申请免费SSL证书连续失败

### ISSUE THREAD

**Issue by sunshinegdy** [jinwyp/one_click_script#219]
您好，使用过程中，遇到申请ssl证书失败，以及无法使用已经申请成功的证书的问题，谢谢。
测试步骤如下。
环境：Debian 11
服务商：vultr 未配置防火墙
域名托管：namesilo
未使用 cloudflare
测试时间：23-02-22 9:00-16:00 每个测试在不同时间重复至少2次。

测试1

1. 重装系统
2. 执行命令 netstat –pnltu》确认端口未占用
3. 执行脚本》2
4. 中间步骤》默认
5. 检测域名指向IP正确》成功
6. 申请证书》默认
7. 输入邮箱地址
8. 选择证书提供商》默认
9. 申请方式》默认
10. http申请方式》默认
11. 申请失败-time out-如图

<img width="944" alt="1" src="https://user-images.githubusercontent.com/10803130/220580835-8b604241-85f6-4a98-95a2-7a91cf79692d.png">

测试2 
reboot，执行脚本，重复测试1步骤，是否新增申请域名证书》1，其中步骤8.选择正式供应商时选择服务商2
申请失败-time out

测试3
reboot，执行脚本，重复测试1步骤，是否新增申请域名证书》1，之后其中8.选择正式供应商时选择服务商3
申请失败-time out

测试4
1. reboot
2. 执行脚本》2
3. 是否新增申请域名证书》1 新增申请域名证书
4. 证书路径》默认
5. 域名》正常填写
6. 检测指向IP》默认》成功
7. 是否申请证书》使用winscp将申请好的证书放入到指定文件夹》n
8. 失败-https证书没有申请成功
![image](https://user-images.githubusercontent.com/10803130/220578604-743cadd6-7dc1-41f7-a0c2-9857730f199e.png)

测试5
reboot，执行脚本
1. 是否新增申请域名证书》3 删除已申请域名证书
2. 选择域名
3. 删除成功
4. 脚本结束

**Comment by jinwyp** [comment]
图上写了错误原因 防火墙问题, 搞不明白的可以换centos 8

还有安装过程种 可以尝试换一个ssl 申请服务商 例如buypass
