### ISSUE TITLE
安装面板之后无法访问

### ISSUE THREAD

**Issue by steven12138** [jinwyp/one_click_script#22]
![image](https://user-images.githubusercontent.com/25414059/97649801-319fc100-1a93-11eb-866f-25dfe68bc55e.png)

安装29面板，然后访问的时候无法访问。
面板和伪装站点均无法访问

**Comment by jinwyp** [comment]
29选择后 进入第二个菜单后安装的是哪个面板啊？  v2ui 还是trojan-web

**Comment by steven12138** [comment]
trojan-web

**Comment by xulei890817** [comment]
> trojan-web

确实是trojan_web无法访问，我看了下log，应该是Nginx没有启动起来，需要用service nginx start 启动起来就行了

**Comment by jinwyp** [comment]
脚本里面是用 systemctl start nginx.service 启动的

**Comment by steven12138** [comment]
用的是
root@vultr:~# cat /etc/issue
Ubuntu 20.04.1 LTS \n \l

**Comment by steven12138** [comment]
不太好找原因，已经把机子重置了[捂脸]
