### ISSUE TITLE
Debian11安装vmess后无法启动

### ISSUE THREAD

**Issue by xlangzhong1** [jinwyp/one_click_script#221]
**Describe the bug** A clear and concise description of what the bug is.
在提出问题前请先自行排除服务器端问题和升级到最新客户端，同时也请通过搜索确认是否有人提出过相同问题。

!!! 请务必提供安装的选择的第几项 !!!
!!! 请务必提供什么操作系统 和用的什么终端 !!!

如题
Debian11，选择12安装vmess成功后无法启动
描述：按日志来说配置文件放置于 /root/v2ray/config.json ，但是从日志上看，xray的启动似乎要从/root/v2ray/xray里面出现，但是脚本并没有创建这个目录，所以出现日志当中的第一个错误，我使用mkdir创建xray目录并把执行文件拖进去，并修改777权限后出现第二个错误，提示访问受限，具体见脱敏日志，我尝试了一下，安装trojan后同样的问题，明明文件全部放在/root/trojan-go当中，日志却出现/root//trojan-go/trojan-go，目录不存在。
尝试解决：重装了系统，更换了IDC厂商，问题仍然存在
求助。下附日志（已脱敏

**Comment by xlangzhong1** [comment]
`
======================================================================
    Xray Version: 1.7.5 安装成功 !
    Xray 服务器端配置路径 /root/v2ray/config.json !
    Xray 访问日志 /root/v2ray-access.log !
    Xray 错误日志 /root/v2ray-error.log ! 
    Xray 查看日志命令: journalctl -n 50 -u xray.service 
    Xray 停止命令: systemctl stop xray.service  启动命令: systemctl start xray.service 
    Xray 重启命令: systemctl restart xray.service
    Xray 查看运行状态命令:  systemctl status xray.service 
    Xray 服务器 每天会自动重启, 防止内存泄漏. 运行 crontab -l 命令 查看定时重启命令 !
======================================================================

Xray 配置信息如下, 请自行复制保存, 密码任选其一 (密码即用户ID或UUID) !!


=========== Xray客户端配置参数 =============
{

}

导入链接 Vmess Base64 格式:
vmess:/
导入链接 Vless 格式:



======================================================================
请下载相应的 xray 客户端:
1 Windows 客户端V2rayN下载：http://dy6.jhxlz.eu.org/download/56cdd1f3c974fe5136bb/v2ray-windows.zip
2 MacOS 客户端下载：http://dy6.jhxlz.eu.org/download/56cdd1f3c974fe5136bb/v2ray-mac.zip
3 Android 客户端下载 https://github.com/2dust/v2rayNG/releases
4 iOS 客户端 请安装小火箭 https://shadowsockshelp.github.io/ios/ 
  iOS 请安装小火箭另一个地址 https://lueyingpro.github.io/shadowrocket/index.html 
  iOS 安装小火箭遇到问题 教程 https://github.com/shadowrocketHelp/help/ 
全平台客户端程序汇总 https://tlanyan.pp.ua/v2ray-clients-download/ 
其他客户端程序请看 https://www.v2fly.org/awesome/tools.html 
======================================================================
root@3:~# systemctl status xray.service
● xray.service - Xray
     Loaded: loaded (/lib/systemd/system/xray.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2023-03-04 01:58:36 CST; 34s ago
       Docs: https://xtls.github.io/
    Process: 14734 ExecStart=/root/v2ray/xray run -config /root/v2ray/config.json (code=exited, status=203/EXEC)
   Main PID: 14734 (code=exited, status=203/EXEC)
        CPU: 1ms

Mar 04 01:58:36 3 systemd[1]: xray.service: Scheduled restart job, restart counter is at 4.
Mar 04 01:58:36 3 systemd[1]: Stopped Xray.
Mar 04 01:58:36 3 systemd[1]: Started Xray.
Mar 04 01:58:36 3 systemd[1]: xray.service: Main process exited, code=exited, status=203/EXEC
Mar 04 01:58:36 3 systemd[1]: xray.service: Failed with result 'exit-code'.
Mar 04 01:58:36 3 systemd[1]: xray.service: Scheduled restart job, restart counter is at 5.
Mar 04 01:58:36 3 systemd[1]: Stopped Xray.
Mar 04 01:58:36 3 systemd[1]: xray.service: Start request repeated too quickly.
Mar 04 01:58:36 3 systemd[1]: xray.service: Failed with result 'exit-code'.
Mar 04 01:58:36 3 systemd[1]: Failed to start Xray.
root@3:~# journalctl -n 50 -u xray.service
-- Journal begins at Thu 2021-12-30 18:13:58 CST, ends at Sat 2023-03-04 01:59:18 CST. --
Mar 04 01:58:35 3 systemd[1]: Started Xray.
Mar 04 01:58:35 3 systemd[14652]: xray.service: Failed to locate executable /root/v2ray/xray: No such file or directory
Mar 04 01:58:35 3 systemd[14652]: xray.service: Failed at step EXEC spawning /root/v2ray/xray: No such file or directory
Mar 04 01:58:35 3 systemd[1]: xray.service: Main process exited, code=exited, status=203/EXEC
Mar 04 01:58:35 3 systemd[1]: xray.service: Failed with result 'exit-code'.
Mar 04 01:58:35 3 systemd[1]: xray.service: Scheduled restart job, restart counter is at 1.
Mar 04 01:58:35 3 systemd[1]: Stopped Xray.
Mar 04 01:58:35 3 systemd[1]: Started Xray.
Mar 04 01:58:35 3 systemd[1]: xray.service: Main process exited, code=exited, status=203/EXEC
Mar 04 01:58:35 3 systemd[1]: xray.service: Failed with result 'exit-code'.
Mar 04 01:58:36 3 systemd[1]: xray.service: Scheduled restart job, restart counter is at 2.
Mar 04 01:58:36 3 systemd[1]: Stopped Xray.
Mar 04 01:58:36 3 systemd[1]: Started Xray.
Mar 04 01:58:36 3 systemd[14732]: xray.service: Failed to locate executable /root/v2ray/xray: No such file or directory
Mar 04 01:58:36 3 systemd[14732]: xray.service: Failed at step EXEC spawning /root/v2ray/xray: No such file or directory
Mar 04 01:58:36 3 systemd[1]: xray.service: Main process exited, code=exited, status=203/EXEC
Mar 04 01:58:36 3 systemd[1]: xray.service: Failed with result 'exit-code'.
Mar 04 01:58:36 3 systemd[1]: xray.service: Scheduled restart job, restart counter is at 3.
Mar 04 01:58:36 3 systemd[1]: Stopped Xray.
Mar 04 01:58:36 3 systemd[1]: Started Xray.
Mar 04 01:58:36 3 systemd[1]: xray.service: Main process exited, code=exited, status=203/EXEC
Mar 04 01:58:36 3 systemd[1]: xray.service: Failed with result 'exit-code'.
Mar 04 01:58:36 3 systemd[1]: xray.service: Scheduled restart job, restart counter is at 4.
Mar 04 01:58:36 3 systemd[1]: Stopped Xray.
Mar 04 01:58:36 3 systemd[1]: Started Xray.
Mar 04 01:58:36 3 systemd[1]: xray.service: Main process exited, code=exited, status=203/EXEC
Mar 04 01:58:36 3 systemd[1]: xray.service: Failed with result 'exit-code'.
Mar 04 01:58:36 3 systemd[1]: xray.service: Scheduled restart job, restart counter is at 5.
lines 1-29
^C
root@3:~# systemctl restart xray.service
root@3:~# systemctl status xray.service
● xray.service - Xray
     Loaded: loaded (/lib/systemd/system/xray.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2023-03-04 02:00:46 CST; 4s ago
       Docs: https://xtls.github.io/
    Process: 14769 ExecStart=/root/v2ray/xray run -config /root/v2ray/config.json (code=exited, status=203/EXEC)
   Main PID: 14769 (code=exited, status=203/EXEC)
        CPU: 1ms

Mar 04 02:00:46 3 systemd[1]: xray.service: Scheduled restart job, restart counter is at 4.
Mar 04 02:00:46 3 systemd[1]: Stopped Xray.
Mar 04 02:00:46 3 systemd[1]: Started Xray.
Mar 04 02:00:46 3 systemd[1]: xray.service: Main process exited, code=exited, status=203/EXEC
Mar 04 02:00:46 3 systemd[1]: xray.service: Failed with result 'exit-code'.
Mar 04 02:00:46 3 systemd[1]: xray.service: Scheduled restart job, restart counter is at 5.
Mar 04 02:00:46 3 systemd[1]: Stopped Xray.
Mar 04 02:00:46 3 systemd[1]: xray.service: Start request repeated too quickly.
Mar 04 02:00:46 3 systemd[1]: xray.service: Failed with result 'exit-code'.
Mar 04 02:00:46 3 systemd[1]: Failed to start Xray.
root@3:~# journalctl -n 50 -u xray.service
-- Journal begins at Thu 2021-12-30 18:13:58 CST, ends at Sat 2023-03-04 02:00:59 CST. --
Mar 04 01:58:36 3 systemd[14732]: xray.service: Failed at step EXEC spawning /root/v2ray/xray: No such file or directory
Mar 04 01:58:36 3 systemd[1]: xray.service: Main process exited, code=exited, status=203/EXEC
Mar 04 01:58:36 3 systemd[1]: xray.service: Failed with result 'exit-code'.
Mar 04 01:58:36 3 systemd[1]: xray.service: Scheduled restart job, restart counter is at 3.
Mar 04 01:58:36 3 systemd[1]: Stopped Xray.
Mar 04 01:58:36 3 systemd[1]: Started Xray.
Mar 04 01:58:36 3 systemd[1]: xray.service: Main process exited, code=exited, status=203/EXEC
Mar 04 01:58:36 3 systemd[1]: xray.service: Failed with result 'exit-code'.
Mar 04 01:58:36 3 systemd[1]: xray.service: Scheduled restart job, restart counter is at 4.
Mar 04 01:58:36 3 systemd[1]: Stopped Xray.
Mar 04 01:58:36 3 systemd[1]: Started Xray.
Mar 04 01:58:36 3 systemd[1]: xray.service: Main process exited, code=exited, status=203/EXEC
Mar 04 01:58:36 3 systemd[1]: xray.service: Failed with result 'exit-code'.
Mar 04 01:58:36 3 systemd[1]: xray.service: Scheduled restart job, restart counter is at 5.
Mar 04 01:58:36 3 systemd[1]: Stopped Xray.
Mar 04 01:58:36 3 systemd[1]: xray.service: Start request repeated too quickly.
Mar 04 01:58:36 3 systemd[1]: xray.service: Failed with result 'exit-code'.
Mar 04 01:58:36 3 systemd[1]: Failed to start Xray.
Mar 04 02:00:45 3 systemd[14765]: xray.service: Failed to execute /root/v2ray/xray: Permission denied
Mar 04 02:00:45 3 systemd[14765]: xray.service: Failed at step EXEC spawning /root/v2ray/xray: Permission denied
Mar 04 02:00:45 3 systemd[1]: Started Xray.
Mar 04 02:00:45 3 systemd[1]: xray.service: Main process exited, code=exited, status=203/EXEC
Mar 04 02:00:45 3 systemd[1]: xray.service: Failed with result 'exit-code'.
Mar 04 02:00:45 3 systemd[1]: xray.service: Scheduled restart job, restart counter is at 1.
Mar 04 02:00:45 3 systemd[1]: Stopped Xray.
Mar 04 02:00:45 3 systemd[1]: Started Xray.
Mar 04 02:00:45 3 systemd[14766]: xray.service: Failed to execute /root/v2ray/xray: Permission denied
Mar 04 02:00:45 3 systemd[14766]: xray.service: Failed at step EXEC spawning /root/v2ray/xray: Permission denied
lines 1-29
^C
root@3:~# chmod -R 777 /root/v2ray
root@3:~# systemctl restart xray.service
root@3:~# journalctl -n 50 -u xray.service
-- Journal begins at Thu 2021-12-30 18:13:58 CST, ends at Sat 2023-03-04 02:02:17 CST. --
Mar 04 02:00:46 3 systemd[1]: Stopped Xray.
Mar 04 02:00:46 3 systemd[1]: Started Xray.
Mar 04 02:00:46 3 systemd[1]: xray.service: Main process exited, code=exited, status=203/EXEC
Mar 04 02:00:46 3 systemd[1]: xray.service: Failed with result 'exit-code'.
Mar 04 02:00:46 3 systemd[1]: xray.service: Scheduled restart job, restart counter is at 4.
Mar 04 02:00:46 3 systemd[1]: Stopped Xray.
Mar 04 02:00:46 3 systemd[1]: Started Xray.
Mar 04 02:00:46 3 systemd[1]: xray.service: Main process exited, code=exited, status=203/EXEC
Mar 04 02:00:46 3 systemd[1]: xray.service: Failed with result 'exit-code'.
Mar 04 02:00:46 3 systemd[1]: xray.service: Scheduled restart job, restart counter is at 5.
Mar 04 02:00:46 3 systemd[1]: Stopped Xray.
Mar 04 02:00:46 3 systemd[1]: xray.service: Start request repeated too quickly.
Mar 04 02:00:46 3 systemd[1]: xray.service: Failed with result 'exit-code'.
Mar 04 02:00:46 3 systemd[1]: Failed to start Xray.
Mar 04 02:02:16 3 systemd[1]: Started Xray.
Mar 04 02:02:16 3 systemd[14796]: xray.service: Failed to execute /root/v2ray/xray: Permission denied
Mar 04 02:02:16 3 systemd[14796]: xray.service: Failed at step EXEC spawning /root/v2ray/xray: Permission denied
Mar 04 02:02:16 3 systemd[1]: xray.service: Main process exited, code=exited, status=203/EXEC
Mar 04 02:02:16 3 systemd[1]: xray.service: Failed with result 'exit-code'.
Mar 04 02:02:16 3 systemd[1]: xray.service: Scheduled restart job, restart counter is at 1.
Mar 04 02:02:16 3 systemd[1]: Stopped Xray.
Mar 04 02:02:16 3 systemd[1]: Started Xray.
Mar 04 02:02:16 3 systemd[14797]: xray.service: Failed to execute /root/v2ray/xray: Permission denied
Mar 04 02:02:16 3 systemd[14797]: xray.service: Failed at step EXEC spawning /root/v2ray/xray: Permission denied
Mar 04 02:02:16 3 systemd[1]: xray.service: Main process exited, code=exited, status=203/EXEC
Mar 04 02:02:16 3 systemd[1]: xray.service: Failed with result 'exit-code'.
Mar 04 02:02:16 3 systemd[1]: xray.service: Scheduled restart job, restart counter is at 2.
Mar 04 02:02:16 3 systemd[1]: Stopped Xray.`

**Comment by jinwyp** [comment]
已修复 请卸载后 在重新安装
