### ISSUE TITLE
建议写个自动获取版本号

### ISSUE THREAD

**Issue by Potterli20** [jinwyp/one_click_script#223]
建议写个自动获取版本号或者弄个自选的

**Comment by jinwyp** [comment]
现在已经是自动获取最新版本了

**Comment by jinwyp** [comment]
https://github.com/jinwyp/one_click_script/blob/master/trojan_v2ray_install.sh#L2681

> > 现在已经是自动获取最新版本了
> 
> 因为我看到你那边还是手机版本号

https://github.com/jinwyp/one_click_script/blob/master/trojan_v2ray_install.sh#L2681

自动获取最新的版本
