### ISSUE TITLE
xray升级1.8.0 一键脚本无法启动xray

### ISSUE THREAD

**Issue by shinanzhuomo** [jinwyp/one_click_script#224]
**Describe the bug** A clear and concise description of what the bug is.
在提出问题前请先自行排除服务器端问题和升级到最新客户端，同时也请通过搜索确认是否有人提出过相同问题。

!!! 请务必提供安装的选择的第几项 !!!
!!! 请务必提供什么操作系统 和用的什么终端 !!!

17 安装xray+自带trojan

**OS and Terminal:**  系统环境 信息 请务必提供什么操作系统 和用的什么终端 ，还有VPS主机商

- OS:centos
- Version 8.6
- Terminal : Windows putty
- VPS 腾讯云

**To Reproduce** 复现方法  
一键安装xray1.8.0
Log Info 日志信息： 请提供安装出错的信息
Mar 13 14:18:14 server systemd[1]: Started Xray.
Mar 13 14:18:14 server xray[4935]: Xray 1.8.0 (Xray, Penetrates Everything.) Custom (go1.20.2 linux/amd64)
Mar 13 14:18:14 server xray[4935]: A unified platform for anti-censorship.
Mar 13 14:18:14 server xray[4935]: 2023/03/13 14:18:14 [Info] infra/conf/serial: Reading config: /root/v2ray/config.json
Mar 13 14:18:14 server xray[4935]: Failed to start: main: failed to load config files: [/root/v2ray/config.json] > infra/conf: Please use VLESS flow "xtls-rprx-vision" with TLS or REALITY.
Mar 13 14:18:14 server systemd[1]: xray.service: main process exited, code=exited, status=23/n/a
Mar 13 14:18:14 server systemd[1]: Unit xray.service entered failed state.
Mar 13 14:18:14 server systemd[1]: xray.service failed.

安装完成nginx 是否启动成功，域名的网站是否能正常打开，如果打不开说明nginx安装有问题，请给出nginx安装时输出日志
能打开nginx

**Comment by jinwyp** [comment]
不要用国内的云安装此类脚本
