### ISSUE TITLE
安装xray的时候无法获取证书

### ISSUE THREAD

**Issue by xiaoshv** [jinwyp/one_click_script#228]
不知道是不是脚本的原因，4个申请地址都无法申请证书，用了很久这个脚本，查了很多不知道什么原因，麻烦作者看一下

**Comment by jinwyp** [comment]
请按照格式发表问题.

**Comment by hqwl159** [comment]
我以为是我域名问题，还一直找问题，更换了ip更换了域名。原来是脚本问题！！！
