### ISSUE TITLE
采用19安装完，忘记保存返回信息，如何查看V2ray和Trojan的信息？

### ISSUE THREAD

**Issue by iJayscn** [jinwyp/one_click_script#23]
采用19安装完，忘记保存返回信息，如何查看V2ray和Trojan的信息？

**Comment by jinwyp** [comment]
v2ray 配置在/root/v2ray/config.json 
trojan 配置在/root/trojan/server.json

用cat 命令就能查看 例如 cat /root/v2ray/config.json

**Comment by LanQ** [comment]
> v2ray 配置在/root/v2ray/config.json
> trojan 配置在/root/trojan/server.json
> 
> 用cat 命令就能查看 例如 cat /root/v2ray/config.json

您好 v2ray和trojan同时安装完成后 只显示v2ray的配置信息 能不能同时也显示trojan的配置信息 比如(密码)

**Comment by jinwyp** [comment]
> > v2ray 配置在/root/v2ray/config.json
> > trojan 配置在/root/trojan/server.json
> > 用cat 命令就能查看 例如 cat /root/v2ray/config.json
> 
> 您好 v2ray和trojan同时安装完成后 只显示v2ray的配置信息 能不能同时也显示trojan的配置信息 比如(密码)

都显示了 只不过log太多， 需要往上翻查看， 我近期准备改一下增加查看配置功能

**Comment by jinwyp** [comment]
> > v2ray 配置在/root/v2ray/config.json
> > trojan 配置在/root/trojan/server.json
> > 用cat 命令就能查看 例如 cat /root/v2ray/config.json
> 
> 您好 v2ray和trojan同时安装完成后 只显示v2ray的配置信息 能不能同时也显示trojan的配置信息 比如(密码)

已增加查看配置信息功能 选择28即可
