### ISSUE TITLE
安装ss2022完后不能正常用

### ISSUE THREAD

**Issue by Ball727** [jinwyp/one_click_script#230]
**Describe the bug** A clear and concise description of what the bug is.
在提出问题前请先自行排除服务器端问题和升级到最新客户端，同时也请通过搜索确认是否有人提出过相同问题。

!!! 请务必提供安装的选择的第几项 !!!
!!! 请务必提供什么操作系统 和用的什么终端 !!!

1. 例如选择的第2项 安装trojan

**OS and Terminal:**  系统环境 信息 请务必提供什么操作系统 和用的什么终端 ，还有VPS主机商

- OS: [e.g. Centos]
- Version [e.g. 7]
- Terminal :  例如 Mac的teminal 或 linux ssh 或 zsh 或 Windows putty 或 VPS自带的在线ssh
- VPS  [e.g.  Google Cloud]

**To Reproduce** 复现方法  

Log Info 日志信息： 请提供安装出错的信息
例如xxx

安装完成nginx 是否启动成功，域名的网站是否能正常打开，如果打不开说明nginx安装有问题，请给出nginx安装时输出日志

第七项，系统是搬瓦工vps的debian11 我发现脚本到获取xray的权限的时候报错了，但是继续进行了下去，报错显示没有找到ssxray文件夹里的xray文件，我去查看也确实没有下载到本地，最终结果导致节点不可用，查看ssxray的运行状态为运行失败，估计就是这个原因

**Comment by jinwyp** [comment]
1 看下 /root/shadowsocksxray/xray 是否xray下载成功
2  运行 systemctl status shadowsocksxray.service 看下是否运行

3 脚本更新了一下  修复了一个bug  可以卸载重新安装 
配置文件之前多了逗号. 如果不想卸载和手动编辑  vi /root/shadowsocksxray/config.json
删除 最后2行的2个逗号. 
可以参考下面的3888行位置 删除2个逗号
https://github.com/jinwyp/one_click_script/commit/21a11173145b4b79fd62a7649572d481ff8d36ba#diff-4bd6e80eb4584137c721a1ed45b73de4051539bc464543e7c2c9466ae35f5d24L3888

然后保存退出后 重启 shadowsocks 
运行 systemctl restart shadowsocksxray.service

**Comment by Ball727** [comment]
> 1 看下 /root/shadowsocksxray/xray 是否运行 systemctl status shadowsocksxray.service 运行 systemctl status shadowsocksxray.service 看下是否运行
> 
> 3脚本更新个个个个可以借载安装配置配置 配置文件文件了了了一一个个借号借号。。。。。。如果如果如果如果如果如果不不不不不不不不想 不 。的3888行位置删去2个逗号 [21a1117 #diff-4bd6e80eb4584137c721a1ed45b73de4051539bc464543e7c2c9466ae35f5d24L3888](https://github.com/jinwyp/one_click_script/commit/21a11173145b4b79fd62a7649572d481ff8d36ba#diff-4bd6e80eb4584137c721a1ed45b73de4051539bc464543e7c2c9466ae35f5d24L3888)
> 
> 然后保存退出后重新启动shadowsocks 运行systemctl restart shadowsocksxray.service

![image](https://user-images.githubusercontent.com/98798220/232081632-b26924b3-269d-4b4b-b611-09978e9f7d24.png)
还是这样

**Comment by Ball727** [comment]
![image](https://user-images.githubusercontent.com/98798220/232081891-35883bb3-12bb-4abe-a85a-65fc0fd58e1b.png)

**Comment by Ball727** [comment]
wget可以下载xray文件
dns
![image](https://user-images.githubusercontent.com/98798220/232099179-d675ce5d-9456-488b-80c9-b987a997cdef.png)

**Comment by jinwyp** [comment]
那就是unzip 没有安装导致的 
我已经改进了脚本 增加unzip的安装 你可以更新一下脚本卸载后重新安装

**Comment by Ball727** [comment]
依旧无法授权？
![image](https://user-images.githubusercontent.com/98798220/232104306-c750fc8e-a290-42c3-b3e0-e9a9ec6d061b.png)

**Comment by jinwyp** [comment]
你安装 unzip了吗？ apt install -y unzip

安装过程中 下面的链接 是否xray下载成功  

https://github.com/XTLS/Xray-core/releases/download/v1.8.0/Xray-linux-64.zip

**Comment by Ball727** [comment]
运行脚本前 我按照你说的 安装了unzip 这样应该是可以了？
![image](https://user-images.githubusercontent.com/98798220/232179996-4e319a78-9a7a-4690-b8bb-4470a4e44460.png)

**Comment by jinwyp** [comment]
对这样就可以了
