### ISSUE TITLE
为什么trojan、vmess等不是走443端口？

### ISSUE THREAD

**Issue by joyongzhu** [jinwyp/one_click_script#232]
感谢大佬，照着大佬的教程成功了！！！

不过我有一个疑问，为什么trojan、vmess等最后提供访问的端口不是443呢？而是每提供一个用户就新增一个端口。这样会不会不安全？因为我听说似乎通过443进行访问更容易混淆视线。
![image](https://user-images.githubusercontent.com/17783147/233288796-264a0e6b-25a0-4ff9-a561-740d3fbf94ae.png)

**Comment by jinwyp** [comment]
这个是x ui的设置 要去x ui 项目问

因为443 端口给x ui 的网站使用了啊， 你也可以设置443 但如果和网站冲突就无法工作了。 你可以试试
