### ISSUE TITLE
trojan-go无法连接read: connection reset by peer

### ISSUE THREAD

**Issue by lincoe** [jinwyp/one_click_script#233]
vps: lightnode
操作系统: debain10

用的是2选项安装的trojan-go, 域名网站能打开，80/443端口也能通。但是电脑手机都无法连接。无论是Cloudflare CDN打开关闭都一样。

v2rayN：基础连接已经关闭，发送时发生错误。
v2rayNG: io:read/write on closed pipe

trojan_access_log:
[INFO]  2023/04/23 22:10:05 tcp connection from 120.37.102.152:15033
[INFO]  2023/04/23 22:10:05 tcp connection from 120.37.102.152:15032
[ERROR] 2023/04/23 22:10:05 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | read tcp 38.54.118.102:443->120.37.102.152:15032: read: connection reset by peer
[INFO]  2023/04/23 22:10:05 tcp connection from 120.37.102.152:15037
[ERROR] 2023/04/23 22:10:05 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | write tcp 38.54.118.102:443->120.37.102.152:15037: write: connection reset by peer
[INFO]  2023/04/23 22:10:05 tcp connection from 120.37.102.152:15038
[INFO]  2023/04/23 22:10:05 tcp connection from 120.37.102.152:15039
[ERROR] 2023/04/23 22:10:05 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | read tcp 38.54.118.102:443->120.37.102.152:15039: read: connection reset by peer
[ERROR] 2023/04/23 22:10:05 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | read tcp 38.54.118.102:443->120.37.102.152:15038: read: connection reset by peer
[ERROR] 2023/04/23 22:10:05 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | read tcp 38.54.118.102:443->120.37.102.152:15033: read: connection reset by peer
[INFO]  2023/04/23 22:10:05 tcp connection from 120.37.102.152:15042
[ERROR] 2023/04/23 22:10:05 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | write tcp 38.54.118.102:443->120.37.102.152:15042: write: connection reset by peer
[INFO]  2023/04/23 22:10:05 tcp connection from 120.37.102.152:15043
[ERROR] 2023/04/23 22:10:05 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | write tcp 38.54.118.102:443->120.37.102.152:15043: write: connection reset by peer
[INFO]  2023/04/23 22:10:06 tcp connection from 120.37.102.152:15044
[ERROR] 2023/04/23 22:10:06 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | write tcp 38.54.118.102:443->120.37.102.152:15044: write: connection reset by peer
[INFO]  2023/04/23 22:10:06 tcp connection from 120.37.102.152:15045
[ERROR] 2023/04/23 22:10:06 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | read tcp 38.54.118.102:443->120.37.102.152:15045: read: connection reset by peer
[INFO]  2023/04/23 22:10:06 tcp connection from 120.37.102.152:15040
[INFO]  2023/04/23 22:10:06 tcp connection from 120.37.102.152:15047
[ERROR] 2023/04/23 22:10:06 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | write tcp 38.54.118.102:443->120.37.102.152:15047: write: connection reset by peer
[INFO]  2023/04/23 22:10:07 tcp connection from 120.37.102.152:15048
[ERROR] 2023/04/23 22:10:07 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | read tcp 38.54.118.102:443->120.37.102.152:15040: read: connection reset by peer
[INFO]  2023/04/23 22:10:07 tcp connection from 120.37.102.152:15049
[ERROR] 2023/04/23 22:10:07 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | read tcp 38.54.118.102:443->120.37.102.152:15048: read: connection reset by peer
[INFO]  2023/04/23 22:10:07 tcp connection from 120.37.102.152:15050
[ERROR] 2023/04/23 22:10:07 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | read tcp 38.54.118.102:443->120.37.102.152:15050: read: connection reset by peer
[INFO]  2023/04/23 22:10:07 tcp connection from 120.37.102.152:15051
[ERROR] 2023/04/23 22:10:07 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | read tcp 38.54.118.102:443->120.37.102.152:15051: read: connection reset by peer
[ERROR] 2023/04/23 22:10:07 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | read tcp 38.54.118.102:443->120.37.102.152:15049: read: connection reset by peer
[INFO]  2023/04/23 22:10:07 tcp connection from 120.37.102.152:15053
[ERROR] 2023/04/23 22:10:07 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | read tcp 38.54.118.102:443->120.37.102.152:15053: read: connection reset by peer
[INFO]  2023/04/23 22:10:08 tcp connection from 120.37.102.152:15054
[ERROR] 2023/04/23 22:10:08 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | read tcp 38.54.118.102:443->120.37.102.152:15054: read: connection reset by peer
[INFO]  2023/04/23 22:10:09 tcp connection from 120.37.102.152:15056
[ERROR] 2023/04/23 22:10:09 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | read tcp 38.54.118.102:443->120.37.102.152:15056: read: connection reset by peer
[INFO]  2023/04/23 22:10:09 tcp connection from 120.37.102.152:15057
[ERROR] 2023/04/23 22:10:09 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | write tcp 38.54.118.102:443->120.37.102.152:15057: write: connection reset by peer
[INFO]  2023/04/23 22:10:10 user 44829bb5741500d7da822ba713ec2cb890c681b3b6a95324b83348ec from 120.37.102.152:14796 tunneling to android.googleapis.com:443 closed sent: 6.62 KiB recv: 1.98 KiB
[INFO]  2023/04/23 22:10:14 user 44829bb5741500d7da822ba713ec2cb890c681b3b6a95324b83348ec from 120.37.102.152:14798 tunneling to www.googleapis.com:443 closed sent: 203.87 KiB recv: 35.86 KiB
[INFO]  2023/04/23 22:11:06 tcp connection from 120.37.102.152:15090
[ERROR] 2023/04/23 22:11:06 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | read tcp 38.54.118.102:443->120.37.102.152:15090: read: connection reset by peer

**Comment by jinwyp** [comment]
选18 安装用xray最新的协议，  trojan-go 被识别了。 不行就换端口 试试 或用ping.pe 看看 希望不大。
