### ISSUE TITLE
甲骨文centos ubuntu安装都不正常

### ISSUE THREAD

**Issue by szylhh** [jinwyp/one_click_script#234]
1，甲骨文以上系统安装后v2都没网机器伪装的网站都打不开，总之不正常，IP正常
2，aws安装后，安装11. 安装官方 Cloudflare WARP Client 启动SOCKS5代理, 用于解锁 Netflix 限制  后没法访问goole，youtube等网站，全局代理百度可以打开，ip也是aws，但是和11相关的哪些服务都打不开

**Comment by jinwyp** [comment]
1 甲骨文 是ARM的机器吗？ 可能会有问题 某些功能不支持ARM. 运行的哪个脚本 选的第几项？
2 安装warp socks5 后 需要配合xray 才可以 不是安装了warp就能自动解锁的

**Comment by shizhenying** [comment]
不是arm机器，centos8我这无法安装wirguan,我换了Ubuntu:OS info: Ubuntu, ubuntu, 20.04.6, 20.04, focal, amd CPU amd64, bash, apt-get,
安装完成后还是不行，域名访问不了，nginx不正常！删机器重装了几次都这样，报错如下:
Please input number:^C
root@instance-20230427-1134:/home/ubuntu# nginx
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] still could not bind()
root@instance-20230427-1134:/home/ubuntu#
root@instance-20230427-1134:/home/ubuntu# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
root@instance-20230427-1134:/home/ubuntu#

**Comment by shizhenying** [comment]
> 1甲骨文是ARM的机器吗？ 可能会有问题某些功能不能支持ARM。运行的哪个脚本选的第几项？ 2 装warp socks5 后需要配合xray 才可以 不是装了warp 就能自动解锁的

不是arm机器，centos8我无法安装wirguan，我换了Ubuntu:OS info: Ubuntu, ubuntu, 20.04.6, 20.04, focal, amd CPU amd64, bash, apt-get,安装完成后还是不行，域名称访问问不过
来，nginx不正常！插件重装了几次都这样，报错如下：
Please input number:^C
root@instance-20230427-1134:/home/ubuntu# nginx
nginx: [emerg] bind() to 0.0.0.0 :80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed ( 98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already正在使用中)
nginx: [emerg] 仍然无法绑定 ()
root@instance-20230427-1134:/home/ubuntu#
root@instance-20230427-1134:/home/ubuntu# nginx -t
nginx: 配置文件/etc/nginx/nginx.conf 语法没问题
nginx: 配置文件/etc/nginx/nginx.conf 测试成功
root@instance -20230427-1134:/家/ubuntu#

**Comment by shizhenying** [comment]
> 1 甲骨文 是ARM的机器吗？ 可能会有问题 某些功能不支持ARM. 运行的哪个脚本 选的第几项？ 2 安装warp socks5 后 需要配合xray 才可以 不是安装了warp就能自动解锁的

不是arm机器，centos8我无法安装wirguan，我换了Ubuntu:OS info: Ubuntu, ubuntu, 20.04.6, 20.04, focal, amd CPU amd64, bash, apt-get,安装完成后还是不行，域名称访问问不过
来，nginx不正常！插件重装了几次都这样，报错如下：
Please input number:^C
root@instance-20230427-1134:/home/ubuntu# nginx
nginx: [emerg] bind() to 0.0.0.0 :80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed ( 98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already正在使用中)
nginx: [emerg] 仍然无法绑定 ()
root@instance-20230427-1134:/home/ubuntu#
root@instance-20230427-1134:/home/ubuntu# nginx -t
nginx: 配置文件/etc/nginx/nginx.conf 语法没问题
nginx: 配置文件/etc/nginx/nginx.conf 测试成功
root@instance -20230427-1134:/家/ubuntu#

请问大佬怎么解决?

**Comment by shizhenying** [comment]
> 1 甲骨文 是ARM的机器吗？ 可能会有问题 某些功能不支持ARM. 运行的哪个脚本 选的第几项？ 2 安装warp socks5 后 需要配合xray 才可以 不是安装了warp就能自动解锁的

不是arm机器，centos8我这无法安装wirguan,我换了Ubuntu:OS info: Ubuntu, ubuntu, 20.04.6, 20.04, focal, amd CPU amd64, bash, apt-get,
安装完成后还是不行，域名访问不了，nginx不正常！删机器重装了几次都这样，报错如下:
Please input number:^C
root@instance-20230427-1134:/home/ubuntu# nginx
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] still could not bind()
root@instance-20230427-1134:/home/ubuntu#
root@instance-20230427-1134:/home/ubuntu# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
root@instance-20230427-1134:/home/ubuntu#
请问大佬怎么办?

**Comment by jinwyp** [comment]
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
你这个80端口被占用了啊？

**Comment by shizhenying** [comment]
被nginx占用，重装系统也是，kill后还是不行，安装的15我可以给你开一台Ubuntu试试
