### ISSUE TITLE
是否能解决Openai 1020错误？

### ISSUE THREAD

**Issue by Giant-Li** [jinwyp/one_click_script#235]
选择12安装好之后，可以正常访问google，youtube。但是访问openai就会提示1020错误。
看网上有人说cloudflare warp可以解决，用了了这个脚本(https://github.com/xianlinyi/warp2chatgpt)，可以安装。但提示找不到xray。
请问有什么办法解决吗？谢谢！

**Comment by jinwyp** [comment]
1 首先通过我的脚本 安装warp 的 IPV6 

可以运行 wget --no-check-certificate https://raw.githubusercontent.com/jinwyp/one_click_script/master/install_kernel.sh && chmod +x ./install_kernel.sh && ./install_kernel.sh

选12 安装wgcf的IPV6 或21 安装 warp-go 的IPV6  安装过程中选3 添加全局IPV6 但IPV4优先模式


2 然后编辑 Xray 配置文件 添加openai IPv6 分流

输入命令 
vi /root/v2ray/config.json


然后在routing里面加入openai 域名分流规则

···
            {
                "type": "field",
                "outboundTag": "IPv6_out",
                "domain": ["geosite:openai"]
            },

···

**Comment by shizhenying** [comment]
我也有这个问题，折腾了三四天😢

**Comment by shizhenying** [comment]
大佬，还是不行，我看你的分流好像还没有加进去，依然不1020错误，我自己设置IPV6又不行

**Comment by jinwyp** [comment]
使用脚本安装xray 选这15 或其他选项， 安装过程中已经增加openai的分流 选择 2. 使用 IPv6 解锁, 需要配合安装WARP 推荐使用   即可
```
wget --no-check-certificate https://raw.githubusercontent.com/jinwyp/one_click_script/master/trojan_v2ray_install.sh && chmod +x ./trojan_v2ray_install.sh && ./trojan_v2ray_install.sh
```
