### ISSUE TITLE
how can i bypass spotify 403 error?

### ISSUE THREAD

**Issue by mmdz1122** [jinwyp/one_click_script#236]
i've installed both cloudflare wrap and wiregurd successfully but the problem is with spotify. 
it gives forbidden error (Your client does not have permission to get URL / from this server.).
is there any solution to that?

**Comment by jinwyp** [comment]
Use the latest script and reinstall xray , then you can choose the warp IPV6 rule of spotify  during the Installation, 
```
wget --no-check-certificate https://raw.githubusercontent.com/jinwyp/one_click_script/master/trojan_v2ray_install.sh && chmod +x ./trojan_v2ray_install.sh && ./trojan_v2ray_install.sh
```
