### ISSUE TITLE
VLess-gRPC-TLS生成的vless链接多了一个“/”

### ISSUE THREAD

**Issue by FoxZzzzzzz** [jinwyp/one_click_script#237]
**Describe the bug** A clear and concise description of what the bug is.
在提出问题前请先自行排除服务器端问题和升级到最新客户端，同时也请通过搜索确认是否有人提出过相同问题。

!!! 请务必提供安装的选择的第几项 !!!
第14项，VLess-gRPC-TLS 配置参数 支持CDN 

!!! 请务必提供什么操作系统 和用的什么终端 !!!
Centos 7 ，v2rayN
!!! 请务必提供是否开启了Cloudflare 的 CDN !!!
开启CDN，并开启了gRPC开关。
!!! 请用 ping.pe 或 ping.ceo 网站 输入IP:端口号 查看是否被GFW屏蔽 !!!
未屏蔽，所有地区访问正常

** Steps to reproduce the behavior: **  请提供使用脚本安装的选择第几项: 

1. 选择第14项，VLess-gRPC-TLS 配置参数 支持CDN 
2. 安装 xray 1.7.5 . 安装过程中选择了解锁流媒体，未安装nginx，和宝塔配合使用

** OS and Terminal: **  系统环境 信息 请务必提供什么操作系统 和用的什么终端 ，还有VPS主机商

- OS: Centos
- Version：7
- Terminal :  xshell
- VPS：RackNerd 

=========== Xray客户端 VLess-gRPC-TLS 配置参数 支持CDN =============
{
    协议: VLess,
    地址: xx.xx.xx,
    端口: xxxx,
    uuid: xxxxxx94-3909-xxxxxxxx-xxxxxxxdc40b,
    额外id: 0,  // AlterID 如果是Vless协议则不需要该项
    流控flow: 空,
    加密方式: none,  
    传输协议: gRPC,
    gRPC serviceName: 5b3xxxxx,
    底层传输协议: tls,
    别名:自己起个任意名称
}

导入链接 Vless 格式:
vless://xxxxxx94-3909-xxxxxxxx-xxxxxxxdc40b@xx.xx.xx:xxx?encryption=none&security=tls&type=grpc&host=xx.xx.xx&serviceName=**%2f**5b3xxxxx#xx.xx.xx+gRPC_tls
生成的vless链接多了一个“/”
导致连接失败。手动去掉后连接正常

**Comment by jinwyp** [comment]
哪个位置多了 "/"  没看出来多了啊

**Comment by FoxZzzzzzz** [comment]
> 哪个位置多了 "/" 没看出来多了啊
vless://[xxxxxx94-3909-xxxxxxxx-xxxxxxxdc40b@xx.xx.xx](mailto:xxxxxx94-3909-xxxxxxxx-xxxxxxxdc40b@xx.xx.xx):xxx?encryption=none&security=tls&type=grpc&host=xx.xx.xx&serviceName=%2f5b3xxxxx#xx.xx.xx+gRPC_tls
"%2f",生成的vless链接里面的serviceName=后面的，

**Comment by jinwyp** [comment]
已修复
