### ISSUE TITLE
最新版本生成的vless链接用acl4ssr转换为clash订阅不正确

### ISSUE THREAD

**Issue by zyf2008Neptune** [jinwyp/one_click_script#238]
选择11，服务器选择Xray，只安装vless+ws+ngnix+tls，生成的vless链接转换后为空，vmess链接转换后没有域名；
且脚本更新后重新安装vless+ws+ngnix+tls，套用cdn会显示521错误，无法访问原网址。
vless+grpc+ngnix+tls则没有任何提示，也无法工作。

**Comment by jinwyp** [comment]
服务器端是否运行正常， 网站 nginx 是否正常 systemctl status nginx
 xray是否运行正常 systemclt status xray

客户端用v2rayN 试一下 不要用clash

**Comment by zyf2008Neptune** [comment]
nginx运行不正常
× nginx.service - nginx - high performance web server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; preset: enabled)
    Drop-In: /etc/systemd/system/nginx.service.d
             └─override.conf
     Active: failed (Result: exit-code) since Wed 2023-05-17 13:16:50 UTC; 1min 45s ago
   Duration: 6.216s
       Docs: https://nginx.org/en/docs/
        CPU: 8ms

May 17 13:16:50 v2 systemd[1]: Starting nginx - high performance web server...
May 17 13:16:50 v2 nginx[35168]: nginx: [emerg] invalid number of arguments in "server_name" directive in /etc/nginx/conf.d/nossl_site.conf:3
May 17 13:16:50 v2 systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
May 17 13:16:50 v2 systemd[1]: nginx.service: Failed with result 'exit-code'.
May 17 13:16:50 v2 systemd[1]: Failed to start nginx - high performance web server.
xray应该是正常的
● xray.service - Xray
     Loaded: loaded (/lib/systemd/system/xray.service; enabled; preset: enabled)
     Active: active (running) since Wed 2023-05-17 13:17:51 UTC; 3min 38s ago
       Docs: https://xtls.github.io/
   Main PID: 35264 (xray)
      Tasks: 6 (limit: 1115)
     Memory: 14.8M
        CPU: 191ms
     CGroup: /system.slice/xray.service
             └─35264 /root/v2ray/xray run -config /root/v2ray/config.json

**Comment by zyf2008Neptune** [comment]
链接也有问题：
vless://XXX@:443?encryption=none&security=tls&type=grpc&host=&serviceName=XXX#+gRPC_tls
