### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by R3Dium** [jinwyp/one_click_script#239]
trying install bbrplus kernel 6.1 and this error shows up
ERROR 404: Not Found.
i tried couple of other kernels but faced with same error

**Comment by jinwyp** [comment]
Which OS  you used debian or ubuntu or centos ? Which os version you used ?

**Comment by R3Dium** [comment]
ubuntu 20

**Comment by jinwyp** [comment]
fixed 

pls rerun the script below to install 6.1 kernel

···
wget --no-check-certificate https://raw.githubusercontent.com/jinwyp/one_click_script/master/install_kernel.sh && chmod +x ./install_kernel.sh && ./install_kernel.sh
···
