### ISSUE TITLE
Connection Bug in Telegram.

### ISSUE THREAD

**Issue by hawshemi** [jinwyp/one_click_script#240]
_Hi_

I have `VLESS+Vision`. when I install `WARP+Wireguard` (number 12 on the script menu) and enable `IPv6`, images and videos on telegram won't download. and sometimes it switches between `Connecting` and `Updating` 2-3 times in 2 seconds.

I've been using it for 2 months but this happened about a week ago.

I think the server ipv6 is connecting and disconnecting (due to some weird reasons!) and this would show itself on Telegram specifically. but it is happening globally on the VPS.

**Comment by jinwyp** [comment]
1 To enable WARP, you need modify the vless config file , add ipv6 traffic rule for telegram . Otherwise  telegram traffic will not go with the WARP Ipv6. 

2 WARP is slow than your VPS ipv4 traffic..  Do not use WARP unless you need it to unlock video stream service.

**Comment by hawshemi** [comment]
@jinwyp I only use it for unblocking Spotify and ChatGPT, removing Google ReCaptcha.

Are there other ways to unblock these services?

Streaming services like Netflix don't matter to me.

**Comment by jinwyp** [comment]
> @jinwyp I only use it for unblocking Spotify and ChatGPT, removing Google ReCaptcha.
> 
> Are there other ways to unblock these services?
> 
> Streaming services like Netflix don't matter to me.

You can try warp-go

**Comment by hawshemi** [comment]
> try warp-go

Do you mean this script? https://github.com/fscarmen/warp

**Comment by jinwyp** [comment]
> > try warp-go
> 
> Do you mean this script? https://github.com/fscarmen/warp

yes
