### ISSUE TITLE
warp

### ISSUE THREAD

**Issue by mmdz1122** [jinwyp/one_click_script#245]
Hello, hope you doing great.
I've installed cloudflare warp for ipv6 successfuly and i've checked the changes and it is all good.
I have an issue with my phone, I usually use ssh tunneling or vless on my phone but the problem is that the clients like napsernet or others are not working with my cloudflare ipv6, instead they're working with ipv4.
I've prioritized ipv6 for wireguard and vps (op. 15 and 16 of script). 
am i missing something here? how can i solve this?

**Comment by jinwyp** [comment]
Sorry I don‘t use WARP on iPhone.

Some solution :

1 Edit vless config  outbound and route rule to support  napsernet using WARP on VPS , then iPhone connect to VPS using vless

2 try use 21 , another WARP project .  https://github.com/fscarmen/warp
