### ISSUE TITLE
在现在第29项后，再安装15项能不能不检测域名？

### ISSUE THREAD

**Issue by lukemin** [jinwyp/one_click_script#25]
30. 不安装nginx, 只安装 trojan 或 v2ray
再选择第
15. 只安装v2ray (VLess 或 VMess协议) 开启websocket, 支持CDN, 不安装nginx, 方便与现有网站或宝塔面板共存
能不能不忽略ip地址，不正确的选项？我已经设置好了cdn了，并且是ipv6的服务器，修改起来太麻烦了。

**Comment by jinwyp** [comment]
可以 等我改一下 加个选项

**Comment by jinwyp** [comment]
已经加好了 选完30后都可以 选择是否检测域名和是否申请证书
