### ISSUE TITLE
怎么新增反代域名设置，已安装了可视化管理面板

### ISSUE THREAD

**Issue by klmahua** [jinwyp/one_click_script#250]
就是想在服务器上同时运行不同的域名，一个域名正常伪装链接使用，想在增加一个反代谷歌域名的配置，如何增加，命令是什么？

**Comment by jinwyp** [comment]
可视化面板你是用我的脚本安装的XUI吗？ 

还有你说的需求没看懂 我的脚本直接支持多域名就是可以生成2个xray服务器端用2两个不同的域名， 但可视化面板XUI不是我这个项目 你要用XUI可视化面板只能自己改配置了

**Comment by klmahua** [comment]
就是服务器只部署个代理  太浪费了  想在服务器上部署很多不同用途的域名   在trojanweb_site.conf文件所在目录下  上传新增的虚拟主机配置文件不起作用  不知道怎么设置

**Comment by jinwyp** [comment]
不要用trojanweb  用我脚本23 安装 才可以  否则只能自己改nginx 配置

或者你用23安装后 把配置看懂 自己研究明白 在重新安装trojan-web 自己弄

**Comment by klmahua** [comment]
> 不要用trojanweb 用我脚本23 安装 才可以 否则只能自己改nginx 配置
> 
> 或者你用23安装后 把配置看懂 自己研究明白 在重新安装trojan-web 自己弄
哦  感谢大佬的回复
2的安装支持多域名配置吗？  ：安装 trojan/trojan-go 和 nginx, 支持CDN 开启websocket, trojan-go 运行在443端口

**Comment by jinwyp** [comment]
除了23  其他也支持多域名 但需要手动修改nginx 配置.

**Comment by klmahua** [comment]
> 除了23 其他也支持多域名 但需要手动修改nginx 配置.
> 
> 具体参考 nginx sni 配置
> 
> https://qoanty.github.io/2021/05/xray-nginx-sni/

哦，那我去试试选项2的安装 选项2安装  多域名设置  是需要多次执行选项2的安装吗

**Comment by klmahua** [comment]
已经部署了一个代理域名  怎么在新增一个反代谷歌的域名  国内访问不了谷歌  想通过反代域名直接访问谷歌

**Comment by jinwyp** [comment]
> 已经部署了一个代理域名 怎么在新增一个反代谷歌的域名 国内访问不了谷歌 想通过反代域名直接访问谷歌
直接用trojan 或 xray 代理 访问google, 用nginx 反代需要非常多的设置, google 有很多需要登录的地方 不是反代能解决的

**Comment by klmahua** [comment]
> > 已经部署了一个代理域名 怎么在新增一个反代谷歌的域名 国内访问不了谷歌 想通过反代域名直接访问谷歌
> > 直接用trojan 或 xray 代理 访问google, 用nginx 反代需要非常多的设置, google 有很多需要登录的地方 不是反代能解决的
感谢回复  问题已经解决  用了管理的代理软件 另外装了一个nginx  主要是管理的自动安装的nginx不知道怎么设置多域名  现在另外装了nginx就好修改了
