### ISSUE TITLE
当我解锁 geosite:openai 提示错误

### ISSUE THREAD

**Issue by summanzhao** [jinwyp/one_click_script#252]
您好！先表示非常感谢您的付出，我的问题如下：
操作系统Debian 10 64 Bit，内核升级到了5.10 LTS，具体安装了以下：
1、内核安装界面先选择了41，成功后安装了2、11
2、Trojan-go V2ray Xray 一键安装脚本，选择了 11，安装过程中选择解锁
netflix、google、openai、youtube
配置文件片段如下：
 "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "type": "field",
                "outboundTag": "IPv6_out",
                "domain": ["test.com" ] 
            },
            {
                "type": "field",
                "outboundTag": "WARP_out",
                "domain": [ "geosite:google" , "geosite:netflix" , "geosite:youtube" , "geosite:openai"] 
            },
            {
                "type": "field",
                "outboundTag": "V2Ray_out",
                "domain": ["test.com" ] 
            },
            
            {
                "type": "field",
                "domain": [
                    "geosite:cn"
                ],
                "outboundTag": "blocked_out"
            },
            {
                "type": "field",
                "ip": [
                    "geoip:cn"
                ],
                "outboundTag": "blocked_out"
            },           
            {
                "type": "field",
                "outboundTag": "IPv4_out",
                "network": "udp,tcp"
            }
        ]
    },

当我的配置文件中
"domain": [ "geosite:google" , "geosite:netflix" , "geosite:youtube" , "geosite:openai"] 
启动V2ray会提示错误：
 main: failed to read config files: [/root/v2ray/config.json] > infra/conf/rule: invalid field rule > infra/conf/rule: failed to parse domain rule: geosite:openai > infra/conf/rule: failed to load geosite: openai > infra/conf/geodata/standard: list not found in geosite.dat: openai
好像是说geosite.dat里面没找到openai

如果配置文件里面去掉解锁openai，如下
"domain": [ "geosite:google" , "geosite:netflix" , "geosite:youtube" ] 
启动，且客户端访问一切正常
我该如何解决此问题？

**Comment by jinwyp** [comment]
不清楚你为什么没有获取到最新的geosite.dat 文件. 是不是原来安装过老版本的v2ray或xray.

可以到这里下载最新版 geosite.dat

 https://github.com/Loyalsoldier/v2ray-rules-dat

https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat

下载后 替换 /root/v2ray/geosite.dat 即可
