### ISSUE TITLE
Trojan服务器部署完，当天正常第二天就无法使用了，Windows客户端报proxy/trojan: failed to find an available destination / common/retry: all retry attempts failed错误（如图）是怎么回事？服务器上没有做任何改动。

### ISSUE THREAD

**Issue by cheros2022** [jinwyp/one_click_script#255]
![1700271322065](https://github.com/jinwyp/one_click_script/assets/110144221/a79d5199-4752-4b39-b01c-ca881771cf34) --客户端日志

/nginxweb/nginx-error.log
2023/11/17 21:58:17 [error] 6804#6804: *174 open() "/nginxweb/html/.env" failed (2: No such file or directory), client: 135.125.246.110, serv
er: kqqkw.***.***, request: "GET /.env HTTP/1.1", host: "13.***.***.***"
2023/11/17 22:24:55 [error] 6804#6804: *176 open() "/nginxweb/html/Core/Skin/Login.aspx" failed (2: No such file or directory), client: 124.1
56.187.113, server: kqqkw.***.***, request: "HEAD /Core/Skin/Login.aspx HTTP/1.1", host: "13.***.***.***:80"
2023/11/17 22:28:42 [error] 6804#6804: *177 open() "/nginxweb/html/.env" failed (2: No such file or directory), client: 185.254.196.173, serv
er: kqqkw.***.***, request: "GET /.env HTTP/1.1", host: "13.***.***.***"
2023/11/17 22:37:40 [error] 6804#6804: *182 open() "/nginxweb/html/js/jquery-3.5.1.slim.min.js" failed (2: No such file or directory), client
: 111.7.96.164, server: kqqkw.***.***, request: "GET /js/jquery-3.5.1.slim.min.js HTTP/1.1", host: "13.***.***.***", referrer: "http://13.1
14.103.150/"
2023/11/17 22:37:40 [error] 6804#6804: *183 open() "/nginxweb/html/js/bootstrap.bundle.min.js" failed (2: No such file or directory), client:
 111.7.96.164, server: kqqkw.***.***, request: "GET /js/bootstrap.bundle.min.js HTTP/1.1", host: "13.***.***.***", referrer: "http://13.114
.103.150/"
2023/11/17 22:37:44 [error] 6804#6804: *180 open() "/nginxweb/html/favicon.ico" failed (2: No such file or directory), client: 111.7.96.164, 
server: kqqkw.***.***, request: "GET /favicon.ico HTTP/1.1", host: "13.***.***.***"
2023/11/17 22:56:22 [error] 6804#6804: *187 open() "/nginxweb/html/.env" failed (2: No such file or directory), client: 135.125.246.110, serv
er: kqqkw.***.***, request: "GET /.env HTTP/1.1", host: "13.***.***.***"
2023/11/18 00:00:33 [error] 6804#6804: *191 open() "/nginxweb/html/Core/Skin/Login.aspx" failed (2: No such file or directory), client: 124.1
56.187.113, server: kqqkw.***.***, request: "HEAD /Core/Skin/Login.aspx HTTP/1.1", host: "13.***.***.***:80"
2023/11/18 00:30:26 [error] 6804#6804: *192 open() "/nginxweb/html/.env" failed (2: No such file or directory), client: 135.125.244.48, serve
r: kqqkw.***.***, request: "GET /.env HTTP/1.1", host: "13.***.***.***"
2023/11/18 00:46:21 [error] 6804#6804: *196 open() "/nginxweb/html/.env" failed (2: No such file or directory), client: 135.125.246.110, serv
er: kqqkw.***.***, request: "GET /.env HTTP/1.1", host: "13.***.***.***"
2023/11/18 01:35:54 [error] 6804#6804: *202 open() "/nginxweb/html/Core/Skin/Login.aspx" failed (2: No such file or directory), client: 124.1
56.187.113, server: kqqkw.***.***, request: "HEAD /Core/Skin/Login.aspx HTTP/1.1", host: "13.***.***.***:80"

**Comment by jinwyp** [comment]
https://ping.pe/ 用这个网站测试服务器是否被GFW封端口 可以在服务器修改其他端口试试， trojan 现在被识别的很厉害 换 xray 最新的 XTLS-Vision-REALITY 协议吧

**Comment by cheros2022** [comment]
收到，感谢。
________________________________
发件人: Jin ***@***.***>
发送时间: 2023年11月18日 22:34
收件人: jinwyp/one_click_script ***@***.***>
抄送: Cheros Peng ***@***.***>; Author ***@***.***>
主题: Re: [jinwyp/one_click_script] Trojan服务器部署完，当天正常第二天就无法使用了，Windows客户端报proxy/trojan: failed to find an available destination / common/retry: all retry attempts failed错误（如图）是怎么回事？服务器上没有做任何改动。 (Issue #255)


https://ping.pe/ 用这个网站测试服务器是否被GFW封端口 可以在服务器修改其他端口试试， trojan 现在被识别的很厉害 换 xray 最新的 XTLS-Vision-REALITY 协议吧

―
