### ISSUE TITLE
输入域名提示不正确

### ISSUE THREAD

**Issue by jsjcjsjc** [jinwyp/one_click_script#256]
!!! 请务必提供安装的选择的第几项 !!!
18
!!! 请务必提供什么操作系统 和用的什么终端 !!!
debian 11
!!! 请务必提供是否开启了Cloudflare 的 CDN !!!
NO
!!! 请用 ping.pe 或 ping.ceo 网站 输入IP:端口号 查看是否被GFW屏蔽 !!!
确认没有问题

选择`18. 安装 v2ray或xray (VLess-TCP-REALITY XTLS Vision)) 不支持CDN, 可选安装nginx, VLess运行在443端口`
发现使用自己域名的时候并不会安装nginx,直接提示错误,我输入的是类似download.test.net这样的域名
![image.png](https://7up.pics/images/2023/11/18/image.png)

**Comment by jinwyp** [comment]
download.test.net 测试了一下 没问题， 是不是你输入的时候输错了域名

**Comment by jsjcjsjc** [comment]
> download.test.net 测试了一下 没问题， 是不是你输入的时候输错了域名

还真是可以的,为了防止域名被泄漏我随便写了一个.

又测试了一下,这样的不行-> us.1ad.net

**Comment by jinwyp** [comment]
首字母不能是数字
