### ISSUE TITLE
nginx无法运行

### ISSUE THREAD

**Issue by zyf2008Neptune** [jinwyp/one_click_script#258]
**Describe the bug** A clear and concise description of what the bug is.
在提出问题前请先自行排除服务器端问题和升级到最新客户端，同时也请通过搜索确认是否有人提出过相同问题。

!!! 请务必提供安装的选择的第几项 !!!
!!! 请务必提供什么操作系统 和用的什么终端 !!!
!!! 请务必提供是否开启了Cloudflare 的 CDN !!!
!!! 请用 ping.pe 或 ping.ceo 网站 输入IP:端口号 查看是否被GFW屏蔽 !!!

** Steps to reproduce the behavior: **  请提供使用脚本安装的选择第几项: 

1. 例如选择的第2项 安装trojan. 安装过程中选择了 2 原版trojan-go 
2. 例如选择的第11项 安装v2ray 或 xray . 安装过程中选择了 websocket 选项  并 选择了解锁流媒体

** OS and Terminal: **  系统环境 信息 请务必提供什么操作系统 和用的什么终端 ，还有VPS主机商

- OS: [e.g. Centos]
- Version [e.g. 7]
- Terminal :  例如 Mac的teminal 或 linux ssh 或 zsh 或 Windows putty 或 VPS自带的在线ssh
- VPS  [e.g.  Google Cloud]

** To Reproduce ** 复现方法  

Log Info 日志信息： 请提供安装时出错的信息
例如 xxx

安装完成后 通过以下命令 检查服务是否启动成功  并提供输出日志

1. 检查 trojan 是否启动成功  ``` systemctl status trojan ```
2. 检查 trojan-go 是否启动成功  ``` systemctl status trojan-go ```
3. 检查 v2ray 是否启动成功  ``` systemctl status v2ray ```
4. 检查 xray 是否启动成功  ``` systemctl status xray ```
4. 检查 shadowsocks (xray内核) 是否启动成功  ``` systemctl status shadowsocksxray ```
5. 检查 nginx 是否启动成功  ``` systemctl nginx xray ``` 

安装完成如选择了安装nginx, 请检查 nginx 是否启动成功，域名网站是否能在浏览器正常打开， 是https 还是 http. 正常安装应该是https. 如果打不开说明nginx安装有问题，请给出nginx安装时输出日志

× nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; preset: enabled)
    Drop-In: /etc/systemd/system/nginx.service.d
             └─override.conf
     Active: failed (Result: exit-code) since Thu 2023-12-14 12:42:26 UTC; 27min ago
       Docs: man:nginx(8)
    Process: 658 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)
        CPU: 6ms

Dec 14 12:42:26 nep-v2 systemd[1]: Starting nginx.service - A high performance web server and a reverse proxy server...
Dec 14 12:42:26 nep-v2 nginx[658]: 2023/12/14 12:42:26 [emerg] 658#658: invalid number of arguments in "server_name" directive in /etc/nginx/conf.d/nossl_sit>
Dec 14 12:42:26 nep-v2 nginx[658]: nginx: configuration file /etc/nginx/nginx.conf test failed
Dec 14 12:42:26 nep-v2 systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Dec 14 12:42:26 nep-v2 systemd[1]: nginx.service: Failed with result 'exit-code'.
Dec 14 12:42:26 nep-v2 systemd[1]: Failed to start nginx.service - A high performance web server and a reverse proxy server.

**Comment by jinwyp** [comment]
在一台机器 同时安装了第2项和第11项?   卸载只安装一个试试 

什么操纵系统? 版本多少?

**Comment by zyf2008Neptune** [comment]
> 在一台机器 同时安装了第2项和第11项? 卸载只安装一个试试
> 
> 什么操纵系统? 版本多少?

ubuntu 23.10 ,只安装了xray

**Comment by jinwyp** [comment]
根据上面的错误信息 
 invalid number of arguments in "server_name" directive in /etc/nginx/conf.d/nossl_sit>

/etc/nginx/conf.d/nossl_site  编辑下这个文件  是不是 server_name 写错了 域名写错了啊

**Comment by zyf2008Neptune** [comment]
> 6\. systemctl nginx xray

编辑并手动添加了域名，nginx状态正常了，但网址显示invalid response，网址无法访问😥

**Comment by jinwyp** [comment]
不清楚 可以卸载重新安装选11试试 注意域名要写对
