### ISSUE TITLE
Trojan-web一键安装证书无法续签问题

### ISSUE THREAD

**Issue by lihui26zhong** [jinwyp/one_click_script#259]
问题1：
子菜单30，子菜单1，一键安装trojan-web和nginx伪装网站，安装过程一切正常，能正常访问伪装网站并建立trojan服务。但是网站证书到期后，不能自动及手动续签。
原因：
一键安装过程先安装了trojan-web和trojan，在安装过程中，acme.sh采用的是stand alone模式申请证书，后又安装了nginx，这就导致acme.sh在证书到期后续签的时候，80端口被nginx占用，而无法完成续签。

**Comment by jinwyp** [comment]
安装的时候可以选择 不是stand alone 模式 选择webroot 模式试试 

或者 在crontab脚本中 先停掉nginx.  在运行acme 续签

命令如下
1 进入编辑crontab  ``` crontab -e ```
2 在 42 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
上面增加一行 ``` 41 4 * * 0,1,2,3,4,5,6 systemctl stop nginx
3.  在 42 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
下面在增加一行 ``` 44 4 * * 0,1,2,3,4,5,6 systemctl restart nginx

**Comment by lihui26zhong** [comment]
安装过程貌似没有stand alone 模式 和webroot 模式的选择。
我的处理办法是删除acme储存的证书信息，重新以nginx模式申请证书。这样再续签就是nginx模式了。
主要是我没有找到如何更改已申请到的证书由standalone模式改成nginx模式。所以索性删了重新申请。
可否考虑先安装nginx以及建立网站，然后再安装trojan-web，以nginx模式申请。这样是不是就没问题了。

**Comment by lihui26zhong** [comment]
dd

**Comment by jinwyp** [comment]
> 安装过程貌似没有stand alone 模式 和webroot 模式的选择。 我的处理办法是删除acme储存的证书信息，重新以nginx模式申请证书。这样再续签就是nginx模式了。 主要是我没有找到如何更改已申请到的证书由standalone模式改成nginx模式。所以索性删了重新申请。 可否考虑先安装nginx以及建立网站，然后再安装trojan-web，以nginx模式申请。这样是不是就没问题了。

我的脚本26就可以各种模式申请证书， trojan-web自带申请证书 具体可以看trojan-web的项目说明 只要保证trojan-web和nginx运行的端口不冲突就可以
