### ISSUE TITLE
EUserv ipv6 only VPS 域名解析地址与本VPS IP地址不一致导致安装中断！

### ISSUE THREAD

**Issue by fscarmen** [jinwyp/one_click_script#26]
域名解析地址为 srv1***48.blue.kund****troller.de (2a02:180:6:1::**45, 本VPS的IP为 195.140.***.147. 
***屏蔽了具体信息。那个ipv6地址是正确的。但后面的195开头的地址是couldflare的地址，只做了AAAA记录，已经把彩云取消没有开CDN，只解析DNS。

**Comment by jinwyp** [comment]
如果不装nginx 可以选择 30 然后进入子菜单 安装 不装nginx的版本 可以跳过ip验证.  或者等我更新一下 把装nginx的版本也可以跳过ip验证

**Comment by jinwyp** [comment]
> 域名解析地址为 srv1_**48.blue.kund**__troller.de (2a02:180:6:1::**45, 本VPS的IP为 195.140.**_.147.
> ***屏蔽了具体信息。那个ipv6地址是正确的。但后面的195开头的地址是couldflare的地址，只做了AAAA记录，已经把彩云取消没有开CDN，只解析DNS。

脚本已经修改好了， 可以选择跳过检测域名

**Comment by fscarmen** [comment]
选19仍然是原来的错误，选30之后选"14. 只安装trojan-go 运行在443端口, 支持CDN, 开启websocket, 不安装nginx. 请确保80端口有监听,否则trojan-go无法启动"。在证书申请环节红色不通过。另一个脚本开发者Kirin10000之前也有同样的问题，后面他处理了。以下是引用他的回复

“我申请证书使用的是nginx作为web服务，你使用的另外一个脚本申请证书是用acme.sh单机模式，即使用socat监听80端口申请证书
两者效果一样的，但是nginx默认只监听80端口ipv4，调一下就好了”

**Comment by jinwyp** [comment]
> 选19仍然是原来的错误，选30之后选"14. 只安装trojan-go 运行在443端口, 支持CDN, 开启websocket, 不安装nginx. 请确保80端口有监听,否则trojan-go无法启动"。在证书申请环节红色不通过。另一个脚本开发者Kirin10000之前也有同样的问题，后面他处理了。以下是引用他的回复
> 
> “我申请证书使用的是nginx作为web服务，你使用的另外一个脚本申请证书是用acme.sh单机模式，即使用socat监听80端口申请证书
> 两者效果一样的，但是nginx默认只监听80端口ipv4，调一下就好了”

你需要把原来的卸载 ，你还要重新下载我的脚本，重新安装就可以。直接选19 ，然后根据提示 是否检测域名指向的IP正确 输入n不检测域名就可以安装。

 没看懂你的需求是什么 ，如果你的机器 已经有nginx 那么要区分nginx 是跑在80还是443， 然后根据不同情况选择不同的选项安装即可
