### ISSUE TITLE
无法下载BBRPlus内核

### ISSUE THREAD

**Issue by ransxd** [jinwyp/one_click_script#260]
** Steps to reproduce the behavior: **  请提供使用脚本安装的选择第几项: 

67

** OS and Terminal: **  系统环境 信息 请务必提供什么操作系统 和用的什么终端 ，还有VPS主机商

- OS : Ubuntu
- Version : 22.04LTS
- Terminal :  Windows ssh
- VPS : AWS

** To Reproduce ** 复现方法  
使用Ubuntu/Debian选择61-67选项

Log Info 日志信息： 请提供安装时出错的信息

 Linux 内核 一键安装脚本 | 2023-11-16 | 系统支持：centos7+ / debian10+ / ubuntu16.04+
 Linux 内核 4.9 以上都支持开启BBR, 如要开启BBR Plus 则需要安装支持BBR Plus的内核
 在任何生产环境中请谨慎使用此脚本, 升级内核有风险, 请做好备份！在某些VPS会导致无法启动!

 当前系统内核: 6.2.0 (KVM)   已安装 BBR 加速内核, 未启动加速模块
 当前拥塞控制算法: cubic    ECN: 只对入站请求开启(默认值)   当前队列算法: fq_codel

 1. 查看当前系统内核版本, 检查是否支持BBR / BBR2 / BBR Plus
 2. 开启 BBR 或 BBR2 加速, 开启 BBR2 需要安装 XanMod 内核
 3. 开启 BBR Plus 加速
 4. 优化 系统网络配置
 5. 删除 系统网络优化配置

 6. 查看 Wireguard 运行状态
 7. 重启 Wireguard
 8. 查看 WARP SOCKS5 代理运行状态
 9. 重启 WARP SOCKS5
 10. 查看 WireGuard 和 WARP SOCKS5 运行状态, 错误日志, 如果WireGuard启动失败 请选该项排查错误

 11. 安装官方 Cloudflare WARP Client 启动SOCKS5代理, 用于解锁 Netflix 限制
 12. 安装 WireGuard 和 Cloudflare WARP 工具 Wgcf, 启动 IPv4或IPv6, 用于避免弹出Google人机验证
 13. 同时安装 官方 Cloudflare WARP Client, WireGuard 和 命令行工具 Wgcf, 不推荐
 14. 卸载 WireGuard 和 Cloudflare WARP linux client
 15. 切换 WireGuard 对VPS服务器的 IPv6 和 IPv4 的网络支持
 16. 设置 VPS 服务器 IPv4 还是 IPv6 网络优先访问
 21. 安装 warp 脚本 by fscarmen
 22. 安装 warp-go 脚本 by fscarmen
 23. 自动刷新WARP IP 直到支持 Netflix 非自制剧解锁

 44. 安装 内核 4.19 LTS, 通过 Ubuntu kernel mainline 安装
 45. 安装 内核 5.4 LTS, 通过 Ubuntu kernel mainline 安装
 46. 安装 内核 5.10 LTS, 通过 Ubuntu kernel mainline 安装
 47. 安装 内核 5.15, 通过 Ubuntu kernel mainline 安装
 48. 安装 内核 5.19, 通过 Ubuntu kernel mainline 安装
 49. 安装 最新版本内核 6.1, 通过 Ubuntu kernel mainline 安装

 51. 安装 XanMod Kernel 内核 6.1 LTS, 官方源安装
 52. 安装 XanMod Kernel 内核 6.2, 官方源安装

 61. 安装 BBR Plus 内核 4.14.129 LTS, cx9208 编译的 dog250 原版, 推荐使用
 62. 安装 BBR Plus 内核 4.14 LTS, UJX6N 编译
 63. 安装 BBR Plus 内核 4.19 LTS, UJX6N 编译
 64. 安装 BBR Plus 内核 5.10 LTS, UJX6N 编译
 65. 安装 BBR Plus 内核 5.15 LTS, UJX6N 编译
 66. 安装 BBR Plus 内核 6.1 LTS, UJX6N 编译
 67. 安装 BBR Plus 最新版内核 6.4或更高版本, UJX6N 编译

 0. 退出脚本

Please input number:67

 VPS服务器已成功设置为 IPv4 优先访问网络

UJX6N 编译的 Linux bbrplus 内核版本号为 6.6.1

Hit:1 http://ap-east-1.ec2.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://ap-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://ap-east-1.ec2.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
dpkg is already the newest version (1.21.1ubuntu2.2).
0 upgraded, 0 newly installed, 0 to remove and 26 not upgraded.

 ==================================================
    开始手动安装 linux 内核
 ==================================================

 准备从 UJX6N github 网站下载 bbr plus 的linux内核并安装

/root/download_linux_kernel/6.6.1-bbrplus/Debian-Ubuntu_Required_linux-image-6.6.1-bbrplus_6.6.1-1_amd64.deb
文件下载中... 下载地址: https://github.com/UJX6N/bbrplus-6.x_stable/releases/download/6.6.1-bbrplus/Debian-Ubuntu_Required_linux-image-6.6.1-bbrplus_6.6.1-1_amd64.deb
--2023-12-25 16:00:29--  https://github.com/UJX6N/bbrplus-6.x_stable/releases/download/6.6.1-bbrplus/Debian-Ubuntu_Required_linux-image-6.6.1-bbrplus_6.6.1-1_amd64.deb
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-12-25 16:00:29 ERROR 404: Not Found.

/root/download_linux_kernel/6.6.1-bbrplus/Debian-Ubuntu_Optional_linux-headers-6.6.1-bbrplus_6.6.1-1_amd64.deb
文件下载中... 下载地址: https://github.com/UJX6N/bbrplus-6.x_stable/releases/download/6.6.1-bbrplus/Debian-Ubuntu_Optional_linux-headers-6.6.1-bbrplus_6.6.1-1_amd64.deb
--2023-12-25 16:00:29--  https://github.com/UJX6N/bbrplus-6.x_stable/releases/download/6.6.1-bbrplus/Debian-Ubuntu_Optional_linux-headers-6.6.1-bbrplus_6.6.1-1_amd64.deb
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-12-25 16:00:30 ERROR 404: Not Found.

正确的下载地址应该形如https://github.com/UJX6N/bbrplus-6.x_stable/releases/download/6.6.1-bbrplus/Debian-Ubuntu_Required_linux-image-6.6.1-bbrplus_6.6.1-bbrplus-1_arm64.deb

**Comment by jinwyp** [comment]
已修复 bbrplus 6.6 请重新运行脚本安装
