### ISSUE TITLE
安装完后X可以访问但无法发帖和评论

### ISSUE THREAD

**Issue by someoneinhere** [jinwyp/one_click_script#265]
v2rayN已是最新版
!!! 请务必提供安装的选择的第几项 !!! ------18
!!! 请务必提供什么操作系统 和用的什么终端 !!!------Debian12，终端Bitvise SSH Client，VPS是Vultr
!!! 请务必提供是否开启了Cloudflare 的 CDN !!!------未开启
!!! 请用 ping.pe 或 ping.ceo 网站 输入IP:端口号 查看是否被GFW屏蔽 !!!----确认没有问题
选择的第18项 安装v2ray 或 xray . 安装过程中选择了 websocket 选项  并 选择了解锁流媒体

连接后国内网站正常使用，YouTube正常访问正常评论。X正常访问无法评论和发帖，反馈帖子未发送，重试也一样，切换到别的VPN后X正常使用，请看看谢谢。

**Comment by someoneinhere** [comment]
刚发现X也无法删除以往帖子

**Comment by jinwyp** [comment]
你不要选择解锁流媒体，解锁流媒体是需要配合warp使用。需要安卓warp才可以
还有换个服务器试试

**Comment by someoneinhere** [comment]
好，谢谢
