### ISSUE TITLE
建议检查crontab以避免出现错误acme.sh: No such file or directory 

### ISSUE THREAD

**Issue by K-Soon** [jinwyp/one_click_script#266]
ubuntu 20.04 LTS操作系统，在申请证书时出现错误acme.sh: No such file or directory。尝试运行
curl  https://get.acme.sh | sh
发现是由于没有crontab命令而中断。运行
apt install cron
安装此命令之后就能正常申请证书。
由于部分VPS的初始操作系统可能缺少crontab而导致证书申请失败，建议在申请证书之前进行crontab命令的验证与安装。

**Comment by jinwyp** [comment]
已修复
