### ISSUE TITLE
脚本18项，安装 v2ray或xray (VLess-TCP-REALITY XTLS Vision)) 添加v2ray-reality服务器转发，生成的配置文件语法错误 

### ISSUE THREAD

**Issue by 65654865** [jinwyp/one_click_script#268]
streamSettings项多了个逗号导致xray不能启动，删除后正常使用
        {
            "tag": "V2Ray_out",
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "*",
                        "port": 443,
                        "users": [
                            {
                                "id": " ",
                                "encryption": "none",
                                
                                "level": 0
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "reality",

                ,
                "realitySettings": {
                    "show": false,
                    "dest": "www.ebay.com:443",
                    "xver": 0,
                    "serverNames": [
                        "www.ebay.com",
                        "ebay.com",
                        "www.ebay.com",
                        "icloud.com",
                        "www.icloud.com",
                        "apple.com",
                        "www.apple.com",
                        "mozilla.org",
                        "addons.mozilla.org",
                        "walmart.com",
                        "www.walmart.com",
                        "etsy.com",
                        "www.etsy.com",
                        "shopify.com",
                        "www.shopify.com",
                        "samsung.com",
                        "www.samsung.com",
                        "airbnb.com",
                        "www.airbnb.com",
                        "asml.com",
                        "www.asml.com",
                        "tsmc.com",
                        "www.tsmc.com",
                        "pfizer.com",
                        "www.pfizer.com",
                        "microsoft.com",
                        "www.microsoft.com",
                        "support.microsoft.com",
                        "office.com",
                        "www.office.com",
                        "signup.live.com",
                        "www.live.com",
                        "outlook.live.com",
                        "lovelive-anime.jp",
                        "s0.awsstatic.com",
                        "d1.awsstatic.com",
                        "amazon.com",
                        "m.media-amazon.com",
                        "www.lovelive-anime.jp"
                    ],
                    "privateKey": "*",
                    "maxTimeDiff": 0,
                    "shortIds": [
                        "*"
                    ]
                }
            }
        },

**Comment by jinwyp** [comment]
看了一下 代码没有问题 不知道是否是全新的安装, 建议卸载之前的xray或v2ray 然后用最新的版本的脚本 选18 重新安装

https://github.com/jinwyp/one_click_script/blob/master/trojan_v2ray_install.sh#L6291
