### ISSUE TITLE
有没有人的Google Cloud被封锁了？申诉过去几天了 也没恢复。

### ISSUE THREAD

**Issue by googlespeed** [jinwyp/one_click_script#27]
提出申诉
概要
您的项目 My First Project (id: even-aloe-290301) 因为采取欺骗性或误导性的做法（向网站发送自动流量或查询来人为地提升网站流量）而违反了 Google Cloud Platform 服务条款或使用限制政策（包括您可能在使用的 Google API 的服务条款），因此已被暂停。

 
详细信息
受影响的项目：My First Project (id: even-aloe-290301)

说明：采取欺骗性或误导性的做法，人为地提升网站流量，因而导致项目 My First Project (id: even-aloe-290301) 被暂停。

 

后续步骤
要解决此问题，请进行检查，确保自己的项目未遭入侵，并花一点时间查看适用的服务条款，从而确保您在以后不会违反我们的政策。

若不采取措施并提交申诉，您的项目可能会被删除。

**Comment by jinwyp** [comment]
没遇到过 我的gcp用的很好，没出现过什么情况。是不是nginx的web静态站点引用了其他网站的？ 网上的一键脚本有的直接跳转到其他网站的。
