### ISSUE TITLE
IP version 6 of the server stops working

### ISSUE THREAD

**Issue by alamdari86** [jinwyp/one_click_script#270]
HI
After I run this script on the server and install option 12, after installing the script, the IP version 6 of the server stops working.
How can I fix this problem?

**Comment by jinwyp** [comment]
Which script you install ？  
Does option 12 is to install Wireguard and Warp？ Try option 14 to remove it

**Comment by alamdari86** [comment]
i install [one_click_script](https://github.com/jinwyp/one_click_script)
after i use of option 14 for remove that problem was fix 
but have any way for use of option 12 without stop ipv6 on server?

**Comment by jinwyp** [comment]
try this to use warp
https://gitlab.com/fscarmen/warp
