### ISSUE TITLE
68选项下载地址错误

### ISSUE THREAD

**Issue by ransxd** [jinwyp/one_click_script#271]
**Describe the bug** A clear and concise description of what the bug is.
在提出问题前请先自行排除服务器端问题和把客户端升级到最新版本例如v2rayN，同时也请通过搜索确认是否有人提出过相同问题。

!!! 请务必提供安装的选择的第几项 !!!
!!! 请务必提供什么操作系统 和用的什么终端 !!!
!!! 请务必提供是否开启了Cloudflare 的 CDN !!!
!!! 请用 ping.pe 或 ping.ceo 网站 输入IP:端口号 查看是否被GFW屏蔽 !!!

** Steps to reproduce the behavior: **  请提供使用脚本安装的选择第几项:
68. 安装 BBR Plus 最新版内核 6.7或更高版本, UJX6N 编译

** OS and Terminal: **  系统环境 信息 请务必提供什么操作系统 和用的什么终端 ，还有VPS主机商

- OS: Ubuntu
- Version 22.04
- Terminal :  Termius (Win x64)
- VPS：阿里云

** To Reproduce ** 复现方法
选择68选项100%复现

Log Info 日志信息：
Please input number:68

 VPS服务器已成功设置为 IPv4 优先访问网络

UJX6N 编译的 Linux bbrplus 内核版本号为 6.7.9

Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
dpkg is already the newest version (1.21.1ubuntu2.3).
0 upgraded, 0 newly installed, 0 to remove and 60 not upgraded.

 ==================================================
    开始手动安装 linux 内核
 ==================================================

 准备从 UJX6N github 网站下载 bbr plus 的linux内核并安装

/root/download_linux_kernel/6.7.9-bbrplus/Debian-Ubuntu_Required_linux-image-6.7.9-bbrplus_6.7.9-bbrplus-1_amd64.deb
文件下载中... 下载地址: https://github.com/UJX6N/bbrplus-6.7/releases/download/6.7.9-bbrplus/Debian-Ubuntu_Required_linux-image-6.7.9-bbrplus_6.7.9-bbrplus-1_amd64.deb
--2024-07-25 22:18:16--  https://github.com/UJX6N/bbrplus-6.7/releases/download/6.7.9-bbrplus/Debian-Ubuntu_Required_linux-image-6.7.9-bbrplus_6.7.9-bbrplus-1_amd64.deb
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-07-25 22:18:17 ERROR 404: Not Found.

/root/download_linux_kernel/6.7.9-bbrplus/Debian-Ubuntu_Optional_linux-headers-6.7.9-bbrplus_6.7.9-bbrplus-1_amd64.deb
文件下载中... 下载地址: https://github.com/UJX6N/bbrplus-6.7/releases/download/6.7.9-bbrplus/Debian-Ubuntu_Optional_linux-headers-6.7.9-bbrplus_6.7.9-bbrplus-1_amd64.deb
--2024-07-25 22:18:17--  https://github.com/UJX6N/bbrplus-6.7/releases/download/6.7.9-bbrplus/Debian-Ubuntu_Optional_linux-headers-6.7.9-bbrplus_6.7.9-bbrplus-1_amd64.deb
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-07-25 22:18:18 ERROR 404: Not Found.

正确的仓库地址应该是bbrplus-6.x_stable

**Comment by jinwyp** [comment]
已修复 重新下载脚本运行即可

**Comment by ransxd** [comment]
证实已修复，非常感谢
