### ISSUE TITLE
安装最新内核脚本逻辑存在缺陷

### ISSUE THREAD

**Issue by Naochen2799** [jinwyp/one_click_script#272]
安装最新内核脚本逻辑存在缺陷
没有Debian12相关的判断逻辑
此外，可以启用Debian官方的backports获取bpo支持

**Comment by ppp2020** [comment]
文件下载中... 下载地址: https://elrepo.org/linux/kernel/el7/x86_64/RPMS/kernel-lt-tools-libs-5.4.284-1.el7.elrepo.x86_64.rpm 
--2024-10-11 16:40:57--  https://elrepo.org/linux/kernel/el7/x86_64/RPMS/kernel-lt-tools-libs-5.4.284-1.el7.elrepo.x86_64.rpm
Resolving elrepo.org (elrepo.org)... 69.195.83.87
Connecting to elrepo.org (elrepo.org)|69.195.83.87|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-10-11 16:40:58 ERROR 404: Not Found.

**Comment by jinwyp** [comment]
Debian12 的自带的内核6.1已经够新了  稍后会更新debian12的兼容性 安装6.6内核
