### ISSUE TITLE
https://git.io/kernel.sh 有个内核有问题

### ISSUE THREAD

**Issue by ppp2020** [jinwyp/one_click_script#273]
37. 安装 内核 5.15 LTS, Teddysun 编译 推荐安装
/root/download_linux_kernel/5.10.226/kernel-ml-5.10.226-1.el7.x86_64.rpm
文件下载中... 下载地址: https://dl.lamp.sh/kernel/el7/kernel-ml-5.10.226-1.el7.x86_64.rpm 
--2024-10-11 16:31:17--  https://dl.lamp.sh/kernel/el7/kernel-ml-5.10.226-1.el7.x86_64.rpm
Resolving dl.lamp.sh (dl.lamp.sh)... 51.158.150.74, 2001:bc8:1600:0:208:a2ff:fe0c:6830
Connecting to dl.lamp.sh (dl.lamp.sh)|51.158.150.74|:443... connected.
HTTP request sent, awaiting response... 404 Not Found

但是脚本没有做判断 直接下一步 

希望更新一下 或者脚本可以判断有没有下载  最好能md5对比一下  给个提示 谢谢作者

**Comment by ppp2020** [comment]
文件下载中... 下载地址: https://dl.lamp.sh/kernel/el7/kernel-ml-5.10.226-1.el7.x86_64.rpm 
--2024-10-11 16:32:27--  https://dl.lamp.sh/kernel/el7/kernel-ml-5.10.226-1.el7.x86_64.rpm
Resolving dl.lamp.sh (dl.lamp.sh)... 51.158.150.74, 2001:bc8:1600:0:208:a2ff:fe0c:6830
Connecting to dl.lamp.sh (dl.lamp.sh)|51.158.150.74|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-10-11 16:32:28 ERROR 404: Not Found.

**Comment by ppp2020** [comment]
因为默认确认就是yes  刚才一台vps 直接不能重启了
大家一定要注意安装成功没有啊

**Comment by jinwyp** [comment]
脚本已经修复 
问题的原因是centos7 编译的版本少于centos8的版本 例如centos7 只有5.10.222， 而centos8 的版本5.10.226 如果按照centos8的版本安装就找不到该版本的文件下载。
