### ISSUE TITLE
使用了TLS后就无法链接

### ISSUE THREAD

**Issue by PX1124** [jinwyp/one_click_script#274]
使用11安装WS+TLS不可连接，使用12无TLS则可连接，测试后发现所有需要TLS的安装都不可连接。
安装12时Cloudflare开启仅DNS则可连接，安装完毕后开启代理则再次不可连接。请问TLS的问题该如何解决？

2024/11/09 15:02:34 127.0.0.1:49958 accepted //play.google.com:443 [http -> proxy]
2024/11/09 15:02:35 [Warning] [3038789630] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss:///cfe495bc):  > dial tcp :443: connectex: No connection could be made because the target machine actively refused it.] > common/retry: all retry attempts failed

**Comment by jinwyp** [comment]
换个VPS主机商试一下 有可能被封了
