### ISSUE TITLE
为什么我脚本安装了trajon-go之后链接不上？

### ISSUE THREAD

**Issue by gzz4454** [jinwyp/one_click_script#28]
脚本中6选项安装完之后，用v2ray客户端和igniter客户端都链接不上
账号密码都正确

**Comment by jinwyp** [comment]
在服务器 运行 systemctl status trojan-go 看看状态运行成功没？  还可以看看log显示什么？  运行cat trojan-go-access.log

**Comment by gzz4454** [comment]
[root@racknerd-afe286 ~]# cat trojan-go-access.log
[WARN]  2020/12/21 04:59:15 empty tls fallback port
[WARN]  2020/12/21 05:05:06 empty tls fallback port
[INFO]  2020/12/21 05:06:29 tcp connection from 114.221.20.58:45904
[INFO]  2020/12/21 05:06:29 tls connection from 114.221.20.58:45904
[INFO]  2020/12/21 05:06:39 tcp connection from 114.221.20.58:45956
[INFO]  2020/12/21 05:06:39 tls connection from 114.221.20.58:45956
[INFO]  2020/12/21 05:06:39 user 39295aa482c43c69fe6d9554628a76457266e9e627971d0a622bfb29 from 114.221.20.58:45956 tunneling to dns.google:443 closed sent: 0 B recv: 517 B
[INFO]  2020/12/21 05:06:44 tcp connection from 114.221.20.58:45988
[INFO]  2020/12/21 05:06:44 tls connection from 114.221.20.58:45988
[INFO]  2020/12/21 05:06:44 user 39295aa482c43c69fe6d9554628a76457266e9e627971d0a622bfb29 from 114.221.20.58:45988 tunneling to dns.google:443 closed sent: 0 B recv: 517 B
[INFO]  2020/12/21 05:06:50 tcp connection from 114.221.20.58:46030
[INFO]  2020/12/21 05:06:50 tls connection from 114.221.20.58:46030
[INFO]  2020/12/21 05:06:50 user 39295aa482c43c69fe6d9554628a76457266e9e627971d0a622bfb29 from 114.221.20.58:46030 tunneling to chrome.cloudflare-dns.com:443 closed sent: 0 B recv: 557 B
[INFO]  2020/12/21 05:07:01 tcp connection from 114.221.20.58:46068
[INFO]  2020/12/21 05:07:01 tls connection from 114.221.20.58:46068
[INFO]  2020/12/21 05:07:01 user 39295aa482c43c69fe6d9554628a76457266e9e627971d0a622bfb29 from 114.221.20.58:46068 tunneling to chrome.cloudflare-dns.com:443 closed sent: 0 B recv: 557 B
[INFO]  2020/12/21 05:07:10 tcp connection from 114.221.20.58:46092
[INFO]  2020/12/21 05:07:10 tls connection from 114.221.20.58:46092
[INFO]  2020/12/21 05:07:10 user 39295aa482c43c69fe6d9554628a76457266e9e627971d0a622bfb29 from 114.221.20.58:46092 tunneling to chrome.cloudflare-dns.com:443 closed sent: 0 B recv: 557 B
[INFO]  2020/12/21 05:07:20 tcp connection from 114.221.20.58:46150
[INFO]  2020/12/21 05:07:20 tls connection from 114.221.20.58:46150
[INFO]  2020/12/21 05:07:20 user 39295aa482c43c69fe6d9554628a76457266e9e627971d0a622bfb29 from 114.221.20.58:46150 tunneling to my.racknerd.com:443 closed sent: 0 B recv: 547 B
[INFO]  2020/12/21 05:07:31 tcp connection from 114.221.20.58:46182
[INFO]  2020/12/21 05:07:31 tls connection from 114.221.20.58:46182
[INFO]  2020/12/21 05:07:31 user 39295aa482c43c69fe6d9554628a76457266e9e627971d0a622bfb29 from 114.221.20.58:46182 tunneling to android.googleapis.com:443 closed sent: 0 B recv: 539 B
[INFO]  2020/12/21 05:07:41 tcp connection from 114.221.20.58:46210
[INFO]  2020/12/21 05:07:41 tls connection from 114.221.20.58:46210
[INFO]  2020/12/21 05:07:41 user 39295aa482c43c69fe6d9554628a76457266e9e627971d0a622bfb29 from 114.221.20.58:46210 tunneling to dns.google:443 closed sent: 0 B recv: 517 B
[INFO]  2020/12/21 05:07:50 tcp connection from 114.221.20.58:46230
[INFO]  2020/12/21 05:07:50 tls connection from 114.221.20.58:46230
[INFO]  2020/12/21 05:07:50 user 39295aa482c43c69fe6d9554628a76457266e9e627971d0a622bfb29 from 114.221.20.58:46230 tunneling to dns.google:443 closed sent: 0 B recv: 517 B
[INFO]  2020/12/21 05:08:00 tcp connection from 114.221.20.58:46250
[INFO]  2020/12/21 05:08:00 tls connection from 114.221.20.58:46250
[INFO]  2020/12/21 05:08:00 user 39295aa482c43c69fe6d9554628a76457266e9e627971d0a622bfb29 from 114.221.20.58:46250 tunneling to dns.google:443 closed sent: 0 B recv: 517 B
[INFO]  2020/12/21 05:08:10 tcp connection from 114.221.20.58:46256
[INFO]  2020/12/21 05:08:10 tls connection from 114.221.20.58:46256
[INFO]  2020/12/21 05:08:10 user 39295aa482c43c69fe6d9554628a76457266e9e627971d0a622bfb29 from 114.221.20.58:46256 tunneling to chrome.cloudflare-dns.com:443 closed sent: 0 B recv: 557 B
[INFO]  2020/12/21 05:08:20 tcp connection from 114.221.20.58:46268
[INFO]  2020/12/21 05:08:20 tls connection from 114.221.20.58:46268
[INFO]  2020/12/21 05:08:20 user 39295aa482c43c69fe6d9554628a76457266e9e627971d0a622bfb29 from 114.221.20.58:46268 tunneling to chrome.cloudflare-dns.com:443 closed sent: 0 B recv: 557 B
[INFO]  2020/12/21 05:08:30 tcp connection from 114.221.20.58:46276
[INFO]  2020/12/21 05:08:30 tls connection from 114.221.20.58:46276
[INFO]  2020/12/21 05:08:30 user 39295aa482c43c69fe6d9554628a76457266e9e627971d0a622bfb29 from 114.221.20.58:46276 tunneling to chrome.cloudflare-dns.com:443 closed sent: 0 B recv: 557 B
[INFO]  2020/12/21 05:08:40 tcp connection from 114.221.20.58:46304
[INFO]  2020/12/21 05:08:40 tls connection from 114.221.20.58:46304
[INFO]  2020/12/21 05:08:40 user 39295aa482c43c69fe6d9554628a76457266e9e627971d0a622bfb29 from 114.221.20.58:46304 tunneling to safebrowsing.google.com:443 closed sent: 0 B recv: 589 B
[INFO]  2020/12/21 05:08:50 tcp connection from 114.221.20.58:46330
[INFO]  2020/12/21 05:08:51 tls connection from 114.221.20.58:46330
[INFO]  2020/12/21 05:08:51 user 39295aa482c43c69fe6d9554628a76457266e9e627971d0a622bfb29 from 114.221.20.58:46330 tunneling to www.picaacg.com:443 closed sent: 0 B recv: 517 B
[INFO]  2020/12/21 05:09:00 tcp connection from 114.221.20.58:46332
[INFO]  2020/12/21 05:09:00 tls connection from 114.221.20.58:46332
[INFO]  2020/12/21 05:09:00 user 39295aa482c43c69fe6d9554628a76457266e9e627971d0a622bfb29 from 114.221.20.58:46332 tunneling to www.picaacg.com:443 closed sent: 0 B recv: 517 B
[INFO]  2020/12/21 05:09:10 tcp connection from 114.221.20.58:46334
[INFO]  2020/12/21 05:09:10 tls connection from 114.221.20.58:46334
[INFO]  2020/12/21 05:09:10 user 39295aa482c43c69fe6d9554628a76457266e9e627971d0a622bfb29 from 114.221.20.58:46334 tunneling to dns.google:443 closed sent: 0 B recv: 517 B
[INFO]  2020/12/21 05:09:20 tcp connection from 114.221.20.58:46358
[INFO]  2020/12/21 05:09:20 tls connection from 114.221.20.58:46358
[INFO]  2020/12/21 05:09:20 user 39295aa482c43c69fe6d9554628a76457266e9e627971d0a622bfb29 from 114.221.20.58:46358 tunneling to dns.google:443 closed sent: 0 B recv: 517 B
[INFO]  2020/12/21 05:09:30 tcp connection from 114.221.20.58:46364
[INFO]  2020/12/21 05:09:30 tls connection from 114.221.20.58:46364
[INFO]  2020/12/21 05:09:30 user 39295aa482c43c69fe6d9554628a76457266e9e627971d0a622bfb29 from 114.221.20.58:46364 tunneling to dns.google:443 closed sent: 0 B recv: 517 B
[INFO]  2020/12/21 05:09:40 tcp connection from 114.221.20.58:46390
[INFO]  2020/12/21 05:09:40 tls connection from 114.221.20.58:46390
[INFO]  2020/12/21 05:09:40 user 39295aa482c43c69fe6d9554628a76457266e9e627971d0a622bfb29 from 114.221.20.58:46390 tunneling to chrome.cloudflare-dns.com:443 closed sent: 0 B recv: 517 B
[INFO]  2020/12/21 05:09:50 tcp connection from 114.221.20.58:46398
[INFO]  2020/12/21 05:09:50 tls connection from 114.221.20.58:46398
[INFO]  2020/12/21 05:09:50 user 39295aa482c43c69fe6d9554628a76457266e9e627971d0a622bfb29 from 114.221.20.58:46398 tunneling to chrome.cloudflare-dns.com:443 closed sent: 0 B recv: 517 B
[INFO]  2020/12/21 05:10:00 tcp connection from 114.221.20.58:46406
[INFO]  2020/12/21 05:10:00 tls connection from 114.221.20.58:46406
[INFO]  2020/12/21 05:10:00 user 39295aa482c43c69fe6d9554628a76457266e9e627971d0a622bfb29 from 114.221.20.58:46406 tunneling to chrome.cloudflare-dns.com:443 closed sent: 0 B recv: 517 B
[INFO]  2020/12/21 05:10:06 tcp connection from 114.221.20.58:46426
[INFO]  2020/12/21 05:10:06 tls connection from 114.221.20.58:46426
[INFO]  2020/12/21 05:10:06 user 39295aa482c43c69fe6d9554628a76457266e9e627971d0a622bfb29 from 114.221.20.58:46426 tunneling to safebrowsing.google.com:443 closed sent: 0 B recv: 589 B
[INFO]  2020/12/21 05:10:16 tcp connection from 114.221.20.58:46446
[INFO]  2020/12/21 05:10:26 user 39295aa482c43c69fe6d9554628a76457266e9e627971d0a622bfb29 from 114.221.20.58:45904 tunneling to dns.google:443 closed sent: 8.86 KiB recv: 2.32 KiB
[ERROR] 2020/12/21 05:10:26 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:135 tls handshake failed | read tcp 108.166.223.239:443->114.221.20.58:46446: read: connection reset by peer
[WARN]  2020/12/21 05:09:23 empty tls fallback port
[INFO]  2020/12/21 05:11:26 tcp connection from 112.29.172.224:55343
[ERROR] 2020/12/21 05:11:29 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:135 tls handshake failed | EOF
[WARN]  2020/12/21 05:21:14 empty tls fallback port
见上文，是有什么错误吗？

**Comment by jinwyp** [comment]
看样子是连接成功了啊， 是不是Android 客户端 代理模式设置不对， 你可以找台PC 装个v2rayN 软件试试  https://github.com/2dust/v2rayN/releases

**Comment by gzz4454** [comment]
v2rayN怎么用？

**Comment by gzz4454** [comment]
PC可以连接，为什么手机不行？

**Comment by jinwyp** [comment]
> PC可以连接，为什么手机不行？

应该还是手机客户端设置的问题
 
或者换个android 客户端 试试
https://github.com/2dust/v2rayNG

https://github.com/Kr328/ClashForAndroid/releases

**Comment by gzz4454** [comment]
换了那个torjan能连上了，是因为手机端会验证服务器时间吗？

**Comment by gzz4454** [comment]
刚v2rayNG手机端又连接上了，但是ping700多，直接ping服务器是200左右来着，之前用v2ray的时候也只有400左右，不是说trajon go是低延迟吗

**Comment by gzz4454** [comment]
能加QQ吗，有几个问题想问一下

**Comment by gzz4454** [comment]
在吗大佬？

**Comment by jinwyp** [comment]
> 换了那个torjan能连上了，是因为手机端会验证服务器时间吗？

肯定不是服务器时间问题， 服务器时间已经改成北京时间了

**Comment by jinwyp** [comment]
> 能加QQ吗，有几个问题想问一下

https://t.me/tgfcer2020  可以用电报  国内的软件不安全
