### ISSUE TITLE
只能通过全局模式访问Google，pac模式和manual模式都访问不了

### ISSUE THREAD

**Issue by unclebryan719** [jinwyp/one_click_script#29]
大神，你好！非常感谢您的无私奉献，为开源社区提供了如此好的工具！用了您的安装脚本感觉非常好用，同时也有一些困惑。我只能通过全局模式访问Google，pac模式和manual模式都访问不了，我用的是V2RayX客户端（mac版），不知道您遇到过类似的问题吗？
期待您的回复！

**Comment by jinwyp** [comment]
服务器装的是v2ray还是trojan 

如果是v2ray 换个mac 客户端试试

https://www.v2fly.org/awesome/tools.html

https://github.com/yanue/V2rayU/releases

https://github.com/Qv2ray/Qv2ray/releases

https://github.com/yichengchen/clashX/releases
