### ISSUE TITLE
选择14安装trojan和v2ray，trojan使用正常，v2ray访问不了

### ISSUE THREAD

**Issue by fwcde** [jinwyp/one_click_script#3]
Cent OS7，选择14安装trojan和v2ray，trojan使用正常，v2ray访问不了。

**Comment by jinwyp** [comment]
v2ray 用的客户端是什么？ ws 路径填对了吗？

**Comment by fwcde** [comment]
作者你好，已经测试trojan和v2ray可以共存，二者均能正常工作。

另外请教，安装caddy的作用是什么？不是已经有nginx么？

**Comment by jinwyp** [comment]
> 作者你好，已经测试trojan和v2ray可以共存，二者均能正常工作。
> 
> 另外请教，安装caddy的作用是什么？不是已经有nginx么？

只有选择11 才是安装caddy， 其他都没有安装caddy 而使用的是nginx 

所以如果选择14是没有安装caddy的。

**Comment by fwcde** [comment]
确定？我访问80端口，通过抓包查看返回数据包，服务器返回的http头server字段是caddy

**Comment by jinwyp** [comment]
你可以运行 systemctl stop caddy.service  看看是否装了caddy 如果报错就是没装，如果装了肯定不是我这个脚本装的caddy 

如果运行成功 caddy 停止了，看看80是否能访问？
