### ISSUE TITLE
如何将后端数据与web管理结合?

### ISSUE THREAD

**Issue by liuxyon** [jinwyp/one_click_script#30]
我现在使用你的脚本安装v2-ui, 如何将实时数据与web结合?

**Comment by jinwyp** [comment]
> 我现在使用你的脚本安装v2-ui, 如何将实时数据与web结合?

v2-ui 的问题可以到v2-ui去问 https://github.com/sprov065/v2-ui

**Comment by liuxyon** [comment]
那有没有线程可以结合的? 使用你的脚本方便哈...

**Comment by jinwyp** [comment]
> 那有没有线程可以结合的? 使用你的脚本方便哈...

是要监控流量吗？ 可以用v2borad  https://github.com/v2board/v2board  没有一键脚本
