### ISSUE TITLE
xray核心

### ISSUE THREAD

**Issue by l3617** [jinwyp/one_click_script#31]
我明明选择xray核心为何安装后还是v2ray核心

**Comment by jinwyp** [comment]
选的第几项？

**Comment by jinwyp** [comment]
默认是安装v2ray，是不是直接回车了，需要输入y 才是xray

**Comment by l3617** [comment]
> 默认是安装v2ray，是不是直接回车了，需要输入y才是xray

我是输入y啊，可是重新查看配置，显示的是v2ray核心

**Comment by jinwyp** [comment]
> > 默认是安装v2ray，是不是直接回车了，需要输入y才是xray
> 
> 我是输入y啊，可是重新查看配置，显示的是v2ray核心

28 查看配置显示的信息不是指的核心， xray和v2ray的配置信息是一样的，xray和v2ray配置格式也一样，都是v2ray的配置 

如何查看服务器核心 是xray还是v2ray？， 在/root/v2ray/ 下面可执行文件是xray还是v2ray 即可

**Comment by jinwyp** [comment]
脚本已经修改过，现在配置提示信息都改过了 安装的xray不会在显示v2ray了
