### ISSUE TITLE
安装的时候乱码。

### ISSUE THREAD

**Issue by lukemin** [jinwyp/one_click_script#32]
` OS info: centos, yum, /usr/lib/systemd/system/， bash
Package wget-1.14-18.el7_6.1.x86_64 already installed and latest version
Package curl-7.29.0-59.el7_9.1.x86_64 already installed and latest version
Package git-1.8.3.1-23.el7_8.x86_64 already installed and latest version
Nothing to do
 ==================================================
 Trojan Trojan-go V2ray 一键安装脚本 2020-12-6 更新.  系统支持：centos7+ / debian9+ / ubuntu16.04+
 *请不要在任何生产环境使用此脚本 请不要有其他程序占用80和443端口
 *若是已安装trojan 或第二次使用脚本，请先执行卸载trojan
 ==================================================
 1. 安装 BBR-PLUS 加速4合一脚本

 2. 安装 trojan 和 nginx 不支持CDN
 3. 修复证书 并继续安装 trojan
 4. 升级 trojan 到最新版本
 5. 卸载 trojan 与 nginx

 6. 安装 trojan-go 和 nginx 不支持CDN, 不开启websocket (兼容trojan客户端)
 7. 修复证书 并继续安装 trojan-go 不支持CDN, 不开启websocket
 8. 安装 trojan-go 和 nginx 支持CDN, 开启websocket (兼容trojan客户端, 但不兼容websb'ocket)\x1b[0m\r\n\x1b[32m\x1b[01m 9. \xe4\xbf\xae\xe5\xa4\x8d\xe8\xaf\x81\xe4\xb9\xa6 \xe5\xb9\xb6\xe7\xbb\xa7\xe7\xbb\xad\xe5\xae\x89\xe8\xa3\x85 trojan-go \xe6\x94\xaf\xe6\x8c\x81CDN, \xe5\xbc\x80\xe5\x90\xafwebsocket \x1b[0m\r\n\x1b[32m\x1b[01m 10. \xe5\x8d\x87\xe7\xba\xa7 trojan-go \xe5\x88\xb0\xe6\x9c\x80\xe6\x96\xb0\xe7\x89\x88\xe6\x9c\xac\x1b[0m\r\n\x1b[31m\x1b[01m 11. \xe5\x8d\xb8\xe8\xbd\xbd trojan-go \xe4\xb8\x8e nginx\x1b[0m\r\n\r\n\x1b[32m\x1b[01m 12. \xe5\xae\x89\xe8\xa3\x85 v2ray\xe6\x88\x96xray \xe5\x92\x8c nginx, \xe6\x94\xaf\xe6\x8c\x81 websocket tls1.3, \xe6\x94\xaf\xe6\x8c\x81CDN\x1b[0m\r\n\x1b[32m\x1b[01m 13. \xe5\x8d\x87\xe7\xba\xa7 v2ray\xe6\x88\x96xray \xe5\x88\xb0\xe6\x9c\x80\xe6\x96\xb0\xe7\x89\x88\xe6\x9c\xac\x1b[0m\r\n\x1b[31m\x1b[01m 14. \xe5\x8d\xb8\xe8\xbd\xbdv2ray\xe6\x88\x96xray \xe5\x92\x8c nginx\x1b[0m\r\n\r\n\x1b[32m\x1b[01m 15. \xe5\x90\x8c\xe6\x97\xb6\xe5\xae\x89\xe8\xa3\x85 trojan + v2ray\xe6\x88\x96xray \xe5\x92\x8c nginx, \xe4\xb8\x8d\xe6\x94\xaf\xe6\x8c\x81CDN\x1b[0m\r\n\x1b[32m\x1b[01m 16. \xe5\x8d\x87\xe7\xba\xa7 v2ray\xe6\x88\x96xray \xe5\x92\x8c trojan \xe5\x88\xb0\xe6\x9c\x80\xe6\x96\xb0\xe7\x89\x88\xe6\x9c\xac\x1b[0m\r\n\x1b[31m\x1b[01m 17. \xe5\x8d\xb8\xe8\xbd\xbd trojan, v2ray\xe6\x88\x96xray \xe5\x92\x8c nginx\x1b[0m\r\n\x1b[32m\x1b[01m 18. \xe5\x90\x8c\xe6\x97\xb6\xe5\xae\x89\xe8\xa3\x85 trojan-go + v2ray\xe6\x88\x96xray \xe5\x92\x8c nginx, \xe4\xb8\x8d\xe6\x94\xaf\xe6\x8c\x81CDN\x1b[0m\r\n\x1b[32m\x1b[01m 19. \xe5\x90\x8c\xe6\x97\xb6\xe5\xae\x89\xe8\xa3\x85 trojan-go + v2ray\xe6\x88\x96xray \xe5\x92\x8c nginx, trojan-go \xe5\x92\x8c v2ray \xe9\x83\xbd\xe6\x94\xaf\xe6\x8c\x81CDN\x1b[0m\r\n\x1b[32m\x1b[01m 20. \xe5\x8d\x87\xe7\xba\xa7 v2ray\xe6\x88\x96xray \xe5\x92\x8c trojan-go \xe5\x88\xb0\xe6\x9c\x80\xe6\x96\xb0\xe7\x89\x88\xe6\x9c\xac\x1b[0m\r\n\x1b[31m\x1b[01m 21. \xe5\x8d\xb8\xe8\xbd\xbd trojan-go, v2ray\xe6\x88\x96xray \xe5\x92\x8c nginx\x1b[0m\r\n\r\n\x1b[32m\x1b[01m 28. \xe6\x9f\xa5\xe7\x9c\x8b\xe5\xb7\xb2\xe5\xae\x89\xe8\xa3\x85\xe7\x9a\x84\xe9\x85\x8d\xe7\xbd\xae\xe7\x94\xa8\xe6\x88\xb7\xe5\xaf\x86\xe7\xa0\x81\xe4\xbf\xa1\xe6\x81\xaf\x1b[0m\r\n\x1b[32m\x1b[01m 29. \xe5\xae\x89\xe8\xa3\x85 trojan \xe5\x92\x8c v2ray \xe5\x8f\xaf\xe8\xa7\x86\xe5\x8c'b'\x96\xe7\xae\xa1\xe7\x90\x86\xe9\x9d\xa2\xe6\x9d\xbf\x1b[0m\r\n\x1b[32m\x1b[01m 30. \xe4\xb8\x8d\xe5\xae\x89\xe8\xa3\x85nginx,\xe5\x8f\xaa\xe5\xae\x89\xe8\xa3\x85trojan\xe6\x88\x96v2ray,\xe5\x8f\xaf\xe9\x80\x89\xe6\x8b\xa9\xe6\x98\xaf\xe5\x90\xa6\xe5\xae\x89\xe8\xa3\x85SSL\xe8\xaf\x81\xe4\xb9\xa6\x1b[0m\r\n\x1b[32m\x1b[01m ==================================================\x1b[0m\r\n\x1b[32m\x1b[01m 31. \xe5\xae\x89\xe8\xa3\x85OhMyZsh\xe4\xb8\x8e\xe6\x8f\x92\xe4\xbb\xb6zsh-autosuggestions, Micro\xe7\xbc\x96\xe8\xbe\x91\xe5\x99\xa8 \xe7\xad\x89\xe8\xbd\xaf\xe4\xbb\xb6\x1b[0m\r\n\x1b[32m\x1b[01m 32. \xe8\xae\xbe\xe7\xbd\xae\xe5\x8f\xaf\xe4\xbb\xa5\xe4\xbd\xbf\xe7\x94\xa8root\xe7\x99\xbb\xe9\x99\x86\x1b[0m\r\n\x1b[32m\x1b[01m 33. \xe4\xbf\xae\xe6\x94\xb9SSH \xe7\x99\xbb\xe9\x99\x86\xe7\xab\xaf\xe5\x8f\xa3\xe5\x8f\xb7\x1b[0m\r\n\x1b[32m\x1b[01m 34. \xe8\xae\xbe\xe7\xbd\xae\xe6\x97\xb6\xe5\x8c\xba\xe4\xb8\xba\xe5\x8c\x97\xe4\xba\xac\xe6\x97\xb6\xe9\x97\xb4\x1b[0m\r\n\x1b[32m\x1b[01m 41. VPS \xe6\xb5\x8b\xe7\xbd\x91\xe9\x80\x9f\xe5\xb7\xa5\xe5\x85\xb7\x1b[0m\r\n\x1b[32m\x1b[01m 0. \xe9\x80\x80\xe5\x87\xba\xe8\x84\x9a\xe6\x9c\xac\x1b[0m\r\n\r\n\xe8\xaf\xb7\xe8\xbe\x93\xe5\x85\xa5\xe6\x95\xb0\xe5\xad\x97:' `

**Comment by jinwyp** [comment]
vps是什么系统？ 用的什么终端程序。一般更换终端程序可以解决

**Comment by lukemin** [comment]
centos7，终端我用的宝塔面板自带的ssh。

**Comment by jinwyp** [comment]
> centos7，终端我用的宝塔面板自带的ssh。

这脚本最好在干净的系统运行，装了宝塔在运行这个脚本 除非单独只安装v2ray，否则会有问题和宝塔冲突

而且这个是宝塔自带的ssh的问题，如果在命令运行是没有问题的，这个问题我试过了，宝塔ssh终端自己的问题
