### ISSUE TITLE
在ubuntu 18.04上，因为apt源中nginx版本过低会导致安装TLS 1.3相关协议时失败

### ISSUE THREAD

**Issue by MegaStone** [jinwyp/one_click_script#34]
Ubuntu 18.04上nginx版本是1.14，尚不支持TLS 1.3。nginx conf文件中的ssl_early_data导致nginx启动失败。
建议加入对nginx版本检测的功能。版本过低的话，add-apt-repository ppa:nginx/stable

**Comment by jinwyp** [comment]
已修改  使用 add-apt-repository ppa:nginx/stable 安装nginx， 同时不支持 openssl 1.1.1 的 用tls1.2 作为候补
