### ISSUE TITLE
Nginx报错，网站打不开。

### ISSUE THREAD

**Issue by xifeng0** [jinwyp/one_click_script#36]
[emerg] unknown directive "ssl_early_data" in /etc/nginx/nginx.conf:34

**Comment by xifeng0** [comment]
发现网站打不开后看了看Nginx的状态是启动失败的。发现了这个错误。请问下该怎么解决

**Comment by znlppa** [comment]
同样的报错
我的是纯净安装，刚装完打开也是报相同的错误 nginx: [emerg] unknown directive "ssl_early_data" in /etc/nginx/nginx.conf:34

**Comment by jinwyp** [comment]
已修改 去掉了ssl_early_data， 避免不同系统不支持openssl 1.1.1 导致nginx 启动失败。 可以删除卸载 后 重新更新脚本安装即可

**Comment by znlppa** [comment]
问题解决了。参照方法手动修改# 注释掉 /etc/nginx/nginx.conf 配置文件中ssl_early_data这一行后就可以正常启动nginx了。谢谢。

**Comment by xifeng0** [comment]
![1](https://user-images.githubusercontent.com/76558682/105629340-6eeed180-5e7d-11eb-9991-b311b5ebbd03.png)
卸载后重新使用脚本安装，Nginx无法正常安装。

**Comment by xifeng0** [comment]
提示是安装完成了。实际上，etc下并没有nginx目录

**Comment by jinwyp** [comment]
> 提示是安装完成了。实际上，etc下并没有nginx目录

选的第几项目 ，什么系统， 或者重新重置个机器装一下， 

nginx启动不成功不影响 Trojan运行，只要证书申请成功 trojan一样运行正常， 只是没有伪装网站，可以自行安装nginx

**Comment by xifeng0** [comment]
> > 提示是安装完成了。实际上，etc下并没有nginx目录
> 
> 选的第几项目，什么系统，或重新重置个机器装一下，
> 
> nginx启动不成功不影响Trojan运行，只要证书申请成功trojan一样运行正常，只是没有伪装网站，可以自行安装nginx

![1](https://user-images.githubusercontent.com/76558682/105632806-25f44880-5e90-11eb-99ea-d39704eb0ca7.png)
选的是12.我装V2RAY。

**Comment by jinwyp** [comment]
> > > 提示是安装完成了。实际上，etc下并没有nginx目录
> > 
> > 
> > 选的第几项目，什么系统，或重新重置个机器装一下，
> > nginx启动不成功不影响Trojan运行，只要证书申请成功trojan一样运行正常，只是没有伪装网站，可以自行安装nginx
> 
> ![1](https://user-images.githubusercontent.com/76558682/105632806-25f44880-5e90-11eb-99ea-d39704eb0ca7.png)
> 选的是12.我装V2RAY。

确定nginx 是否安装 可以 apt-get install nginx 重新安装 
然后如果能看懂 nginx 配置 可以手动修改 /etc/nginx/nginx/conf 

可以参考 脚本 https://github.com/jinwyp/one_click_script/blob/master/trojan_v2ray_install.sh 850行开始

然后systemctl restart nginx 
如果启动成功 可以 通过 systemctl status nginx 查看状态是否启动成功

如果不行就重置系统 重新安装把

因为选第12项 的v2ray 是nginx 提供的tls 加密 ， v2ray只是裸跑一个vmess或vless 
nginx 通过转发路径可以端口到v2ray的端口 如果看不懂nginx配置只能重置重装了

**Comment by xifeng0** [comment]
> > > > 提示是安装完成了。实际上，etc下并没有nginx目录
> > > 
> > > 
> > > 选的第几项目，什么系统，或重新重置个机器装一下，
> > > nginx启动不成功不影响Trojan运行，只要证书申请成功trojan一样运行正常，只是没有伪装网站，可以自行安装nginx
> > 
> > 
> > ![1](https://user-images.githubusercontent.com/76558682/105632806-25f44880-5e90-11eb-99ea-d39704eb0ca7.png)
> > 选的是12.我装V2RAY。
> 
> 确定nginx 是否安装 可以 apt-get install nginx 重新安装
> 然后如果能看懂 nginx 配置 可以手动修改 /etc/nginx/nginx/conf
> 
> 可以参考 脚本 https://github.com/jinwyp/one_click_script/blob/master/trojan_v2ray_install.sh 850行开始
> 
> 然后systemctl restart nginx
> 如果启动成功 可以 通过 systemctl status nginx 查看状态是否启动成功
> 
> 如果不行就重置系统 重新安装把
> 
> 因为选第12项 的v2ray 是nginx 提供的tls 加密 ， v2ray只是裸跑一个vmess或vless
> nginx 通过转发路径可以端口到v2ray的端口 如果看不懂nginx配置只能重置重装了

重置后安装成功了！感谢。
