### ISSUE TITLE
修改配置文件就报错启动不了

### ISSUE THREAD

**Issue by 759583695** [jinwyp/one_click_script#37]
● v2ray.service - V2Ray
   Loaded: loaded (/usr/lib/systemd/system/v2ray.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2021-01-24 18:42:24 CST; 2s ago
     Docs: https://www.v2fly.org/
  Process: 65962 ExecStart=/root/v2ray/v2ray -config /root/v2ray/config.json (code=exited, status=2)
 Main PID: 65962 (code=exited, status=2)

Jan 24 18:42:24 baron systemd[1]: v2ray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 24 18:42:24 baron systemd[1]: v2ray.service: Failed with result 'exit-code'.
Jan 24 18:42:24 baron systemd[1]: v2ray.service: Service RestartSec=100ms expired, scheduling restart.
Jan 24 18:42:24 baron systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
Jan 24 18:42:24 baron systemd[1]: Stopped V2Ray.
Jan 24 18:42:24 baron systemd[1]: v2ray.service: Start request repeated too quickly.
Jan 24 18:42:24 baron systemd[1]: v2ray.service: Failed with result 'exit-code'.
Jan 24 18:42:24 baron systemd[1]: Failed to start V2Ray.

**Comment by jinwyp** [comment]
选的第几项安装的？ 什么系统？

**Comment by 759583695** [comment]
系统：CentOS SELinux 8 x64
 30. 不安装nginx,只安装trojan或v2ray,可选择是否安装SSL证书
 我只安了v2ray

**Comment by 759583695** [comment]
{
  "log" : {
    "access": "/root/v2ray-access.log",
    "error": "/root/v2ray-error.log",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "port": 12345,
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "efc33655-6a17-41f2-a6f4-132f9f8b21ba",
            "level": 0,
            "email": "password11@gmail.com"
          },
          {
            "id": "6e463e6c-c3c5-42a9-b213-826446b6acef",
            "level": 0,
            "email": "password12@gmail.com"
          },
          {
            "id": "c9c95f9d-4694-4277-8c92-5e8c74321bc1",
            "level": 0,
            "email": "password13@gmail.com"
          },
          {
            "id": "9bc49be3-06d5-4628-afe5-7c17a1b26ff0",
            "level": 0,
            "email": "password14@gmail.com"
          },
          {
            "id": "ca13d5c8-b47d-4dca-9f29-bfd95834766f",
            "level": 0,
            "email": "password15@gmail.com"
          },
          {
            "id": "e1a29994-b1c7-4101-991e-eb950a5d420b",
            "level": 0,
            "email": "password16@gmail.com"
          },
          {
            "id": "4c2997f0-9ad8-4b2f-ad56-d20fc296b87f",
            "level": 0,
            "email": "password17@gmail.com"
          },
          {
            "id": "87849821-7c71-4fae-8fa1-f28512a5d794",
            "level": 0,
            "email": "password18@gmail.com"
          },
          {
            "id": "6eb3777c-8c64-4c23-a231-0d5700a69c7d",
            "level": 0,
            "email": "password19@gmail.com"
          },
          {
            "id": "f76427ac-4332-41ab-a2a2-03443be9b31c",
            "level": 0,
            "email": "password20@gmail.com"
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/ed647ff1"
        }
      }
    }
  ],
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "blocked",
      "protocol": "blackhole",
      "settings": {}
    }
  ]
}
1、原来配置文件是这样的，，，，我改个端口也不行，改删除id 下面的邮箱也不行，就是一样都不能改 改了就启动不了
2、其他的都没动，  然后我保存安装生成的配置文件，重新改配置文件后启动不了，又复制原来的配置文件进去还是启动不了
3、大概就是这个配置文件动不得

**Comment by jinwyp** [comment]
> {
> "log" : {
> "access": "/root/v2ray-access.log",
> "error": "/root/v2ray-error.log",
> "loglevel": "warning"
> },
> "inbounds": [
> {
> "port": 12345,
> "protocol": "vmess",
> "settings": {
> "clients": [
> {
> "id": "efc33655-6a17-41f2-a6f4-132f9f8b21ba",
> "level": 0,
> "email": "[password11@gmail.com](mailto:password11@gmail.com)"
> },
> {
> "id": "6e463e6c-c3c5-42a9-b213-826446b6acef",
> "level": 0,
> "email": "[password12@gmail.com](mailto:password12@gmail.com)"
> },
> {
> "id": "c9c95f9d-4694-4277-8c92-5e8c74321bc1",
> "level": 0,
> "email": "[password13@gmail.com](mailto:password13@gmail.com)"
> },
> {
> "id": "9bc49be3-06d5-4628-afe5-7c17a1b26ff0",
> "level": 0,
> "email": "[password14@gmail.com](mailto:password14@gmail.com)"
> },
> {
> "id": "ca13d5c8-b47d-4dca-9f29-bfd95834766f",
> "level": 0,
> "email": "[password15@gmail.com](mailto:password15@gmail.com)"
> },
> {
> "id": "e1a29994-b1c7-4101-991e-eb950a5d420b",
> "level": 0,
> "email": "[password16@gmail.com](mailto:password16@gmail.com)"
> },
> {
> "id": "4c2997f0-9ad8-4b2f-ad56-d20fc296b87f",
> "level": 0,
> "email": "[password17@gmail.com](mailto:password17@gmail.com)"
> },
> {
> "id": "87849821-7c71-4fae-8fa1-f28512a5d794",
> "level": 0,
> "email": "[password18@gmail.com](mailto:password18@gmail.com)"
> },
> {
> "id": "6eb3777c-8c64-4c23-a231-0d5700a69c7d",
> "level": 0,
> "email": "[password19@gmail.com](mailto:password19@gmail.com)"
> },
> {
> "id": "f76427ac-4332-41ab-a2a2-03443be9b31c",
> "level": 0,
> "email": "[password20@gmail.com](mailto:password20@gmail.com)"
> }
> ],
> "decryption": "none"
> },
> "streamSettings": {
> "network": "ws",
> "wsSettings": {
> "path": "/ed647ff1"
> }
> }
> }
> ],
> "outbounds": [
> {
> "tag": "direct",
> "protocol": "freedom",
> "settings": {}
> },
> {
> "tag": "blocked",
> "protocol": "blackhole",
> "settings": {}
> }
> ]
> }
> 1、原来配置文件是这样的，，，，我改个端口也不行，改删除id 下面的邮箱也不行，就是一样都不能改 改了就启动不了
> 2、其他的都没动， 然后我保存安装生成的配置文件，重新改配置文件后启动不了，又复制原来的配置文件进去还是启动不了
> 3、大概就是这个配置文件动不得

我用你这个配置文件 xray 内核启动成功 没有报错

建议你用vscode 或 sublime 等专门的编辑器编辑好后 粘贴到配置文件里
应该是修改后的文件格式有问题，email不能重复 等等
