### ISSUE TITLE
由于挖掘加密货币（挖矿），与您的项目关联的资源因违反我们的免费试用服务条款而被暂停。

### ISSUE THREAD

**Issue by xifeng0** [jinwyp/one_click_script#38]
已经被封2个机器了。前天搭了一个，用一天被封。昨天搭了个还没到一天，就被封了
![QQ图片20210126172953](https://user-images.githubusercontent.com/76558682/105827277-bd76aa00-5ffc-11eb-826a-df7c228d2810.png)
使用脚本12搭建，用32解锁ROOT登录，套用了CF的CDN。
这里被封前，机器CPU莫名的占用变的很高。
![2](https://user-images.githubusercontent.com/76558682/105827644-337b1100-5ffd-11eb-8a1f-e3333374ed6b.png)

**Comment by xifeng0** [comment]
是我弱口令被扫了吗😂？我不解锁root登录再搭一个试试

**Comment by jinwyp** [comment]
不要用root和密码登录 用公钥私钥 把密码登录关了

**Comment by xifeng0** [comment]
> 不要用root和密码登录 用公钥私钥 把密码登录关了

现在啥都没开，就用谷歌自己托管的密钥登录。。看看情况吧。

**Comment by sxx1314** [comment]
比较奇葩 最近也遇到了。。。并且一直都是key登录。
