### ISSUE TITLE
安装bbr后 三个启动项都不能启动了

### ISSUE THREAD

**Issue by gangmain** [jinwyp/one_click_script#39]
vultr 的centos8 在用脚本安装bbr时  bbr plus 和bbr魔改版重启后都不发进入系统。用自带console进去看到三个启动项，不管选哪个都不发正常启动系统。

**Comment by jinwyp** [comment]
有些VPS 无法正常安装bbr plus， 安装后无法启动 只能重装系统
建议选择centos7 或 ubuntu (不带bbr的系统 例如搬瓦工选择了带bbr的系统反而无法安装) 安装bbr plus  ，
或者不安装bbr plus 直接使用原版的bbr， 就是很多VPS 的系统自带安装了bbr 但没有启用，通过脚本的菜单启用原版bbr即可

或者换VPS主机商，例如google cloud 没有任何问题，大厂在虚拟化内核这块做的还是厉害
