### ISSUE TITLE
這是什麼情況

### ISSUE THREAD

**Issue by sdd-cn** [jinwyp/one_click_script#4]
chmod: cannot access 'x': No such file or directory

**Comment by jinwyp** [comment]
运行的第几项？

**Comment by sdd-cn** [comment]
wget --no-check-certificate https://raw.githubusercontent.com/jinwyp/one_click_script/master/trojan_v2ray_install.sh && chmod +x trojan_v2ray_install.sh && ./trojan_v2ray_install.sh

**Comment by sdd-cn** [comment]
權限要在記事本下編輯一下 空格

**Comment by sdd-cn** [comment]
chmod + x

**Comment by jinwyp** [comment]
我运行 
wget --no-check-certificate https://raw.githubusercontent.com/jinwyp/one_click_script/master/trojan_v2ray_install.sh && chmod +x trojan_v2ray_install.sh && ./trojan_v2ray_install.sh

没问题啊， 你是在什么系统运行的？ 必须是linux系统才可以
