### ISSUE TITLE
请问大佬，如果想使用多个二级域名，nginx应该如何设置

### ISSUE THREAD

**Issue by kingsea0-0** [jinwyp/one_click_script#40]
首先感谢大佬的脚本，非常简单好用。请教大佬一个问题，对web不是很熟悉，请见谅。

目前我搭建好了trojan-go + ws 。现在我想使用多个二级域名来区分流量是否走cdn，比如客户端使用www.abc.com域名走直连，使用cdn.abc.com域名走cdn。因为申请证书的时候使用的是www域名申请的，现在我直接在nginx.conf的servename中加入cdn域名，cloudflare这边提示525错误，应该是证书验证不通过。所以想问一下nginx应该如何设置，能让两个二级域名用同一个trojan服务。感谢大佬

**Comment by jinwyp** [comment]
这个问题本质是同一个IP 上 使用nginx 支持多个 https 443 端口的虚拟主机

在原来的时候nginx是不支持的， 后来加入SNI功能

默认nginx是不开启 SNI 需要自己编译安装nginx 

具体可以搜索相关 NGINX SNI  和 同一个IP 支持多个 https 虚拟主机 

例如
https://www.jianshu.com/p/d40e249774ff
