### ISSUE TITLE
求救一下xray内核每次用脚本更新后就无法使用了

### ISSUE THREAD

**Issue by shinanzhuomo** [jinwyp/one_click_script#42]
![Screenshot_20210201-044701](https://user-images.githubusercontent.com/36750785/106397461-8f53f880-6448-11eb-871d-4637c22fc5d8.jpg)
一模一样的配置重新装一次才能正常用。。

**Comment by jinwyp** [comment]
1 选的第几项安装的？
2 选的第几项更新的？

**Comment by shinanzhuomo** [comment]
> 1选的第几项安装的？？
> 2选的第几项更新的？？
> 
> 已修复，可以重新下载脚本然后运行更新xray即可，
> 
> 手动修复运行下面命令增加权限后 重新启动xray立即
> chmod + x / root / v2ray / xray
> systemctl重新启动xray
> 
> 查看状态
> systemctl状态x射线

![image](https://user-images.githubusercontent.com/36750785/106534431-0499f900-652f-11eb-9c13-b12bc902d4d1.png)
谢谢大大  不过又了另外的问题 更新脚本的时候报这个错误 这个会有影响吗

**Comment by jinwyp** [comment]
> > 1选的第几项安装的？？
> > 2选的第几项更新的？？
> > 已修复，可以重新下载脚本然后运行更新xray即可，
> > 手动修复运行下面命令增加权限后 重新启动xray立即
> > chmod + x / root / v2ray / xray
> > systemctl重新启动xray
> > 查看状态
> > systemctl状态x射线
> 
> ![image](https://user-images.githubusercontent.com/36750785/106534431-0499f900-652f-11eb-9c13-b12bc902d4d1.png)
> 谢谢大大 不过又了另外的问题 更新脚本的时候报这个错误 这个会有影响吗

更新源后 某些sqllite 下载出现问题，就是没更新成功不过不影响，没更新也可以正常用

**Comment by shinanzhuomo** [comment]
> > > 1选的第几项安装的？？
> > > 2选的第几项更新的？？
> > > 已修复，可以重新下载脚本然后运行更新xray即可，
> > > 手动修复运行下面命令增加权限后 重新启动xray立即
> > > chmod + x / root / v2ray / xray
> > > systemctl重新启动xray
> > > 查看状态
> > > systemctl状态x射线
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/36750785/106534431-0499f900-652f-11eb-9c13-b12bc902d4d1.png)
> > 谢谢大大 不过又了另外的问题 更新脚本的时候报这个错误 这个会有影响吗
> 
> 更新源后 某些sqllite 下载出现问题，就是没更新成功不过不影响，没更新也可以正常用

谢谢！
