### ISSUE TITLE
debian10 安装 xray + cdn  时 安装的nginx 版本为较老的 1.14，此时nginx启动会出错，需要更新nginx 到1.18 才能正常

### ISSUE THREAD

**Issue by tanpengsccd** [jinwyp/one_click_script#46]
参考这个 https://joshtronic.com/2018/12/17/how-to-install-the-latest-nginx-on-debian-and-ubuntu/ 
更新nginx 到最新版

**Comment by jinwyp** [comment]
已经修改了， 可以测试一下有没有问题，

nginx 无法启动是因为 低版本的nginx 由于 某个tls1.3的指令问题 
https://github.com/jinwyp/one_click_script/issues/36

**Comment by tanpengsccd** [comment]
OK。测试OK了。
