### ISSUE TITLE
 选项“9. 修复证书 并继续安装 trojan-go 支持CDN, 开启websocket” 不会修改对应 host 的值

### ISSUE THREAD

**Issue by tanpengsccd** [jinwyp/one_click_script#47]
比如 我第一次安装 是 选项8，输入的域名是 a.baidu.com，一切顺利。
后面我又想改为b.baidu.com,  此时我再选择”9. 修复证书 并继续安装 trojan-go 支持CDN, 开启websocket“。
发现
/etc/nginx/nginx.conf
/root/trojan-go/server.json
里的配置域名没有修改为b.baidu.com，依然是a.baidu.com，不知道这算不是bug。

**Comment by jinwyp** [comment]
修复证书的意思是必须域名相同的情况下，由于之前证书申请失败 需要重新申请证书

如果是换域名直接卸载重装即可
