### ISSUE TITLE
阿里云centos7.8执行命令12安装Nginx失败

### ISSUE THREAD

**Issue by kevinkind** [jinwyp/one_click_script#48]

**Comment by kevinkind** [comment]
File contains parsing errors: file:///etc/yum.repos.d/nginx.repo
	[line  6]: EOF        

	[line 31]: cat <<EOF >> /etc/apt/sources.list.d/nginx.list

Loaded plugins: fastestmirror


File contains parsing errors: file:///etc/yum.repos.d/nginx.repo
	[line  6]: EOF        

	[line 31]: cat <<EOF >> /etc/apt/sources.list.d/nginx.list

Loaded plugins: fastestmirror


File contains parsing errors: file:///etc/yum.repos.d/nginx.repo
	[line  6]: EOF        

	[line 31]: cat <<EOF >> /etc/apt/sources.list.d/nginx.list

Loaded plugins: fastestmirror


File contains parsing errors: file:///etc/yum.repos.d/nginx.repo
	[line  6]: EOF        

	[line 31]: cat <<EOF >> /etc/apt/sources.list.d/nginx.list

Loaded plugins: fastestmirror


File contains parsing errors: file:///etc/yum.repos.d/nginx.repo
	[line  6]: EOF        

	[line 31]: cat <<EOF >> /etc/apt/sources.list.d/nginx.list

**Comment by jinwyp** [comment]
已修复 请重新下载运行脚本
