### ISSUE TITLE
ubuntu 18 Nginx安装失败

### ISSUE THREAD

**Issue by hunao0221** [jinwyp/one_click_script#49]
================================================== 
     开始安装 Web服务器 nginx !
 ================================================== 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  fontconfig-config fonts-dejavu-core libfontconfig1 libgd3 libjbig0 libjpeg-turbo8 libjpeg8 libnginx-mod-http-geoip libnginx-mod-http-image-filter libnginx-mod-http-xslt-filter
  libnginx-mod-mail libnginx-mod-stream libtiff5 libwebp6 libxpm4 nginx-common nginx-core
Suggested packages:
  libgd-tools fcgiwrap nginx-doc ssl-cert
The following NEW packages will be installed:
  fontconfig-config fonts-dejavu-core libfontconfig1 libgd3 libjbig0 libjpeg-turbo8 libjpeg8 libnginx-mod-http-geoip libnginx-mod-http-image-filter libnginx-mod-http-xslt-filter
  libnginx-mod-mail libnginx-mod-stream libtiff5 libwebp6 libxpm4 nginx nginx-common nginx-core
0 upgraded, 18 newly installed, 0 to remove and 0 not upgraded.
Need to get 153 kB/2462 kB of archives.
After this operation, 8210 kB of additional disk space will be used.
Ign:1 http://asia-east2-a.gce.clouds.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libtiff5 amd64 4.0.9-5ubuntu0.3
Err:1 http://security.ubuntu.com/ubuntu bionic-updates/main amd64 libtiff5 amd64 4.0.9-5ubuntu0.3
  404  Not Found [IP: 91.189.88.246 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/t/tiff/libtiff5_4.0.9-5ubuntu0.3_amd64.deb  404  Not Found [IP: 91.189.88.246 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Failed to enable unit: Unit file nginx.service does not exist.
Failed to stop nginx.service: Unit nginx.service not loaded.
./trojan_v2ray_install.sh: line 831: /etc/nginx/nginx.conf: No such file or directory

**Comment by jinwyp** [comment]
已修复 请重新下载脚本运行
