### ISSUE TITLE
V2ray的文件地址是否改动了？

### ISSUE THREAD

**Issue by cogitate3** [jinwyp/one_click_script#5]
自动升级时，v2ray升级不成功，提示如下：

==========================================
       开始升级 V2ray Version:  !
==========================================
--2020-07-27 03:45:28--  https://github.com/v2ray/v2ray-core/releases/download/v/v2ray-linux-64.zip
Resolving github.com (github.com)... 140.82.112.3
Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-07-27 03:45:29 ERROR 404: Not Found.

Archive:  /root/v2ray/upgrade/v2ray-linux-64.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /root/v2ray/upgrade/v2ray-linux-64.zip or
        /root/v2ray/upgrade/v2ray-linux-64.zip.zip, and cannot find /root/v2ray/upgrade/v2ray-linux-64.zip.ZIP, period.
mv: cannot stat '/root/v2ray/upgrade/v2ray': No such file or directory
mv: cannot stat '/root/v2ray/upgrade/v2ctl': No such file or directory
       升级成功!

v2ray项目已经搬迁到v2fly，最新版的v2ray地址是否需要改动？请大神参考。

**Comment by jinwyp** [comment]
已修复脚本

这是因为某些网络原因 没有获取到v2ray的版本号， 已经换了一种获取版本号的方法

正常地址是v后面应该有v4.26.0这样的版本号，由于最新版本号获取失败导致下载失败。  
https://github.com/v2ray/v2ray-core/releases/download/v4.26.0/v2ray-linux-64.zip


其他地址没有改变
