### ISSUE TITLE
客户端"address"填Cloudflare CDN无法连接

### ISSUE THREAD

**Issue by very20101** [jinwyp/one_click_script#51]
v2ray, Xray, trojan-go 客户端"address"填Cloudflare CDN无法连接，且无log 输出。xray-ws-tls客户端配置如下：

{
"log": {
    "access": "～/v2ray/access.log",
    "error": "～/v2ray/error.log",
    "loglevel": "warning"
  },

"inbounds": [
        {
            "port": 10800,
            "listen": "127.0.0.1",
            "protocol": "socks",
            "settings": {
                "udp": true
            }
        }
    ],
    "outbounds": [
        {
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "x.y.z", 
                        "port": 443,
                        "users": [
                            {
                                "id": "xxx-xxx-xxx", 
                                "encryption": "none",
                                "level": 0
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "security": "tls",
                "tlsSettings": {
                    "serverName": "a.b.c" 
                },
                "wsSettings": {
                    "path": "/xxxx" 
                }
            }
        }
    ]
}

当x.y.z 填Cloudflare CDN ip时，没网络连接，也没log输出，当x.y.z填自己的域名a.b.c 时可以正常联网。请问在ws-tls 模式下x.y.z 是否只能填自己的域名？如果填Cloudflare CDN ip，该如何设置？

**Comment by jinwyp** [comment]
1 你用的第几项安装的？
2 每个客户端设置不同，例如v2rayN 中 地址填写 实际的CDN ip ，然后伪装域名需要填入原来的域名, 但其他的客户端方法也不一样

**Comment by very20101** [comment]
脚本的第12项和第19项均试过。客户端就是X-ray或trojan-go的源文件，命令行启动，没有用其它的客户端。操作系统时macOS 10.13.6 或10.15.6。

**Comment by jinwyp** [comment]
> 脚本的第12项和第19项均试过。客户端就是X-ray或trojan-go的源文件，命令行启动，没有用其它的客户端。操作系统是macOS 10.13.6 或10.15.6。

这里有问题要解释一下
1 当开启Cloudflare CDN后， 直接仅仅填写https域名后 就已经是走CDN了, 你可以ping 一下的域名看看是不是已经不是你原来VPS的IP了, 

2 填写优选的CDN IP 必须同时填写域名，否则CDN怎么知道你访问的是哪个网站？  所以只填入IP肯定是不对的配置。

v2rayN 是windows 客户端，例如v2rayN 中 地址填写 实际的CDN ip ，然后伪装域名需要填入原来的域名

其他客户端和命令行具体怎么操作不太清楚，你可以找个windows 用v2rayN 试一下 . 
但 CDN的 IP 和 你的https域名肯定要同时填写的,  

同时Cloudflare CDN 里面需要打开CDN 选项， 而且还要填入worker 的脚本 才可以

**Comment by very20101** [comment]
多谢！我找个windows客户端试试
