### ISSUE TITLE
域名伪装网站可以改吗？

### ISSUE THREAD

**Issue by WarrenTrump** [jinwyp/one_click_script#53]
您好，
请问域名伪装网站可以更换吗。
现在这个好像就是个空模板，这样会不安全吗？

谢谢

**Comment by jinwyp** [comment]
直接替换 /root/website/html下面内容即可

**Comment by WarrenTrump** [comment]
> 直接替换 /root/website/html下面内容即可 

好的！
感谢大佬的脚本！
辛苦！
