### ISSUE TITLE
xray能连但trojan连不上，是配置不对吗？

### ISSUE THREAD

**Issue by flywhc** [jinwyp/one_click_script#55]
选择“15 同时安装trojan和xray”，安装完用提示里那个v2rayN for windows，按照提示添加xray没有问题，除了流控为空没提示。不需要设置密码

然后再设置trojan却连不上，我的配置是：

服务器地址：按照提示，与xray的一模一样
服务器端口：也跟xray一样的443
密码：abcdefg2020103e3b8372d0  (提示里说，选其中一个密码7: 3e3b8372d0，"您选择的前缀 abcdefg202010到abcdefg202099都可以使用")
域名SNI：设置成跟服务器地址一样

我还试过ios的91vpn，也是连不上，我是这样设置的：
所有的server address, SNI adress和Hosts都写一样的服务器地址。
 enable TLS = true,
ALPN= http/1.1
stream network: http
http path: /

**Comment by jinwyp** [comment]
密码错了  
密码7  3e3b8372d0 
或者 密码是 abcdefg202010

不能是 abcdefg2020103e3b8372d0 

带前缀的密码就是你指定的密码  abcdefg202010 - abcdefg202099。   不带随机数的密码 否则还叫什么指定的密码啊！
带前缀的密码就是你自己能记住的密码 可以给多个设备使用，  如果带随机数的密码那么你必须每次要查看配置，多麻烦啊！

**Comment by flywhc** [comment]
哦，原来是完全没有关系的两组密码，这两组一共一百多个密码，随便一个都能登录

我误解了，因为一般说“前缀密码”是指的密码锁、二次认证系统等等那种两组密码组合起来的密码，目的是加强安全性
