### ISSUE TITLE
ubuntu 18 和 20 下Trojan 0.8.3 无法连接？

### ISSUE THREAD

**Issue by iJayscn** [jinwyp/one_click_script#56]
ubuntu 18 和 20 下Trojan 0.8.3 无法连接？

客户端 V2rayN

Vless 正常。

原系统是 18.04，无法运行升级到20.04，还是一样。

全新系统仅使用此脚本安装

web站点访问也是正常

其他的debian10  debian9 centos8都正常。。。。

**Comment by iJayscn** [comment]
[FATAL] 2021/04/04 14:41:58 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 13.76.33.118:443: bind: cannot assign requested address
[FATAL] 2021/04/04 14:42:08 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 13.76.33.118:443: bind: cannot assign requested address
[FATAL] 2021/04/04 14:42:18 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 13.76.33.118:443: bind: cannot assign requested address
[FATAL] 2021/04/04 14:42:29 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 13.76.33.118:443: bind: cannot assign requested address
[FATAL] 2021/04/04 14:42:39 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 13.76.33.118:443: bind: cannot assign requested address
[FATAL] 2021/04/04 14:42:49 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 13.76.33.118:443: bind: cannot assign requested address
[FATAL] 2021/04/04 14:42:59 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 13.76.33.118:443: bind: cannot assign requested address
[FATAL] 2021/04/04 14:43:09 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 13.76.33.118:443: bind: cannot assign requested address
[FATAL] 2021/04/04 14:43:20 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 13.76.33.118:443: bind: cannot assign requested address
[FATAL] 2021/04/04 14:43:30 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 13.76.33.118:443: bind: cannot assign requested address
[FATAL] 2021/04/04 14:43:40 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 13.76.33.118:443: bind: cannot assign requested address
[FATAL] 2021/04/04 14:43:50 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 13.76.33.118:443: bind: cannot assign requested address
[FATAL] 2021/04/04 14:44:01 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 13.76.33.118:443: bind: cannot assign requested address
[FATAL] 2021/04/04 14:44:11 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 13.76.33.118:443: bind: cannot assign requested address
[FATAL] 2021/04/04 14:44:21 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 13.76.33.118:443: bind: cannot assign requested address
[FATAL] 2021/04/04 14:44:31 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 13.76.33.118:443: bind: cannot assign requested address
[FATAL] 2021/04/04 14:44:42 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 13.76.33.118:443: bind: cannot assign requested address
[FATAL] 2021/04/04 14:44:52 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 13.76.33.118:443: bind: cannot assign requested address
[FATAL] 2021/04/04 14:45:02 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 13.76.33.118:443: bind: cannot assign requested address
[FATAL] 2021/04/04 14:45:12 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 13.76.33.118:443: bind: cannot assign requested address
[FATAL] 2021/04/04 14:45:23 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 13.76.33.118:443: bind: cannot assign requested address
[FATAL] 2021/04/04 14:45:33 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 13.76.33.118:443: bind: cannot assign requested address
[FATAL] 2021/04/04 14:45:43 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 13.76.33.118:443: bind: cannot assign requested address
[FATAL] 2021/04/04 14:45:53 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:45:54 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:46:04 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:46:15 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:46:25 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:46:35 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:46:45 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:46:56 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:47:06 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:47:16 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:47:26 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:47:37 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:47:47 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:47:57 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:48:07 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:48:18 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:48:28 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:48:38 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:48:48 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:48:59 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:49:09 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:49:19 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:49:29 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:49:37 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:49:47 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:49:57 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:50:08 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:50:18 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use
[FATAL] 2021/04/04 14:50:28 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 listen tcp 0.0.0.0:443: bind: address already in use

**Comment by iJayscn** [comment]
使用随机生成密码不行

使用自定义前缀的密码，可以了

晕。。。。。。。

**Comment by jinwyp** [comment]
选的脚本第几项安装的?

**Comment by iJayscn** [comment]
> 选的脚本第几项安装的?

19

**Comment by jinwyp** [comment]
试了一下 用随机密码也可以访问， 估计是客户端问题 可以选择18 不支持的websocket的模式试试 . 用的v2ray 内核  Trojan 0.8.3

**Comment by iJayscn** [comment]
> 试了一下 用随机密码也可以访问， 估计是客户端问题 可以选择18 不支持的websocket的模式试试 . 用的v2ray 内核 Trojan 0.8.3

好的
