### ISSUE TITLE
亚马逊vps 使用root用户安装选19，会出现申请证书失败的问题

### ISSUE THREAD

**Issue by CookedMeat2** [jinwyp/one_click_script#58]
使用以下命令安装：
curl -O https://raw.githubusercontent.com/jinwyp/one_click_script/master/trojan_v2ray_install.sh && chmod +x ./trojan_v2ray_install.sh && ./trojan_v2ray_install.sh

sudo -i切换到root用户，上面到脚本选择19，申请证书的时候会把证书脚本下载到 /home/ubuntu/.acme.sh/目录下，实际上需要在/home/root/.acme.sh/目录才能成功，后来手动运行命令
 mv /home/ubuntu/.acme.sh/acme.sh  /root/.acme.sh/acme.sh
这样是可以成功的，可是每次这样的话，会比较麻烦，不知道作者是否可以修复下此bug呢？

**Comment by jinwyp** [comment]
https://github.com/acmesh-official/acme.sh/wiki/sudo

不要用sudo

**Comment by akw5454521** [comment]
> https://github.com/acmesh-official/acme.sh/wiki/sudo
> 
> 不要用sudo
> 
> sudo -i 后 主目录已经是/root 下面了, 但证书申请的脚本还是当前用户下, 只能手工复制, 或不要用sudo ,
> 
> 脚本无法修改此问题,因为sudo -i后 已无法知道之前的用户是什么名称

请问下脚本有办法增加专门修复证书的功能吗？我3个月前安装的用着没问题，过了3个月后就提示509错误了，去root/.acme.sh目录下查看文件都是3月前的，不知为啥没续签成功，想手动续一下

**Comment by jinwyp** [comment]
> > https://github.com/acmesh-official/acme.sh/wiki/sudo
> > 不要用sudo
> > sudo -i 后 主目录已经是/root 下面了, 但证书申请的脚本还是当前用户下, 只能手工复制, 或不要用sudo ,
> > 脚本无法修改此问题,因为sudo -i后 已无法知道之前的用户是什么名称
> 
> 请问下脚本有办法增加专门修复证书的功能吗？我3个月前安装的用着没问题，过了3个月后就提示509错误了，去root/.acme.sh目录下查看文件都是3月前的，不知为啥没续签成功，想手动续一下

你可以 看一下 /root/.acme.sh/你的域名 是否有更新的证书 ,如果有 复制到/root/website/cert/ 

如果没有 可以运行 "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh"  续签证书 然后在复制到 /root/website/cert/ 下面

**Comment by akw5454521** [comment]
> > > https://github.com/acmesh-official/acme.sh/wiki/sudo
> > > 不要用sudo
> > > sudo -i 后 主目录已经是/root 下面了, 但证书申请的脚本还是当前用户下, 只能手工复制, 或不要用sudo ,
> > > 脚本无法修改此问题,因为sudo -i后 已无法知道之前的用户是什么名称
> > 
> > 
> > 请问下脚本有办法增加专门修复证书的功能吗？我3个月前安装的用着没问题，过了3个月后就提示509错误了，去root/.acme.sh目录下查看文件都是3月前的，不知为啥没续签成功，想手动续一下
> 
> 你可以 看一下 /root/.acme.sh/你的域名 是否有更新的证书 ,如果有 复制到/root/website/cert/
> 
> 如果没有新的ssl 可以运行 "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" 或 acme.sh --renew -d 你的域名 --force 续签证书 然后在复制到 /root/website/cert/ 下面
> 
> 注意文件名 域名.key改为 private.key 复制到 /root/website/cert/

感谢回复，之前我已经用脚本卸载重装了😅，3个月后再看看吧

**Comment by jinwyp** [comment]
> > > > https://github.com/acmesh-official/acme.sh/wiki/sudo
> > > > 不要用sudo
> > > > sudo -i 后 主目录已经是/root 下面了, 但证书申请的脚本还是当前用户下, 只能手工复制, 或不要用sudo ,
> > > > 脚本无法修改此问题,因为sudo -i后 已无法知道之前的用户是什么名称
> > > 
> > > 
> > > 请问下脚本有办法增加专门修复证书的功能吗？我3个月前安装的用着没问题，过了3个月后就提示509错误了，去root/.acme.sh目录下查看文件都是3月前的，不知为啥没续签成功，想手动续一下
> > 
> > 
> > 你可以 看一下 /root/.acme.sh/你的域名 是否有更新的证书 ,如果有 复制到/root/website/cert/
> > 如果没有新的ssl 可以运行 "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" 或 acme.sh --renew -d 你的域名 --force 续签证书 然后在复制到 /root/website/cert/ 下面
> > 注意文件名 域名.key改为 private.key 复制到 /root/website/cert/
> 
> 感谢回复，之前我已经用脚本卸载重装了😅，3个月后再看看吧


这个自动续签ssl的问题已经修复， 需要重新卸载安装， 之前用的 acme standlone 模式 续签与nginx 80端口冲突， 现在改为webroot模式了
