### ISSUE TITLE
pc可以上网，但是手机无法上网

### ISSUE THREAD

**Issue by eternallyjie** [jinwyp/one_click_script#59]
选择15同时安装trojan和v2ray。v2ray选择xRay+vless。安装过户，PC配置可以上网，但是手机无法上网，无论是安卓(v2RayN)还是ios(小火箭)都无法使用trojan捉v2Ray上网。请问是手机上还需要什么配置吗？

**Comment by jinwyp** [comment]
android 客户端的问题, 可以试试在pc上用v2rayN 成功连接后,用分享二维码的方式 用android 客户端扫码加入.

vless更新频繁,很多配置容易出问题,遇到问题只能到相应的客户端去问问比较好, 实在不行就是用vmess.

**Comment by eternallyjie** [comment]
> android 客户端的问题, 可以试试在pc上用v2rayN 成功连接后,用分享二维码的方式 用android 客户端扫码加入.
> 
> vless更新频繁,很多配置容易出问题,遇到问题只能到相应的客户端去问问比较好, 实在不行就是用vmess.

使用vmess还是一样的，无法在手机端使用。关键是trojan也是一样无法在手机端使用

**Comment by jinwyp** [comment]
可以用v2ray试试 客户端不一定支持xray, 具体去android 客户端去问问  目前 windows v2rayN支持的最好, 而且要注意 v2rayN支持的trojan是原版C语言的trojan 还是 xray的trojan内核 都不一样,  要用对应的客户端.  或单独装某个协议试试.

**Comment by eternallyjie** [comment]
> 可以用v2ray试试 客户端不一定支持xray, 具体去android 客户端去问问 目前 windows v2rayN支持的最好, 而且要注意 v2rayN支持的trojan是原版C语言的trojan 还是 xray的trojan内核 都不一样, 要用对应的客户端. 或单独装某个协议试试.

我发现区别了，手机端不能选择加密方式，要选择none。
