### ISSUE TITLE
希望大大能研发出 Trojan-go+V2ray+Caddy+WS+TSL+CDN的一键脚本，谢谢！

### ISSUE THREAD

**Issue by ChengEast** [jinwyp/one_click_script#6]
希望大大能研发出 Trojan-go+V2ray+Caddy+WS+TSL+CDN的一键脚本，谢谢！

**Comment by jinwyp** [comment]
为什么要用caddy？ caddy 现在没有nginx 好用啊

**Comment by ChengEast** [comment]
caddy简单 6666

**Comment by ChengEast** [comment]
caddy可以自动续签证书，一台VPS上共用证书，同时有 trojan-go和v2ray+WS+TSL，关键还支持CDN，这样安全性可以大大加强

**Comment by jinwyp** [comment]
> caddy可以自动续签证书，一台VPS上共用证书，同时有 trojan-go和v2ray+WS+TSL，关键还支持CDN，这样安全性可以大大加强

我的脚本这些功能都已经支持了， 不需要caddy了， trojan的证书和caddy不能用，trojan要在caddy前面 所以 caddy 的证书没用
