### ISSUE TITLE
error getting ssl certificate 

### ISSUE THREAD

**Issue by samperu** [jinwyp/one_click_script#61]
Hello, I was trying to use your scrpit, but I get this error. thanks for your attention.

![Screenshot_5](https://user-images.githubusercontent.com/78442105/114293977-7d05c480-9a60-11eb-908e-f3aed37d2477.png)

- OS: Ubuntu 20.04
- VPS oracle cloud

**Comment by jinwyp** [comment]
The error show you have installed nginx ,  It is better to install on a new clean system. 

Or choose other mode options to install on a exist nginx web server

**Comment by frashersam** [comment]
Hello, I get the same error, I found that it happen when the port are closed and it can't be port forwarded.
I was using oracle cloud and it happen to me.

maybe could you (jinwyp)  try to use your script in oracle cloud? (they give for free 300 dollars for VM machine) 
Thank for your attention.

**Comment by jinwyp** [comment]
To get ssl certificate, acme.sh need port 80 openning, 

So that you nginx must be stop when to get ssl certificate.
