### ISSUE TITLE
访问nginx管理面板链接 400 错误或者白屏

### ISSUE THREAD

**Issue by LOVEChen** [jinwyp/one_click_script#63]
系统信息: Ubuntu, ubuntu, 20.04.2, 20.04, focal, intel CPU amd64, bash, apt-get, /lib/systemd/system/

访问nginx管理面板链接 400 错误或者白屏

**Comment by jinwyp** [comment]
安装选的哪项啊?

**Comment by LOVEChen** [comment]
> 安装选的哪项啊?

29,安装管理面板 先是升级 发现白了 就全部卸载重新安装 trojan-web 还是不行

**Comment by jinwyp** [comment]
已修复 可以卸载后重新安装trojan-web

手动修复方法:  修改nginx 配置 即可

https://github.com/Jrohy/trojan/wiki/nginx%E9%85%8D%E7%BD%AE

https://github.com/Jrohy/trojan/issues/418
