### ISSUE TITLE
希望能增加自定义port,id,path功能

### ISSUE THREAD

**Issue by jackytj** [jinwyp/one_click_script#64]
希望能增加自定义port,id,path功能。感谢！

**Comment by jinwyp** [comment]
1 port trojan都是443 你想自定义哪个？ 是v2ray的运行的端口吗？还是不安装nginx 只安装trojan或v2ray的端口
2 id是v2ray的密码意思吗？ 那串随机号想自定义？
3 path是websocket的path吗？

**Comment by jackytj** [comment]
是的，就是config.json里的三个字段的值。

**Comment by jinwyp** [comment]
> 是的，就是config.json里的三个字段的值。

是需要自定义v2ray的 运行端口把
trojan 需要改端口吗？

**Comment by jackytj** [comment]
是V2ray的运行端口，Trojan暂时没有需求。自定义运行端口是在不安装Nginx的情况下才有的需求，可以在安装后不用改变原前端的配置。而自定义id和path是为了不改变原有节点的配置。

**Comment by jinwyp** [comment]
已增加 该功能 可以试试 
同时还加了一个额外端口功能 可以与主端口一起使用

**Comment by jackytj** [comment]
好的，非常感谢
