### ISSUE TITLE
trojan-go不稳定，怀疑跟bbrplus或者配置有关

### ISSUE THREAD

**Issue by hunao0221** [jinwyp/one_click_script#65]
System: `centos 7`
kernel： `bbrplus`

#### 安装选项
5. 安装 trojan-go 和 nginx 不支持CDN, 不开启websocket (兼容trojan客户端), trojan-go 运行在443端口

#### issues 
启动trojan go后很快就会连接不上，重启`systemctl restart trojan-go`后又可以，就这样陷入死循环，在trojan-go项目找到两个issue应该是类似的情况，https://github.com/p4gefau1t/trojan-go/issues/286 & https://github.com/p4gefau1t/trojan-go/issues/203

这里有部分服务端日志
![image](https://user-images.githubusercontent.com/11972530/114808349-a2852c00-9dda-11eb-8f35-3828f61e4fa8.png)

不知道这跟服务端的配置有没有关系，还有就是我怀疑跟bbrplus有关系，我这边会试试只打开原版bbr，看问题是否存在。

**Comment by jinwyp** [comment]
用优化脚本 把 文件数限制打开 到无限大

**Comment by hunao0221** [comment]
> 用优化脚本 把 文件数限制打开 到无限大

抱歉， 优化脚本指的是哪一个？

**Comment by jinwyp** [comment]
> > 用优化脚本 把 文件数限制打开 到无限大
> 
> 抱歉， 优化脚本指的是哪一个？

wget --no-check-certificate https://raw.githubusercontent.com/jinwyp/one_click_script/master/install_kernel.sh && chmod +x ./install_kernel.sh && ./install_kernel.sh
