### ISSUE TITLE
VLESS+ gRPC +TLS (support CDN,IPv6) . . .

### ISSUE THREAD

**Issue by M33FT** [jinwyp/one_click_script#67]
Hi . . .

Thanks for your very good script. It's really great.

It's very interesting that you also solved the "Google man-machine verification" discussion in your script. you rock!

May I just ask, when do you support "VLESS + gRPC + TLS [support CDN,IPv6]" in your script ?
Because I really wanted to test gRPC in your script.

Thanks for your good support bro ;-)

**Comment by jinwyp** [comment]
VLess gRPC is a new featrue, 

I will add this feature later in this month

**Comment by jinwyp** [comment]
Add gRPC with nginx  or  gRPC only or gRPC with vless + tls

**Comment by M33FT** [comment]
gRPC with vless + tls
