### ISSUE TITLE
要不要支持ipv6？

### ISSUE THREAD

**Issue by tanpengsccd** [jinwyp/one_click_script#69]
我可以提供一个 GULLO IPV4NAT 带 IPV6 的OVZ小鸡。
y2$ 128M内存 NAT-Chi ，可以支持 Debian 10

**Comment by jinwyp** [comment]
什么意思?

**Comment by tanpengsccd** [comment]
似乎现在不支持ipv6的小鸡。我选择12 输入 了 hostname  但是提示监测到的IP地址不对。因为我是IPV6

**Comment by jinwyp** [comment]
> 似乎现在不支持ipv6的小鸡。我选择12 输入 了 hostname 但是提示监测到的IP地址不对。因为我是IPV6

在输入域名后, 可以选择 不验证 域名 指向的 ip  是否 正确
