### ISSUE TITLE
纪念一下100star了，不知道有没有NaiveProxy需求

### ISSUE THREAD

**Issue by jinwyp** [jinwyp/one_click_script#7]
工具层出不穷 有没有NaiveProxy的需求啊？

**Comment by yaak63** [comment]
有此要求，现在vmess和vless似乎不好使了。

**Comment by NetHeritage** [comment]
naiveproxy本身搭建挺简单的  如果有编译好的caddy2  手动搭建也不需要五分钟   如果能出naiveproxy和trojan(trojan-go) 、v2ray并存的方案就好了
