### ISSUE TITLE
trojan-web升级失败

### ISSUE THREAD

**Issue by LOVEChen** [jinwyp/one_click_script#71]
ubuntu 20
菜单29
请输入数字:2

versionTrojanWeb: 2.10.4
 ==================================================
    开始升级 Trojan-web 可视化管理面板: 2.10.4 !
 ==================================================
--2021-05-31 20:55:49--  https://github.com/Jrohy/trojan/releases/download/v2.10.4/trojan
Resolving github.com (github.com)... 13.114.40.48
Connecting to github.com (github.com)|13.114.40.48|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-05-31 20:55:49 ERROR 404: Not Found.

 ================================================== 
     升级成功 Trojan-web 可视化管理面板: 2.10.4 !
 ==================================================

**Comment by jinwyp** [comment]
已修复 trojan-web的 文件名换了
