### ISSUE TITLE
现在好像没有更新SSL证书的选项了？

### ISSUE THREAD

**Issue by iJayscn** [jinwyp/one_click_script#73]
**Describe the bug** A clear and concise description of what the bug is.
在提出问题前请先自行排除服务器端问题和升级到最新客户端，同时也请通过搜索确认是否有人提出过相同问题。

!!! 请务必提供安装的选择的第几项 !!!
!!! 请务必提供什么操作系统 和用的什么终端 !!!

1. 25、同时安装V2和Trojan 支持CDN

**OS and Terminal:**  系统环境 信息 请务必提供什么操作系统 和用的什么终端 ，还有VPS主机商

- OS: debian
- Version 10
- Terminal : xshell
- VPS  GC

**Comment by jinwyp** [comment]
选择27 卸载后 再重装就行  以前的版本有问题,现在不需要更新ssl证书了, 会自动更新

如果新机器 需要单独申请证书可以选择30后 在选11申请

**Comment by iJayscn** [comment]
> 选择27 卸载后 再重装就行 以前的版本有问题,现在不需要更新ssl证书了, 会自动更新
> 
> 如果新机器 需要单独申请证书可以选择30后 在选11申请

ok
