### ISSUE TITLE
出错了

### ISSUE THREAD

**Issue by lsq726** [jinwyp/one_click_script#76]
wget --no-check-certificate https://raw.githubusercontent.com/jinwyp/one_click_script/master/trojan_v2ray_install.sh && chmod +x ./trojan_v2ray_install.sh && ./trojan_v2ray_install.sh
--2021-06-25 06:39:42--  https://raw.githubusercontent.com/jinwyp/one_click_script/master/trojan_v2ray_install.sh
Auflösen des Hostnamens raw.githubusercontent.com (raw.githubusercontent.com)… 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Verbindungsaufbau zu raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443 … fehlgeschlagen: Das Netzwerk ist nicht erreichbar.
Verbindungsaufbau zu raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443 … fehlgeschlagen: Das Netzwerk ist nicht erreichbar.
Verbindungsaufbau zu raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443 … fehlgeschlagen: Das Netzwerk ist nicht erreichbar.
Verbindungsaufbau zu raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443 … fehlgeschlagen: Das Netzwerk ist nicht erreichbar.
root@srv23077:~# 
root@srv23077:~# curl -O https://raw.githubusercontent.com/jinwyp/one_click_script/master/trojan_v2ray_install.sh && chmod +x ./trojan_v2ray_install.sh && ./trojan_v2ray_install.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Couldn't connect to server

**Describe the bug** A clear and concise description of what the bug is.
在提出问题前请先自行排除服务器端问题和升级到最新客户端，同时也请通过搜索确认是否有人提出过相同问题。

!!! 请务必提供安装的选择的第几项 !!!
!!! 请务必提供什么操作系统 和用的什么终端 !!!

1. 例如选择的第2项 安装trojan

**OS and Terminal:**  系统环境 信息 请务必提供什么操作系统 和用的什么终端 ，还有VPS主机商

- OS: [e.g. Centos]
- Version [e.g. 7]
- Terminal :  例如 Mac的teminal 或 linux ssh 或 zsh 或 Windows putty 或 VPS自带的在线ssh
- VPS  [e.g.  Google Cloud]

**To Reproduce** 复现方法  

Log Info 日志信息： 请提供安装出错的信息
例如xxx

安装完成nginx 是否启动成功，域名的网站是否能正常打开，如果打不开说明nginx安装有问题，请给出nginx安装时输出日志

**Comment by jinwyp** [comment]
你的VPS无法访问github服务器 https://raw.githubusercontent.com/jinwyp/one_click_script/master/trojan_v2ray_install.sh  
服务器的网络问题，不要用国内的服务器
