### ISSUE TITLE
一个问题，虽然感觉和脚本无关，但无奈找不到答案便在此发问。

### ISSUE THREAD

**Issue by prprDog** [jinwyp/one_click_script#77]
从昨天下午开始，通过window和安卓的v2rayN客户端均无法通过自建服务器科学上网。服务器用的是trojan + nginx 无ws和cdn
经过分析发现以下现象：
1.域名能正常访问
2.远程ssh能连上服务器
3.通过服务器端wget url能收到200返回
即然一切看上去都如此正常，为何仅通过代理客户端连不上呢？于是我把服务器的脚本以及trojan和nginx删了一次，用最新的脚本装了一下。发现依旧不行，现象还是以上3点。
如果说是某些东西被封了，能否给个验证方法，好让我死的安心。

**Comment by demoncde** [comment]
同样的问题也发生了

**Comment by iJayscn** [comment]
> 从昨天下午开始，通过window和安卓的v2rayN客户端均无法通过自建服务器科学上网。服务器用的是trojan + nginx 无ws和cdn
> 经过分析发现以下现象：
> 1.域名能正常访问
> 2.远程ssh能连上服务器
> 3.通过服务器端wget url能收到200返回
> 即然一切看上去都如此正常，为何仅通过代理客户端连不上呢？于是我把服务器的脚本以及trojan和nginx删了一次，用最新的脚本装了一下。发现依旧不行，现象还是以上3点。
> 如果说是某些东西被封了，能否给个验证方法，好让我死的安心。

我的自建目前正常，建议重置一下服务器系统，重新安装 试一下。

**Comment by prprDog** [comment]
> > 从昨天下午开始，通过window和安卓的v2rayN客户端均无法通过自建服务器科学上网。服务器用的是trojan + nginx 无ws和cdn
> > 经过分析发现以下现象：
> > 1.域名能正常访问
> > 2.远程ssh能连上服务器
> > 3.通过服务器端wget url能收到200返回
> > 即然一切看上去都如此正常，为何仅通过代理客户端连不上呢？于是我把服务器的脚本以及trojan和nginx删了一次，用最新的脚本装了一下。发现依旧不行，现象还是以上3点。
> > 如果说是某些东西被封了，能否给个验证方法，好让我死的安心。
> 
> 我的自建目前正常，建议重置一下服务器系统，重新安装 试一下。

我用的是onevps，我开始怀疑是不是最近7.1的原因

**Comment by jinwyp** [comment]
http://port.ping.pe/ 用这个网站测试一下443端口是否被封了， 近期好像都是443端口直接被封了。其他端口正常。解决方法一种就是套CDN 或者换端口 ， 换端口更容易被检测 。 
GFW应该是检测不出来直接把443端口给封了

**Comment by prprDog** [comment]
> http://port.ping.pe/ 用这个网站测试一下443端口是否被封了， 近期好像都是443端口直接被封了。其他端口正常。解决方法一种就是套CDN 或者换端口 ， 但换端口更容易被检测 。
> GFW应该是检测不出来直接把443端口给封了，可能是觉得这个网站有大流量出入，但网站却没什么内容被机器学习了， 可以换个网站内容

检查了，确实是443被封了，所以只能套CDN了吗？哭了

**Comment by prprDog** [comment]
> http://port.ping.pe/ 用这个网站测试一下443端口是否被封了， 近期好像都是443端口直接被封了。其他端口正常。解决方法一种就是套CDN 或者换端口 ， 但换端口更容易被检测 。
> GFW应该是检测不出来直接把443端口给封了，可能是觉得这个网站有大流量出入，但网站却没什么内容被机器学习了， 可以换个网站内容

配了个cloudflare，并且用window的nslookup指令也确实看到域名解析被成功更改了。然而依旧不行，是不是要在trojan或者nginx上配置什么？

**Comment by jinwyp** [comment]
> > http://port.ping.pe/ 用这个网站测试一下443端口是否被封了， 近期好像都是443端口直接被封了。其他端口正常。解决方法一种就是套CDN 或者换端口 ， 但换端口更容易被检测 。
> > GFW应该是检测不出来直接把443端口给封了，可能是觉得这个网站有大流量出入，但网站却没什么内容被机器学习了， 可以换个网站内容
> 
> 配了个cloudflare，并且用window的nslookup指令也确实看到域名解析被成功更改了。然而依旧不行，是不是要在trojan或者nginx上配置什么？

需要用支持CDN的协议 例如websocket 而且CDN只能用固定的几个端口 例如443 80 8080 等。不能用其他端口， 教程很多可以自行搜索

**Comment by jinwyp** [comment]
Nginx的网站页面增加了随机页面， 每次刷新主页内容是不同的

**Comment by prprDog** [comment]
> > > http://port.ping.pe/ 用这个网站测试一下443端口是否被封了， 近期好像都是443端口直接被封了。其他端口正常。解决方法一种就是套CDN 或者换端口 ， 但换端口更容易被检测 。
> > > GFW应该是检测不出来直接把443端口给封了，可能是觉得这个网站有大流量出入，但网站却没什么内容被机器学习了， 可以换个网站内容
> > 
> > 
> > 配了个cloudflare，并且用window的nslookup指令也确实看到域名解析被成功更改了。然而依旧不行，是不是要在trojan或者nginx上配置什么？
> 
> 需要用支持CDN的协议 例如websocket 而且CDN只能用固定的几个端口 例如443 80 8080 等。不能用其他端口， 教程很多可以自行搜索

我看脚本的trojan-go支持websock，应该能走CDN吧，服务端配完后发现客户端没有哪个能支持trojan-go走websock的...

**Comment by jinwyp** [comment]
> > > > http://port.ping.pe/ 用这个网站测试一下443端口是否被封了， 近期好像都是443端口直接被封了。其他端口正常。解决方法一种就是套CDN 或者换端口 ， 但换端口更容易被检测 。
> > > > GFW应该是检测不出来直接把443端口给封了，可能是觉得这个网站有大流量出入，但网站却没什么内容被机器学习了， 可以换个网站内容
> > > 
> > > 
> > > 配了个cloudflare，并且用window的nslookup指令也确实看到域名解析被成功更改了。然而依旧不行，是不是要在trojan或者nginx上配置什么？
> > 
> > 
> > 需要用支持CDN的协议 例如websocket 而且CDN只能用固定的几个端口 例如443 80 8080 等。不能用其他端口， 教程很多可以自行搜索
> 
> 我看脚本的trojan-go支持websock，应该能走CDN吧，服务端配完后发现客户端没有哪个能支持trojan-go走websock的...

qv2ray 安装trojan-go的插件应该可以

**Comment by jimsavage** [comment]
> 从昨天下午开始，通过window和安卓的v2rayN客户端均无法通过自建服务器科学上网。服务器用的是trojan + nginx 无ws和cdn
> 经过分析发现以下现象：
> 1.域名能正常访问
> 2.远程ssh能连上服务器
> 3.通过服务器端wget url能收到200返回
> 即然一切看上去都如此正常，为何仅通过代理客户端连不上呢？于是我把服务器的脚本以及trojan和nginx删了一次，用最新的脚本装了一下。发现依旧不行，现象还是以上3点。
> 如果说是某些东西被封了，能否给个验证方法，好让我死的安心。

我和你一样，我服务器用安装 xray 和 nginx, (VLess-TCP-XTLS direct) + (VLess-WS-TLS) + xray自带的trojan, 支持CDN, xray 运行在443端口。客户端用Openwrt的代理上的。你是不是阿里云的？而且我的点443能正常访问，就是不能代理。。。我都重置了N遍了。。。现在绝望的边缘

**Comment by jimsavage** [comment]
> > 从昨天下午开始，通过window和安卓的v2rayN客户端均无法通过自建服务器科学上网。服务器用的是trojan + nginx 无ws和cdn
> > 经过分析发现以下现象：
> > 1.域名能正常访问
> > 2.远程ssh能连上服务器
> > 3.通过服务器端wget url能收到200返回
> > 即然一切看上去都如此正常，为何仅通过代理客户端连不上呢？于是我把服务器的脚本以及trojan和nginx删了一次，用最新的脚本装了一下。发现依旧不行，现象还是以上3点。
> > 如果说是某些东西被封了，能否给个验证方法，好让我死的安心。
> 
> 我和你一样，我服务器用安装 xray 和 nginx, (VLess-TCP-XTLS direct) + (VLess-WS-TLS) + xray自带的trojan, 支持CDN, xray 运行在443端口。客户端用Openwrt的代理上的。你是不是阿里云的？而且我的点443能正常访问，就是不能代理。。。我都重置了N遍了。。。现在绝望的边缘

补充一个P站能上，其他果外的不行。

**Comment by jimsavage** [comment]
> > > 从昨天下午开始，通过window和安卓的v2rayN客户端均无法通过自建服务器科学上网。服务器用的是trojan + nginx 无ws和cdn
> > > 经过分析发现以下现象：
> > > 1.域名能正常访问
> > > 2.远程ssh能连上服务器
> > > 3.通过服务器端wget url能收到200返回
> > > 即然一切看上去都如此正常，为何仅通过代理客户端连不上呢？于是我把服务器的脚本以及trojan和nginx删了一次，用最新的脚本装了一下。发现依旧不行，现象还是以上3点。
> > > 如果说是某些东西被封了，能否给个验证方法，好让我死的安心。
> > 
> > 
> > 我和你一样，我服务器用安装 xray 和 nginx, (VLess-TCP-XTLS direct) + (VLess-WS-TLS) + xray自带的trojan, 支持CDN, xray 运行在443端口。客户端用Openwrt的代理上的。你是不是阿里云的？而且我的点443能正常访问，就是不能代理。。。我都重置了N遍了。。。现在绝望的边缘
> 
> 补充一个P站能上，其他果外的不行。

TG也能上了。。

**Comment by prprDog** [comment]
> > > > 从昨天下午开始，通过window和安卓的v2rayN客户端均无法通过自建服务器科学上网。服务器用的是trojan + nginx 无ws和cdn
> > > > 经过分析发现以下现象：
> > > > 1.域名能正常访问
> > > > 2.远程ssh能连上服务器
> > > > 3.通过服务器端wget url能收到200返回
> > > > 即然一切看上去都如此正常，为何仅通过代理客户端连不上呢？于是我把服务器的脚本以及trojan和nginx删了一次，用最新的脚本装了一下。发现依旧不行，现象还是以上3点。
> > > > 如果说是某些东西被封了，能否给个验证方法，好让我死的安心。
> > > 
> > > 
> > > 我和你一样，我服务器用安装 xray 和 nginx, (VLess-TCP-XTLS direct) + (VLess-WS-TLS) + xray自带的trojan, 支持CDN, xray 运行在443端口。客户端用Openwrt的代理上的。你是不是阿里云的？而且我的点443能正常访问，就是不能代理。。。我都重置了N遍了。。。现在绝望的边缘
> > 
> > 
> > 补充一个P站能上，其他果外的不行。
> 
> TG也能上了。。

我改成VLess套CDN可以了，但是巨慢无比，我直接用trojan快的不行

**Comment by jinwyp** [comment]
现在443端口已经解封了，大家可以注意下

**Comment by jimsavage** [comment]
> > > > > 从昨天下午开始，通过window和安卓的v2rayN客户端均无法通过自建服务器科学上网。服务器用的是trojan + nginx 无ws和cdn
> > > > > 经过分析发现以下现象：
> > > > > 1.域名能正常访问
> > > > > 2.远程ssh能连上服务器
> > > > > 3.通过服务器端wget url能收到200返回
> > > > > 即然一切看上去都如此正常，为何仅通过代理客户端连不上呢？于是我把服务器的脚本以及trojan和nginx删了一次，用最新的脚本装了一下。发现依旧不行，现象还是以上3点。
> > > > > 如果说是某些东西被封了，能否给个验证方法，好让我死的安心。
> > > > 
> > > > 
> > > > 我和你一样，我服务器用安装 xray 和 nginx, (VLess-TCP-XTLS direct) + (VLess-WS-TLS) + xray自带的trojan, 支持CDN, xray 运行在443端口。客户端用Openwrt的代理上的。你是不是阿里云的？而且我的点443能正常访问，就是不能代理。。。我都重置了N遍了。。。现在绝望的边缘
> > > 
> > > 
> > > 补充一个P站能上，其他果外的不行。
> > 
> > 
> > TG也能上了。。
> 
> 我改成VLess套CDN可以了，但是巨慢无比，我直接用trojan快的不行

有部分网站还是不能上，例如油管
