### ISSUE TITLE
部署一个月后节点失效

### ISSUE THREAD

**Issue by senseiod** [jinwyp/one_click_script#78]
操作系统：Debian10、Ubuntu20.10
部署选项：安装 trojan 和 nginx 不支持CDN, trojan 运行在443端口

问题：
配置后通过浏览器能正常访问http://hk.iouyi.top，但是无法访问https://hk.iouyi.top。导致Trojan失效
证书也部署了，之前部署后正常使用了一个月，且https://hk.iouyi.top能够访问，但是后来就无法使用了
重装了系统，重装了Trojan也无法使用，不止一个服务器有这样的问题，另外kr.iouyi.top和jp.iouyi.top也是同样的问题
挂上其他可用的节点就能正常访问https://hk.iouyi.top，根据猜测有可能是GFW封了443端口，但具体为什么封禁不清楚
现在我的问题是可以使用445端口等来解决问题吗？或者下次该如何避免GFW封禁？

**Comment by jinwyp** [comment]
443端口被封了 一般可以换个端口

同时检查你机器是否有上报软件 不要安装任何国产软件

可以到这个帖子讨论
https://github.com/jinwyp/one_click_script/issues/77
