### ISSUE TITLE
增强功能 关于证书自动放置

### ISSUE THREAD

**Issue by LOVEChen** [jinwyp/one_click_script#79]
是否申请证书? 默认为自动申请证书, 如果二次安装或已有证书 可以选否
如果已经有SSL证书文件请放到下面路径
xxx.com 域名证书内容文件路径 /root/website/cert/fullchain.cer 
xxx.com 域名证书私钥文件路径 /root/website/cert/private.key 

能不能把选否以后自动检测并放置文件 而不是粗暴的退出？ 感谢感谢

**Comment by jinwyp** [comment]
现在就是这样的，选否 后 会检查 /root/website/cert/fullchain.cer 如果没有该文件才会退出

**Comment by LOVEChen** [comment]
> 现在就是这样的，选否 后 会检查 /root/website/cert/fullchain.cer 如果没有该文件才会退出

老板好，因为默认卸载后保留证书，然后这个文件会被清除，需要重新放置，就是想问，能不能完全自动放置过去。

**Comment by jinwyp** [comment]
> > 现在就是这样的，选否 后 会检查 /root/website/cert/fullchain.cer 如果没有该文件才会退出
> 
> 老板好，因为默认卸载后保留证书，然后这个文件会被清除，需要重新放置，就是想问，能不能完全自动放置过去。

新版脚本 卸载后不会在删除证书，更新脚本即可。
