### ISSUE TITLE
V2RAY的安装脚本是否要更新？

### ISSUE THREAD

**Issue by ilratchet** [jinwyp/one_click_script#8]
==========================================
      开始安装 V2ray !
==========================================
ERROR: This script has been DISCARDED, please switch to fhs-install-v2ray project.
HOW TO USE: https://github.com/v2fly/fhs-install-v2ray
TO MIGRATE: https://github.com/v2fly/fhs-install-v2ray/wiki/Migrate-from-the-old-script-to-this
./trojan_v2ray_install.sh: line 1474: /etc/v2ray/config.json: No such file or directory
sed: can't read /etc/systemd/system/v2ray.service: No such file or directory
Failed to restart v2ray.service: Unit v2ray.service not found.
Failed to restart caddy.service: Unit caddy.service not found.
======================================================================

**Comment by jinwyp** [comment]
最近caddy2 和 v2ray都有些变化，准备把caddy 去掉， 用nginx + v2ray

**Comment by jinwyp** [comment]
已经修复该问题
