### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by zhl111** [jinwyp/one_click_script#80]
我只有一个阿里的域名，
之前设置了一个二级域名，解析到一个vps
现在我设置了第二个二级域名，想解析到另一个vps地址
但安装时，总提示我  域名解析地址与本VPS IP地址不一致!
ping完，地址是对的哦
请教：一个域名不能在二级域名里映射2个IP吗？
如果能，该怎么操作？
谢谢

**Comment by jinwyp** [comment]
在检测域名的地方 可以选择不检测域名，继续就可以。

或者 阿里的域名可能设置后变更比较慢，等一天试试再试试

**Comment by zhl111** [comment]
感谢回复，等了2天还是不行。还是这个问题：一个域名能在二级域名里映射2个以上IP吗？
如果能，还有哪里可能没设置对？
如果不能，我就不研究了

**Comment by jinwyp** [comment]
> 感谢回复，等了2天还是不行。还是这个问题：一个域名能在二级域名里映射2个以上IP吗？
> 如果能，还有哪里可能没设置对？
> 如果不能，我就不研究了

www.xxx.com 对应 IP1
www2.xxx.com 对用IP2 
肯定是没问题的

建议不要用阿里云的域名 用国外的域名商的
