### ISSUE TITLE
证书到期没有自动更新

### ISSUE THREAD

**Issue by wpzzz** [jinwyp/one_click_script#83]
trojan-go突然上不去，发现是证书到期，crontab里面命令是acme.sh自动更新，
手动执行命令后提升80端口被占用？ stop nginx之后提示更新成功，不过trojan-go依旧无效，
查看trojan-go的配置文件，发现证书指向/root/website/cert中，改成指向之前acme.sh下载的证书路径，
这下电脑trojan-qt5可以上了， 但是手机上v2rayng不行，这也太奇怪了。。

所以现在只能重新安装吗？  最新版本有解决这个问题吗

**Comment by wpzzz** [comment]
在v2rayng里面选择跳过证书验证，可以了， 但是这样估计会加到被识别的风险。
所以重装了，依旧Let's Encrypt证书，这下所有的都可以了，但以后总不能到期就重装吧

**Comment by jinwyp** [comment]
脚本自动续签的

**Comment by wpzzz** [comment]
并没有，无效的

**Comment by jinwyp** [comment]
> 并没有，无效的

新版的脚本已经解决了， 第一次申请使用了webroot模式申请证书 ，使用了ran 作为web服务器 以后更新证书后 继续使用nginx就正常了，  

之前的脚本第一次使用的是standlone 模式申请的证书 更新不正常

**Comment by Sinmists** [comment]
[Thu Jul 22 14:35:58 UTC 2021] Installing cron job
58 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
[Thu Jul 22 14:35:58 UTC 2021] Good, bash is found, so change the shebang to use bash as 
[Thu Jul 22 14:35:58 UTC 2021] OK
[Thu Jul 22 14:35:58 UTC 2021] Install success!
 ================================================== 
  开始申请证书, acme.sh 通过 standalone mode 申请 

[Thu Jul 22 14:35:59 UTC 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory

以上日志，今天安装说明第一次仍然是在用standlone 模式 @jinwyp

**Comment by jinwyp** [comment]
> # [Thu Jul 22 14:35:58 UTC 2021] Installing cron job
> 58 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
> [Thu Jul 22 14:35:58 UTC 2021] Good, bash is found, so change the shebang to use bash as
> [Thu Jul 22 14:35:58 UTC 2021] OK
> [Thu Jul 22 14:35:58 UTC 2021] Install success!
> 开始申请证书, acme.sh 通过 standalone mode 申请
> 
> [Thu Jul 22 14:35:59 UTC 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
> 
> 以上日志，今天安装说明第一次仍然是在用standlone 模式 @jinwyp

你更新脚本了吗?

你选的第几项?

在第一个菜单中都是使用webroot模式  如果在30子菜单中安装使用的是standlone模式 因为没有nginx

**Comment by Sinmists** [comment]
之前用的最新脚本,安装v2rayui面板,没有nginx,重试带nginx的确认是webroot模式,但按照这行
> 58 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
每天凌晨更新一次证书?这个频率不是会触发申请上限吗,还是我理解错了?

**Comment by jinwyp** [comment]
> 之前用的最新脚本,安装v2rayui面板,没有nginx,重试带nginx的确认是webroot模式,但按照这行
> 
> > 58 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
> 
> 每天凌晨更新一次证书?这个频率不是会触发申请上限吗,还是我理解错了?

我的脚本中安装v2ui 使用的官方脚本 , 没有申请证书也没有安装nginx, 可以通过选30后在选11 申请证书证书, 
所以你这个证书是怎么申请的我就不知道了. 

具体可以看 v2ui文档
https://blog.sprov.xyz/2019/08/03/v2-ui/
