### ISSUE TITLE
请问下解锁流媒体的 wireguard 和 CF-WARP 是运行在哪个端口？

### ISSUE THREAD

**Issue by iJayscn** [jinwyp/one_click_script#84]
Oracle的服务器只开放了 80 和 443 ，youtube等流媒体网站都不能访问。

**Comment by jinwyp** [comment]
默认好像是51820
https://www.thomas-krenn.com/en/wiki/WireGuard_Basics


WireGuard uses UDP to transmit the encrypted IP packets.
The port can be freely selected from the high ports range.
If no port is specified, WireGuard starts at 51820/UDP.
