### ISSUE TITLE
建议增加对于ARM架构的检测

### ISSUE THREAD

**Issue by wwjjhh1995** [jinwyp/one_click_script#88]
使用您的脚本进行trojan-go安装时，发现您脚本中默认下载的是x86_64架构可执行文件，手动更换armv8可执行文件后解决。
此外，arm架构中自动获取证书似乎也有些许问题，估计也是架构问题。

希望可以更新。

**Comment by jinwyp** [comment]
已经加入支持trojan ， trojan-go  ， v2ray ， xray 的arm版本下载安装
