### ISSUE TITLE
[Feature request] 利用IP地址自动签发证书

### ISSUE THREAD

**Issue by recolic** [jinwyp/one_click_script#89]
有一类ip2domain服务，可以免去小白购买和配置域名的负担。可以考虑寻找靠谱的服务并且集成。下面是一个例子：

**请勿使用我的服务。这只是一个例子，此服务不稳定** : <https://recolic.net/blog/post/convert-ip-address-to-domain-name>

这样小白可以直接输入ip地址，就能自动签发一个证书。这或许可以作为一个可选功能。

**Comment by jinwyp** [comment]
相当于用了其他人或服务商提供的一个而二级域名，感觉不太安全啊， 域名现在买一个很便宜啊， 没有域名也不会用脚本吧

**Comment by recolic** [comment]
主要是考虑到反正流量不会从他们那儿过。。anyway只是一个suggestion, never mind

Aug 31, 2021 21:19:49 JinWYP ***@***.***>:
