### ISSUE TITLE
V2ray install script outdated and removed

### ISSUE THREAD

**Issue by PScamander** [jinwyp/one_click_script#9]
Hi, this is an amazing project but I've found that the official v2ray install script this project is using has been removed by the source. Could you please kindly consider replacing it with the new script (provided by the v2fly project) or changing the source? Thank you very much and good day to you

**Comment by enkka** [comment]
have not fixed yet

==========================================
      开始安装 V2ray !
==========================================
ERROR: This script has been DISCARDED, please switch to fhs-install-v2ray project.
HOW TO USE: https://github.com/v2fly/fhs-install-v2ray
TO MIGRATE: https://github.com/v2fly/fhs-install-v2ray/wiki/Migrate-from-the-old-script-to-this
./trojan_v2ray_install.sh: line 1474: /etc/v2ray/config.json: No such file or directory
sed: can't read /etc/systemd/system/v2ray.service: No such file or directory
sudo: unable to resolve host shanfeng: Name or service not known
Failed to restart v2ray.service: Unit v2ray.service not found.
sudo: unable to resolve host shanfeng: Name or service not known
Failed to restart caddy.service: Unit caddy.service not found.

**Comment by jinwyp** [comment]
Fixed, pls update your script and run

**Comment by PScamander** [comment]
> Fixed, pls update your script and run

Hi, thank you so much for updating the script. I have tried it today, however, it has not been successful. I was able to install trojan successfully but never was I able to install v2ray. Here's the log:
  MacOS 客户端另一个版本下载：https://github.com/Trojan-Qt5/Trojan-Qt5/releases
3 Android 客户端下载 https://github.com/trojan-gfw/igniter/releases 
4 iOS 客户端 请安装小火箭 https://shadowsockshelp.github.io/ios/ 
  iOS 请安装小火箭另一个地址 https://lueyingpro.github.io/shadowrocket/index.html 
  iOS 安装小火箭遇到问题 教程 https://github.com/shadowrocketHelp/help/ 
======================================================================
教程与其他资源:
访问 https://www.v2rayssr.com/trojan-1.html ‎ 下载 浏览器插件 客户端 及教程
访问 https://westworldss.com/portal/page/download ‎ 下载 客户端 及教程
======================================================================
其他 Windows 客户端:
https://github.com/TheWanderingCoel/Trojan-Qt5/releases (exe为Win客户端, dmg为Mac客户端)
https://github.com/Qv2ray/Qv2ray/releases (exe为Win客户端, dmg为Mac客户端)
https://github.com/Dr-Incognito/V2Ray-Desktop/releases (exe为Win客户端, dmg为Mac客户端)
https://github.com/Fndroid/clash_for_windows_pkg/releases
======================================================================
其他 Mac 客户端:
https://github.com/TheWanderingCoel/Trojan-Qt5/releases (exe为Win客户端, dmg为Mac客户端)
https://github.com/Qv2ray/Qv2ray/releases (exe为Win客户端, dmg为Mac客户端)
https://github.com/Dr-Incognito/V2Ray-Desktop/releases (exe为Win客户端, dmg为Mac客户端)
https://github.com/JimLee1996/TrojanX/releases (exe为Win客户端, dmg为Mac客户端)
https://github.com/yichengchen/clashX/releases 
======================================================================
其他 Android 客户端:
https://github.com/trojan-gfw/igniter/releases 
https://github.com/Kr328/ClashForAndroid/releases 
======================================================================
 ==================================================
  已安装过 V2ray, 退出安装 !
 ==================================================


You can see here that it just doesn't install. It constantly skips v2ray installation despite it being not installed in the first place. Could you please look at the script for a little and see if this issue could be fixed? Thanks a lot for your work. I am very grateful indeed.

**Comment by jinwyp** [comment]
> > Fixed, pls update your script and run
> 
> # Hi, thank you so much for updating the script. I have tried it today, however, it has not been successful. I was able to install trojan successfully but never was I able to install v2ray. Here's the log:
> MacOS 客户端另一个版本下载：https://github.com/Trojan-Qt5/Trojan-Qt5/releases
> 3 Android 客户端下载 https://github.com/trojan-gfw/igniter/releases
> 4 iOS 客户端 请安装小火箭 https://shadowsockshelp.github.io/ios/
> iOS 请安装小火箭另一个地址 https://lueyingpro.github.io/shadowrocket/index.html
> iOS 安装小火箭遇到问题 教程 https://github.com/shadowrocketHelp/help/
> # 教程与其他资源:
> 访问 https://www.v2rayssr.com/trojan-1.html ‎ 下载 浏览器插件 客户端 及教程
> 访问 https://westworldss.com/portal/page/download ‎ 下载 客户端 及教程
> # 其他 Windows 客户端:
> https://github.com/TheWanderingCoel/Trojan-Qt5/releases (exe为Win客户端, dmg为Mac客户端)
> https://github.com/Qv2ray/Qv2ray/releases (exe为Win客户端, dmg为Mac客户端)
> https://github.com/Dr-Incognito/V2Ray-Desktop/releases (exe为Win客户端, dmg为Mac客户端)
> https://github.com/Fndroid/clash_for_windows_pkg/releases
> # 其他 Mac 客户端:
> https://github.com/TheWanderingCoel/Trojan-Qt5/releases (exe为Win客户端, dmg为Mac客户端)
> https://github.com/Qv2ray/Qv2ray/releases (exe为Win客户端, dmg为Mac客户端)
> https://github.com/Dr-Incognito/V2Ray-Desktop/releases (exe为Win客户端, dmg为Mac客户端)
> https://github.com/JimLee1996/TrojanX/releases (exe为Win客户端, dmg为Mac客户端)
> https://github.com/yichengchen/clashX/releases
> # 其他 Android 客户端:
> https://github.com/trojan-gfw/igniter/releases
> https://github.com/Kr328/ClashForAndroid/releases
> # ==================================================
> 已安装过 V2ray, 退出安装 !
> You can see here that it just doesn't install. It constantly skips v2ray installation despite it being not installed in the first place. Could you please look at the script for a little and see if this issue could be fixed? Thanks a lot for your work. I am very grateful indeed.

Because you haved installed v2ray.   
So the better way you install this script on a new VPS. 

Or delete  "/usr/local/bin/v2ray" and  "/usr/bin/v2ray" file , Then Run this script , select 17 to Uninstall trojan and v2ray  . Then Select 15 to install trojan and v2ray
