### ISSUE TITLE
VLess-TCP-TLS无法连接

### ISSUE THREAD

**Issue by TheWhiteDog9487** [jinwyp/one_click_script#90]
配置全部都是按脚本输出信息填的
【Xray客户端 VLess-TCP-TLS】无法连接，V2rayN报错app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: operation was canceled] > common/retry: all retry attempts failed，Firefox报错建立安全连接失败，PR_END_OF_FILE_ERROR
同端口同地址的【Xray客户端 VLess-WS-TLS】反而可以完全正常使用，没半点问题
这迹象感觉也不是封端口，不懂到底是怎么回事
![Snipaste_2021-09-22_20-24-17](https://user-images.githubusercontent.com/60037547/134343024-d1d83ef8-da45-4398-a961-7131253d5f68.png)

**Comment by jinwyp** [comment]
什么系统? 选的菜单第几项安装的?

**Comment by TheWhiteDog9487** [comment]
> 
> 
> 什么系统? 选的菜单第几项安装的?

系统是Ubuntu 21.04 (GNU/Linux 5.11.0-34-generic x86_64)
第一个菜单选的是30，因为我已经装了Nginx跑网站
第二个菜单选的应该是23或24，记不清了
还有一个点是在用脚本之前我已经用Certbot签了证书，我用符号连接把证书和私钥连接到/root/website/cert

**Comment by jinwyp** [comment]
> > 什么系统? 选的菜单第几项安装的?
> 
> 系统是Ubuntu 21.04 (GNU/Linux 5.11.0-34-generic x86_64)
> 第一个菜单选的是30，因为我已经装了Nginx跑网站
> 第二个菜单选的应该是23或24，记不清了
> 还有一个点是在用脚本之前我已经用Certbot签了证书，我用符号连接把证书和私钥连接到/root/website/cert

我试了一下 选30后选23 的 VLess-TCP-TLS   
直接用安装后复制导入链接 vless:// 开头的 没有问题  
证书用的我脚本的证书  

可以运行 systemctl status xray.service 看看是否启动正常， xray 占用443端口， 是否和nginx 端口冲突

**Comment by TheWhiteDog9487** [comment]
> 
> 
> > > 什么系统? 选的菜单第几项安装的?
> > 
> > 
> > 系统是Ubuntu 21.04 (GNU/Linux 5.11.0-34-generic x86_64)
> > 第一个菜单选的是30，因为我已经装了Nginx跑网站
> > 第二个菜单选的应该是23或24，记不清了
> > 还有一个点是在用脚本之前我已经用Certbot签了证书，我用符号连接把证书和私钥连接到/root/website/cert
> 
> 我试了一下 选30后选23 的 VLess-TCP-TLS 直接用安装后复制导入链接 vless:// 开头的 没有问题 证书用的我脚本的证书
> 
> 可以运行 systemctl status xray.service 看看是否启动正常， xray 占用443端口， 是否和nginx 端口冲突

新发现一种可能性：
不知道脚本为什么没有侦测到我的主机名和公网IP，输出配置信息和导入链接的地址全都没有连接地址，还是我手动加上去的。
WS的连接地址直接输入IP也是会建立安全连接失败，换成主机名之后就正常了，猜测是证书的原因
我想有没有可能是没侦测到地址所以自动配置出了点问题？
