### ISSUE TITLE
报告几个bug

### ISSUE THREAD

**Issue by wpzzz** [jinwyp/one_click_script#91]
申请证书失败，发现是nginx未安装，提示
Skipping acquire of configured file 'nginx/binary-i386/Packages' as repository 'https://nginx.org/packages/ubuntu focal InRelease' doesn't support architecture 'i386'
需要修改证书中的/etc/apt/sources.list.d/nginx.list部分

重试之后还是不行， 提示unzip未安装，  重新手动安装后成功

**Comment by jinwyp** [comment]
1 什么系统 2选的菜单第几项安装的?

**Comment by yaak63** [comment]
我也遇到同样问题，可能是用的freenom免费域名，现在cloudflare不支持申请与更新证书了。

**Comment by jinwyp** [comment]
> 我也遇到同样问题，可能是用的freenom免费域名，现在cloudflare不支持申请与更新证书了。

与免费域名没关, cloudflare只是DNS申请证书的模式受限制, 而脚本可以用http模式申请 不影响

我刚试过 没问题,免费域名 不要用DNS模式申请

**Comment by wpzzz** [comment]
ubuntu20
第五项
非arm
