### ISSUE TITLE
出错了！

### ISSUE THREAD

**Issue by yiranfeiyang1981** [jinwyp/one_click_script#92]
默认通过 Letsencrypt.org 来申请证书, 如果证书申请失败, 例如一天内通过 Letsencrypt.org 申请次数过多, 可以选否通过 BuyPass.com 来申请.
是否通过 Letsencrypt.org 来申请证书? 默认直接回车为是, 选否则通过 BuyPass.com 来申请, 请输入[Y/n]:
./trojan_v2ray_install.sh: line 1035: /root/.acme.sh/acme.sh: No such file or directory

./trojan_v2ray_install.sh: line 1049: /root/.acme.sh/acme.sh: No such file or directory
 ================================================== 
 ================================================== 
 https证书没有申请成功，安装失败!
 请检查域名和DNS是否生效, 同一域名请不要一天内多次申请!
 请检查80和443端口是否开启, VPS服务商可能需要添加额外防火墙规则，例如阿里云、谷歌云等!
 重启VPS, 重新执行脚本, 可重新选择该项再次申请证书 ! 
 ==================================================

**Comment by yiranfeiyang1981** [comment]
Centos7.1_64bit

**Comment by jinwyp** [comment]
脚本没问题 检查你的vps网络是否有问题  运行一下命令 安装acme.sh 脚本 是不是网络问题
curl https://get.acme.sh | sh

不要在国内vps安装，检查网络是否能访问 curl https://get.acme.sh

**Comment by yiranfeiyang1981** [comment]
刚刚查看才发现 NGINX竟然没有安装 我使用的方案是5

[root@F11-A23 ~]# systemctl start nginx.service
Failed to start nginx.service: Unit not found.
[root@F11-A23 ~]# vi /etc/nginx/nginx.conf

**Comment by yiranfeiyang1981** [comment]
Failed to start nginx.service: Unit not found.
 ================================================== 
       Web服务器 nginx 安装成功!!

**Comment by jinwyp** [comment]
你证书没申请成功当然失败了, 卸载后 检查你的vps网络吧

**Comment by yiranfeiyang1981** [comment]
安装V2RAY 14 也是提示这个，但是竟然莫名其妙可以用了，   nginx 配置路径 /etc/nginx/nginx.conf  目录下面这个配置文件也没有！感觉NGINX 没有被安装！证书我查看目录了没有问题，感谢大佬回复！

**Comment by yiranfeiyang1981** [comment]
伪装网站提示

500 Internal Privoxy Error
Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

**Comment by yiranfeiyang1981** [comment]
难道是我安装宝塔的原因？？？？？？？

**Comment by jinwyp** [comment]
安装宝塔肯定安装nginx了啊， 所以用我的脚本nginx安装失败了。 可以选30子菜单里面不安装nginx的版本。 注意端口443不要与nginx冲突

**Comment by yiranfeiyang1981** [comment]
Loaded plugins: fastestmirror
No Match for argument: nginx
No Packages marked for removal

**Comment by yiranfeiyang1981** [comment]
关键问题 我的宝塔没有安装NGINX 我先重装系统重新试试！

**Comment by yiranfeiyang1981** [comment]
找到证书安装失败的原因了！
 ================================================== 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   937    0   937    0     0   2040      0 --:--:-- --:--:-- --:--:--  2036
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  203k  100  203k    0     0   174k      0  0:00:01  0:00:01 --:--:--  174k
[Wed Sep 29 01:32:26 CST 2021] Installing from online archive.
[Wed Sep 29 01:32:26 CST 2021] Downloading https://github.com/acmesh-official/acme.sh/archive/master.tar.gz
[Wed Sep 29 01:32:29 CST 2021] Extracting master.tar.gz
[Wed Sep 29 01:32:29 CST 2021] Please install openssl first. ACME_OPENSSL_BIN=openssl
[Wed Sep 29 01:32:29 CST 2021] We need openssl to generate keys.
[Wed Sep 29 01:32:29 CST 2021] Pre-check failed, can not install.

请问标准安装系统是那个？

**Comment by jinwyp** [comment]
我一般用centos7 安装 5.10内核比较快， 其他系统也应该可以， 你的问题可能和宝塔冲突了， 新干净系统应该没问题
