### ISSUE TITLE
安装成功后发现nginx v2ray都没启动查看状态V2RAY提示无权限！

### ISSUE THREAD

**Issue by yiranfeiyang1981** [jinwyp/one_click_script#93]
安装成功后发现nginx v2ray都没启动查看状态V2RAY提示无权限！
重启机器 手动启动NGINX V2RAY 系统没有自动启动，是否需要手动添加启动项！

**Comment by jinwyp** [comment]
安装的第几项？ 什么系统？

建议你换台其他服务商的VPS， 你的VPS可能访问github有问题 或用centos7 系统 试试
