### ISSUE TITLE
使用脚本的11进行安装后在Cloudflare的workers里添加加速，但是发送测试提示我证书过期。

### ISSUE THREAD

**Issue by xifeng0** [jinwyp/one_click_script#94]
502 Bad Gateway
content-length:1375
content-type:text/html; charset=UTF-8

<!DOCTYPE html>

<html>
  <head>
    <title>Error communicating with origin</title>
    <link rel="stylesheet" id="cf_styles-css" href="https://cloudflareworkers.com/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
    <style type="text/css">body{margin:0;padding:0}</style>
  </head>
  <body>
    <div id="cf-wrapper">
      <div id="cf-error-details" class="cf-error-details-wrapper">
        <div class="cf-wrapper cf-header cf-error-overview">
          <h1>
            <span class="cf-error-type" data-translate="error">Uh oh...</span>
          </h1>
          <h2 class="cf-subheadline" data-translate="error_desc">Error communicating with origin server hk.xifeng.ga</h2>
        </div>

        <section></section>

        <div class="cf-section cf-wrapper">
          <h2 data-translate="what_happened">Details</h2>
          <p><code style="font-family:monospace">TLS peer's certificate is not trusted; reason = certificate has expired</code></p>
        </div>

        <div class="cf-error-footer cf-wrapper">
          <p>
            <span class="cf-footer-item"><span data-translate="performance_security_by">Performance &amp; security by</span> <a href="https://www.cloudflare.com" target="_blank">Cloudflare</a></span>
          </p>
        </div>
      </div>
    </div>

  </body>
</html>
明明网页显示证书没有过期，但是CF在发送测试返回的是502错误，但是我自己用浏览器打开workers的链接缺可以正常打开网页。

**Comment by jinwyp** [comment]
没用过这个worker 不清楚怎么解决
