### ISSUE TITLE
bbr plus 5.14内核升级了

### ISSUE THREAD

**Issue by longmoon77** [jinwyp/one_click_script#96]
UJX6N已将bbrplus 5.14内核升级，因此脚本安装显示404，请尽快更新，感谢。
![IMG_20211106_165938.jpg](https://user-images.githubusercontent.com/62339707/140604121-f61dfb73-a8b9-49fd-8819-75619ca2cff3.jpg)

**Comment by jinwyp** [comment]
已更新 最近UJX6N 更新的太频繁了
