### ISSUE TITLE
centos7/ubuntu18 Nginx安装失败

### ISSUE THREAD

**Issue by SoYeonQwQ** [jinwyp/one_click_script#97]
输入2或5之后，直接就报错，安装完成后启动不了Nginx，机房为搬瓦工，centos7，内核原版和5.10，5.14都试过

请输入数字:5
Loaded plugins: fastestmirror
base                                                                        | 3.6 kB  00:00:00     
extras                                                                      | 2.9 kB  00:00:00     
https://nginx.org/packages/centos/7/x86_64/repodata/repomd.xml: [Errno 14] curl#60 - "Peer's Certificate issuer is not recognized."
Trying other mirror.
It was impossible to connect to the CentOS servers.
This could mean a connectivity issue in your environment, such as the requirement to configure a proxy,
or a transparent proxy that tampers with TLS security, or an incorrect system clock.
Please collect information about the specific failure that occurs in your environment,
using the instructions in: https://access.redhat.com/solutions/1527033 and create a bug on https://bugs.centos.org/

 One of the configured repositories failed (nginx repo),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=nginx ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable nginx
        or
            subscription-manager repos --disable=nginx

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=nginx.skip_if_unavailable=true

failure: repodata/repomd.xml from nginx: [Errno 256] No more mirrors to try.
https://nginx.org/packages/centos/7/x86_64/repodata/repomd.xml: [Errno 14] curl#60 - "Peer's Certificate issuer is not recognized."
 关闭防火墙 firewalld

**Comment by SoYeonQwQ** [comment]
重新安装了ubuntu20，5.4内核可以成功安装nginx，更新5.10内核安装后有依赖版本不对，安装失败。最后是在5.4上装好trojan和nginx后，再更新内核到5.10，现在一切正常。。 前面的Ubuntu18安装不成功，有没有可能是时区设置不对的原因？因为内核版本一样的，但是时区不一样，会报这个 "Peer's Certificate issuer is not recognized."吗？

**Comment by jinwyp** [comment]
我一般会VPS新机器会设置社区为北京时间，  这问题没遇到过， 一些解决方法供参考 https://shouts.dev/centos-curl-error-60-peers-certificate-issuer-is-not-recognized-solved

**Comment by jinwyp** [comment]
新开了一台 vultr的 centos7的机器  安装 一切正常  

新机器安装顺序 运行我脚本后 选34 设置北京时区， 然后选31 安装软件 后 在选2 安装trojan和nginx

我的域名是cloudflare 不是国内的腾讯等(尽量不要用国内的域名商 出问题不知道什么原因) 安装完毕后网站可以正常打开 chrome带有https锁头标志

搬瓦工的机器选择系统时要选择不带bbr的原版内核系统
